deepmodeling/deepmd-kit

source/lmp/pair_nnp.cpp, source/lmp/pair_nnp.h.in
There are still two problems:
1. If the `atom_style` is not `atomic` (e.g. `charge`), the order of `std_f` is different from that of atom ids.
2. Now the code cannot run with MPI.
=> print each atom's deviation

.travis.yml, setup.py
Then, we can use `python setup.py sdist` to package the source, and use `twine upload dist/*` to upload it to [pypi.org](https://pypi.org/simple). Users can use `pip install deepmd-kit` to install the python interface directly.
=> use setuptools_scm instead of setuptools-git-version

README.md, source/CMakeLists.txt
also fix a bug and update README
Currently, if a user uses gcc 4.8.5, he/she needs to modify `CMakeLists.txt` to disable native MD and i-Pi on his/her own. Why not detect gcc version and do it automatically?
=> disable native md and i-pi automaticaly if gcc<4.9

doc/install-tf.1.14-gpu.md
When compile tensorflow_cc, the dependencies of tensorflow have been downloaded already. So we don't need to download them again. Also, it seems that `libprotobuf.a` and `libnsync.a` are useless. I think they may be already a part of tensorflow. We only need to move headers to `include` folder.
It works well, but **please check it again**.
=> simplify installation of TensorFlow

.travis.yml
and users will be able to use `pip install tensorflow deepmd-kit` to install wheels without building it.
Notes:
v1.1.2 has been built and I successfully installed and used it in Google Colab: https://colab.research.google.com/drive/1FTVKNG76nsYaJ_mYywz_R7swa5c7BWEe
=> use travis-ci to build wheels and upload to pypi

source/lib/include/NNPInter.h, source/lib/src/NNPInter.cc
```cpp
std::string type_map;
nnp_inter.get_type_map(type_map);
std::cout << "type_map:" << type_map << "\n";
```
output:
```
type_map:O H
```
=> add get_type_map for c++ api

source/train/DescrptSeA.py, source/train/DescrptSeR.py, source/train/Fitting.py
1. allows no interaction between custom atom types
usage:
```json
"descriptor" :{
"no_inter_types": [[0,0],[0,1],[0,3],[0,5],[1,1],[1,3],[1,5],[3,3],[3,5],[5,5],[2,2],[2,4],[4,4]]
}
```
2. supports user-specified atomic energy
usage:
```json
"fitting_net" : {
"atom_ener": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
}
```
3. supports setting davg of descriptor to 0
usage:
```json
"descriptor" :{
"set_davg_zero": true
}
```
=> allows no interaction and supports user-specified atomic energy

source/lmp/pair_nnp.cpp
log.cite file will be generated when running LAMMPS...
=> Call LAMMPS builtin citeme function

source/lib/src/NNPInter.cc, source/op/cuda/descrpt_se_a.cu, source/op/descrpt_se_a_gpu.cc, source/train/CMakeLists.txt
Increase max neighbor size from 256 to 1024 and fix a potential bug of install transform.py in $deepmd_source_dir/source/op/train/CMakeLists.txt
=> increase max neighbor size from 256 to 1024

.gitignore, README.md, source/tests/test_deepmd_data_sys.py, source/train/DataSystem.py, source/train/Trainer.py, source/train/common.py
When one is dealing with multiple systems which have very distinct numbers of frames setting number of tests as only one integer which is same for all systems is rather restraining. For example consider two systems:
1. system with 10000 frames
2. system with 100 frames
Setting number of tests to 10 should be ideal for the second system but is far too low for the first one. There is no good solution to this situation, since increasing test number to say 100 would be appropriate for the first system but wrong for the second.
The change I propose simply allows to set `numb_test` parameter as a list with separate value for each system or as a string specifying a percentage of the systems frames that should be used for testing.
In the first case, number of tests could be specified in json as …
=> Enable setting test size individually for each system

source/train/Trainer.py
Usually, the type number of the model should be equal to that of the data
However, nt_model > nt_data should be allowed, since users may only want to
train using a dataset that only have some of elements
=> allow ntypes_model > ntypes_data (fix #261)

deepmd/utils/neighbor_stat.py, source/lib/CMakeLists.txt, source/lib/include/DeviceFunctor.h, source/lib/include/NNPInter.h, source/lib/src/NNPInter.cc, source/lmp/pair_nnp.cpp, source/lmp/pair_nnp.h.in, source/op/descrpt_se_a_multi_device.cc, source/op/descrpt_se_r_multi_device.cc
- bcast the modle files to all MPI processors.
- fix a bug, change the default memory size of temporary tensor(used in descrpt_se_a.cu)to nloc * GPU_MAX_NBOR_SIZE(4096) to avoid a potential GPU memory access error.
- fix a bug, rm print in class NeighborStat.
=> send model file through mpi bcast

source/lib/src/NNPInter.cc, source/lmp/pair_nnp.cpp
1. Do nothing if the C++ interface is initialized more than once. Solves issue #370 
2. set the `restartinfo` to `0` because the pair_style `deepmd` does not support restarting from lammps restart file. Solve the issue #329
=> Fix lammps related bugs

deepmd/entrypoints/train.py, deepmd/train/trainer.py, deepmd/utils/data_system.py
Bug fixings: 
1, when valid data is not given; 
2, bug related to iterate over a dict.  
Enhancement:
1, Not using ClassArg in trainer anymore
2, print name of the dataset in the summary of `DeepmdDataSystem`
=> Bug fixings related to using validate dataset

deepmd/entrypoints/train.py, deepmd/train/trainer.py, deepmd/utils/data_system.py
- printing the training error with exactly the batch used to train 
- remove the size of test data in `print_summary`
- fix bug of averaging over batches.
=> Printing the training error with exactly the batch used to train 

deepmd/entrypoints/train.py, deepmd/utils/compat.py, source/tests/compat_inputs/water_v2.json, source/tests/test_compat_input.py
=> Auto conversion of input script from v1 to v2 

deepmd/utils/argcheck.py, doc/train-input-auto.rst
- generated with updated dargs
=> update doc: changed name of descriptors.

source/cmake/Findtensorflow.cmake
In conda-forge's recent released tensorflow, protobuf is external
from tensorflow and not inside the tensorflow directory.
=> Do not find protobuf for python

source/CMakeLists.txt
Clang doesn't support this flag, cause an error on osx:
> ld: unknown option: --no-as-needed
This commit should be cherry-picked to `r1.2` branch.
=> only enable link what you use on GNU compilers

deepmd/loss/tensor.py
Close the loss normalization of dipole loss, since it can't improve the performance and might lead to unstability of small norm data
**Author:** YWolfeee
**Date:** Apr, 23, 2021
=> Close loss normalization

deepmd/descriptor/se_a.py, deepmd/fit/ener.py, deepmd/model/ener.py, deepmd/train/trainer.py, deepmd/utils/argcheck.py, deepmd/utils/network.py, deepmd/utils/type_embed.py, doc/train-input-auto.rst, examples/water/se_e2_a_tebd/input.json, source/tests/common.py, source/tests/test_descrpt_se_a_type.py, source/tests/test_fitting_ener_type.py, source/tests/test_model_se_a.py, source/tests/test_model_se_a_type.py, source/tests/test_type_embed.py, source/tests/water_se_a_type.json
- add type embedding
- refact descriptor `se_e2_a`
- refact fitting `ener`
=> Add type embedding

doc/getting-started.md, source/lmp/pair_deepmd.cpp, source/lmp/pair_deepmd.h.in
=> support MPI and other atom_styles for LAMMPS atomic keyword

source/lmp/pair_deepmd.cpp, source/lmp/pair_deepmd.h.in
This ensures the out file will not be override when LAMMPS restarts.
This commit may be conflicted with #392. Commit
https://github.com/deepmodeling/deepmd-kit/commit/5597ea2b49f96e99a52a9779b04b6c12e5a79a04 should be dropped.
Resolves #623.
=> append to out_file when LAMMPS restarts

source/api_cc/tests/test_deeppot_model_devi.cc
add test case to ensure that the c++ model devi is consistent with python model devi
=> UT for model devi C++ interface

.github/workflows/build_cc.yml, doc/install.md, setup.py, source/install/build_cc.sh
=> add CUDA/ROCM documents & fix CI (fix #730)

.gitignore, deepmd/utils/neighbor_stat.py, deepmd/utils/tabulate.py, requirements.txt
tqdm is not used at present. It may be imported in #350 for tests, but since it is not really used for production, it is safe to remove this requirement.
=> remove unused tqdm 

requirements.txt
We don't need typing_extensions for python>=3.7.
See:
[1] https://pypi.org/project/typing-extensions/
[2] https://www.python.org/dev/peps/pep-0508/
=> remove typing_extensions for python>=3.7

source/lib/src/cuda/CMakeLists.txt
cuda<=10 doesn't support `-std=c++17`, but conda compilers will add
it into the flag. We can friendly remove such flag to prevent users
go here and ask #428.
fix #755.
=> remove `-std=c++17` for cuda<=10

doc/development/index.md, doc/development/type-embedding.md, doc/train-se-e2-a-tebd.md
=> add type-embedding developer doc

deepmd/train/trainer.py
This PR fix error that `paddle.set_device()` only make sense in forward step, which may cause Tensor allocated in wrong devices
=> fix change device error code

doc/install.md
=> add documents for conda

deepmd/descriptor/loc_frame.py, deepmd/descriptor/se_a.py, deepmd/descriptor/se_a_ef.py, deepmd/descriptor/se_r.py, deepmd/descriptor/se_t.py, deepmd/entrypoints/freeze.py, deepmd/entrypoints/train.py, deepmd/infer/data_modifier.py, deepmd/infer/deep_eval.py, deepmd/infer/deep_pot.py, deepmd/infer/deep_tensor.py, deepmd/infer/ewald_recp.py, deepmd/loss/ener.py, deepmd/loss/tensor.py, deepmd/train/trainer.py, deepmd/utils/neighbor_stat.py, deepmd/utils/sess.py, deepmd/utils/tabulate.py, source/lib/include/gpu_cuda.h
=> add OOM message

source/lib/src/rocm/prod_force.hip.cu, source/lib/src/rocm/prod_virial.hip.cu
This PR works on optimizing ROCm kernel which uses atomicAdd. 
By the experiments before, we already knew that atomicAdd on CUDA is much more efficient than on ROCm. A straightforward idea is to reduce the calling number of atomicAdd instruction.  By pre-summing the four values before doing atomicAdd, we gains nearly **4 times** speedup on `force_deriv_wrt_neighbors_a` and `virial_deriv_wrt_neighbors_a` ROCm kernels. 
Moreover, by switching the computing order inside and cross a block, we aim to reduce the crashing of writing same global memory address. In our benchmark, this switching gets **1.4 ~ 2.2 times** speedup.
We also benchmark the E2E performance on LAMMPS inference. On compressed copper model, this work gets **1.45x** speedup on pairs computing.
Baseline: …
=> speedup ROCm kernel which uses atomicAdd

source/lib/src/cuda/tabulate.cu
This PR works on tabulate fusion CUDA kernel, including:
* speedup `tabulate_fusion_fifth_order_polynomial` kernel 1.3 times by reducing shm using (and thread syncing). 
* fix misusage between `KTILE` and `MTILE` in `tabulate_fusion_grad_fifth_order_polynomial` kernel.
* format the `warp_idx` variable used in `tabulate_fusion_grad_fifth_order_polynomial` kernel.
=> speedup tabulate cuda kernel by reducing shm using

doc/install.md, setup.py
In some develop environment, CUDA/ROCm toolkit root cannot be detected automatically. This PR fixes it by allowing user to specify toolkit root as environment variable.
=> support to specify CUDA/ROCm root in python pkg building

deepmd/entrypoints/__init__.py, deepmd/entrypoints/main.py, deepmd/entrypoints/train.py, deepmd/utils/argcheck.py, doc/train-input-auto.rst, source/tests/test_train.py
Notice :
- The function `train` in the module `deepmd.entrypoints.train` is renamed to `train_dp` to avoid the conflict between the module and the function name, which causes trouble in the UT for the auto sel
=> automatically determine the `sel` from the training data.

source/lib/src/rocm/prod_env_mat.hip.cu
This PR works on  optimizing ROCm function format_nlist_b.
In the previous work, one thread in a thread block handles all neighbors of one center atom. therefore, the parallel granularity is coarse. Besides, Threads in a thread block access memory which is not coalesced.
A straightforward way is to make threads in a block handle a part of  neighbors of a center atom. Before doing this, we have to do a preprocession on nei_iter array, which doesn't take too much time. In our benchmark, this optimization gets ≈7x speed up.
We also benchmark the E2E performance on LAMMPS inference. On compressed water model, this work gets ≈1.05x speedup on pairs computing.
Baseline:
[hcctrace.out.before.json.zip](https://github.com/deepmodeling/deepmd-kit/files/6773890/hcctrace.out.before.json.zip)
After …
=> speed up format_nlist_b

deepmd/entrypoints/compress.py, deepmd/train/trainer.py, deepmd/utils/errors.py
=> add message for DecodeError

source/lib/src/cuda/prod_env_mat.cu
This change in CUDA improves little performance. I open this PR for keeping code consistent with Rocm.
On compressed water model, this work gets ≈1.38x speeds up in format_nlist_b.
The impact on E2E performance on LAMMPS inference is negligible.
Baseline:
[report1_before.qdrep.zip](https://github.com/deepmodeling/deepmd-kit/files/6807650/report1_before.qdrep.zip)
After modification:
[report1_after.qdrep.zip](https://github.com/deepmodeling/deepmd-kit/files/6807656/report1_after.qdrep.zip)
=> Synchronize format_nlist_b in CUDA with ROCm

source/lib/src/cuda/CMakeLists.txt
CUDA 11 has included cub, so we don't need to include it any more.
cub can be upgraded along with the CUDA Toolkit to obtain bugfixes.
See https://github.com/NVIDIA/cub#releases.
See also https://github.com/NVIDIA/cub/blob/main/CHANGELOG.md.
P.S. It's still unclear to me that which version of C++ it supports.  (#755)
=> remove cub include for CUDA>=11

deepmd/env.py, deepmd/model/ener.py, deepmd/train/trainer.py, setup.py, source/op/paddle_ops/srcs/pd_prod_env_mat_multi_devices_cpu.cc, source/op/paddle_ops/srcs/pd_prod_force_se_a_multi_devices_cpu.cc, source/op/paddle_ops/srcs/pd_prod_virial_se_a_multi_devices_cpu.cc
Following issues fixed:
1. Removed @paddle.jit.to_static decorator. Model will be converted to
static graph at save time.
2. Manually set InputSpec for "Ener" model with "se_a" descriptor
3. Due to lack of support for "double" datatype at inference time,
default training precision was set to float (low precision)
=> [Paddle] Fixed model save issues with Ener model

deepmd/train/trainer.py, examples/water/train/water_se_a.json, source/op/paddle_ops/srcs/pd_prod_env_mat_multi_devices_cpu.cc, source/op/paddle_ops/srcs/pd_prod_force_se_a_multi_devices_cpu.cc, source/op/paddle_ops/srcs/pd_prod_virial_se_a_multi_devices_cpu.cc, source/tests/test_pd_prod_force_and_virial.py
Detected functional regression between CUDA 10.1 and CUDA 11.2
Therefore force 3 custom ops, namely "env_mat", "force_se_a" and "virial_se_a" to fallback on CPU
Minor changes to save_model function in "trainer.py" to suppress dynamic-to-static warnings
=> Force env_mat force_se_a virial_se_a to fallback on CPU

deepmd/utils/neighbor_stat.py
atoms with no neighbors generate empty neighbor distance array causing np.min to crush.
add safe check and warning for atoms with no neighbors
=> Fix the empty neighbor distance array in neighbor_stat.py 

deepmd/descriptor/se_a.py, deepmd/descriptor/se_r.py
Fix #899. See comments in the code for details.
Also optimize to directly return zero matrix for exclude_types. As everything is zero, calculate something like zero times a number is meaningless.
=> fix `InvalidArgumentError` caused by zero `sel` and optimize zero matrix

deepmd/cluster/local.py, deepmd/cluster/slurm.py, deepmd/train/run_options.py, requirements.txt
Before this pull request, the implementation of GPU discovery at `deepmd.cluster.local` and `deepmd.cluster.slurm` is based on the environment variable `CUDA_VISIBLE_DEVICE`.
This is not safe because the value of `CUDA_VISIBLE_DEVICE` may be illegal. What's more, IDs returned should obey the naming rule of platform GPU ID at [gpu_id.h](https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/core/common_runtime/gpu/gpu_id.h).
=> Find available GPUs in an elegant way.

deepmd/entrypoints/train.py
The default value of `type_map` is `None`, so when you don't set `type_map`, you'll get this error.
https://github.com/deepmodeling/deepmd-kit/blob/043ac869bfcdc7f3a20aa24d04bb7c7b88abcc0b/deepmd/entrypoints/train.py#L225
=> fix 'NoneType' has no len() in `auto_sel`

deepmd/entrypoints/train.py, deepmd/utils/neighbor_stat.py
Currently I can't see any warning during the training if `sel` is not enough, so it's a good idea to check it before training, and tell the user what to do.
Also fix #874.
=> raise warning before training if `sel` is not enough

deepmd/cluster/slurm.py, deepmd/env.py, requirements.txt, source/tests/test_cluster.py, source/tests/test_env.py
For better code coverage and feature compatibility, add unit tests for #892 and #905.
Need to mention, the expanding logic of environment variable `SLURM_JOB_NODELIST` is fixed with a professional package [python-hostlist](https://www.nsc.liu.se/~kent/python-hostlist/).
=> Fix the expanding logic of `SLURM_JOB_NODELIST` and add unit tests for parallel training.

doc/install.md
Starting from v2.0.0.b4, `libdeepmd` and `lammps-dp` will decouple.
The idea is that both C++ API and LAMMPS are usually stable, so we do not need to build LAMMPS in every release. Also, CPU version and GPU version share the same API and LAMMPS itself does not need CUDA, so we do not need to build LAMMPS twice.
=> update conda install documents

deepmd/__init__.py, deepmd/entrypoints/__init__.py
Symbol `DeepEval` is not imported while declared in field `__all__` of `deepmd/__init__.py`.
```
>>> from deepmd import *
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: module 'deepmd' has no attribute 'DeepEval'
```
Module `train` should not be declared as public in `deepmd/entrypoints/__init__.py`. Actually, `train_dp` is the correct one.
```
>>> from deepmd.entrypoints import *
>>> test
<function test at 0x7f7c2bc53d08>
>>> train
<module 'deepmd.entrypoints.train' from '/usr/local/lib/python3.7/dist-packages/deepmd_kit-2.0.0b3.dev37+g4d08f7e-py3.7-linux-x86_64.egg/deepmd/entrypoints/train.py'>
```
=> Fix member declartion of `deepmd` and `deepmd.entrypoints`.

deepmd/utils/data.py, source/tests/test_deepmd_data.py
=> set input DeepmdData.type_map to input type_map

doc/getting-started.md, source/lmp/compute_deeptensor_atom.cpp, source/lmp/compute_deeptensor_atom.h
One can use the following command to calculate deep tensor for each atom, taking dipole of water molecule for example
```
compute         dipole all deeptensor/atom dipole.pb
dump            1 all custom 100 water.dump id type x y z c_dipole[1] c_dipole[2] c_dipole[3] 
```
=> add lammps compute style for atomic deep tensor

source/train/argcheck.py
=> add aliases to Arguments

doc/getting-started.md, source/CMakeLists.txt, source/api_cc/CMakeLists.txt, source/install/build_lammps.sh, source/ipi/CMakeLists.txt, source/lib/CMakeLists.txt, source/lib/src/cuda/CMakeLists.txt, source/lib/src/rocm/CMakeLists.txt, source/lmp/env.sh.in, source/md/CMakeLists.txt, source/op/CMakeLists.txt
=> clean library and header dependencies

deepmd/entrypoints/compress.py, deepmd/entrypoints/main.py, deepmd/entrypoints/train.py, doc/getting-started.md
Add model compression support for models without training script. The main changes are:
- Allow users to provide the training script if there's no training script within the input frozen model.
- Note if there's a training script within the frozen model and the users provide one at the same time, the training script within the model will be used by default.
=> add model compression support for models without training script

deepmd/utils/compat.py, source/tests/compat_inputs/water_v2.json
=> convert `decay_rate` to `stop_lr` from old inputs

source/md/CMakeLists.txt, source/md/mdnn.cc
Although no one really enables and uses it, I still make it compatible with v2.0.
Also fix compilation errors.
Seems there is hard-code `DOUBLE` in the code, and I have no time to fix it, so I comment the build for float precision.
=> make native MD compatible with v2.0

source/CMakeLists.txt
cherry pick #536.
----
Clang doesn't support this flag, cause an error on osx:
> ld: unknown option: --no-as-needed
This commit should be cherry-picked to `r1.2` branch.
(cherry picked from commit ee8c419517fad9d7bcbf9fa13321a024889e5440)
=> cherry pick #536: only enable link what you use on GNU compilers

source/cmake/Findtensorflow.cmake
cherry pick #535
----
In conda-forge's recent released tensorflow, protobuf is external
from tensorflow and not inside the tensorflow directory.
(cherry picked from commit f66c78ec3ac21248d2a0dc0427f8d87d503e9636)
=> cherry pick #535: Do not find protobuf for python

source/tests/test_model_compression.py
In the benchmark on my local workstation, the model compression unit test within the ```$deepmd_source_dir/source/tests/test_model_compression.py``` consumes about 50% of the total unit test execution time. The execution time of ```test_model_compression.py``` can be largely reduced by this PR. 
The main benefits of this PR are:
- reduce the total ut time from 805.551 seconds to 422.773 seconds on my local 6-core Intel Xeon 8163 CPU environment.
- avoid GPU memory conflict during the os.system calls, check [this](https://stackoverflow.com/questions/39758094/clearing-tensorflow-gpu-memory-after-model-execution).
=> speedup model compression UTs

doc/development/type-embedding.md
=> update type embedding doc

deepmd/infer/deep_eval.py, deepmd/infer/deep_tensor.py, deepmd/loss/tensor.py, deepmd/train/trainer.py
See PEP-8 (https://www.python.org/dev/peps/pep-0008/#programming-recommendations)
=> remove bare `except` and limit the `try` clause

deepmd/train/trainer.py, deepmd/utils/argcheck.py, doc/train-input-auto.rst, doc/train/tensorboard.md
By default, TensorFlow events are recorded into files every step during DeePMD-Kit training if TensorBoard is enabled.
Capturing and writing tensor values are extremely time cost. From my experience, on a A100 host, the elapsed seconds every 2000 steps are trippled.
- Disabled.
```
DEEPMD INFO    batch    2000 training time 14.11 s, testing time 0.02 s
DEEPMD INFO    batch    4000 training time 14.37 s, testing time 0.02 s
DEEPMD INFO    batch    6000 training time 14.19 s, testing time 0.02 s
```
- Enabled.
```
DEEPMD INFO    batch    2000 training time 45.67 s, testing time 0.02 s
DEEPMD INFO    batch    4000 training time 45.22 s, testing time 0.02 s
DEEPMD INFO    batch    6000 training time 44.97 s, testing time 0.02 s
```
Thus, we introduce the argument `tensorboard_freq` to control …
=> Add the argument `tensorboard_freq` to control sampling ratio during training.

doc/conf.py
See [here](https://explore-deepmd.njzjz.win/en/latest/development/api.html) for preview.
`viewcode` add a link in each class to the source code.
`intersphinx` add a link in each type hint to the documentation of Python, NumPy, and TensorFlow.
PS: some type hints are wrong, hence the link is not generated. For example,
```py
eval(coords: numpy.array, cells: numpy.array, atom_types: List[int], atomic: bool = False, fparam: Optional[numpy.array] = None, aparam: Optional[numpy.array] = None, efield: Optional[numpy.array] = None) → Tuple[numpy.ndarray, ...]
```
`numpy.array` should be `numpy.ndarray`.
=> add sphinx plugins `viewcode` and `intersphinx`

.github/workflows/test_python.yml, doc/install/install-from-source.md, setup.py
As tensorflow API v1 has been stable, it's safe not to pin the tensorflow version.
=> unpin tensorflow version

deepmd/descriptor/se_a.py, deepmd/descriptor/se_a_ebd.py, deepmd/descriptor/se_a_ef.py, deepmd/descriptor/se_r.py, deepmd/utils/argcheck.py, deepmd/utils/tabulate.py, doc/model/train-se-e2-a.md, doc/train-input-auto.rst
Also regenerates `train-input-auto.rst`.
=> fix type hints and add doc for `exclude_types`

.github/workflows/test_python.yml, setup.py
=> fix a bug in `setup.py`

deepmd/cluster/local.py, deepmd/descriptor/hybrid.py, deepmd/descriptor/loc_frame.py, deepmd/descriptor/se_a.py, deepmd/descriptor/se_a_ef.py, deepmd/descriptor/se_r.py, deepmd/descriptor/se_t.py, deepmd/fit/dipole.py, deepmd/fit/ener.py, deepmd/fit/polar.py, deepmd/infer/data_modifier.py, deepmd/infer/deep_eval.py, deepmd/infer/deep_polar.py, deepmd/infer/deep_pot.py, deepmd/infer/deep_tensor.py, deepmd/infer/ewald_recp.py, deepmd/infer/model_devi.py, deepmd/utils/compat.py, deepmd/utils/type_embed.py
For example, `Return` should be `Returns`... See [style guide](https://numpydoc.readthedocs.io/en/latest/format.html).
=> fix incorrect type hints and docstrings

deepmd/infer/deep_pot.py, deepmd/infer/model_devi.py
Directly copied from `doc/inference/python.md`.
=> add examples to docstings

deepmd/descriptor/se_a.py, deepmd/entrypoints/compress.py, deepmd/train/trainer.py
Since in PR #1000 we have enable initialize the fitting-net variables with the frozen model saved variables. So there’s no need for the `dp transfer` interface to transfer the fitting-net variables to the compressed model.
=> rm 'dp transfer' from the model compression workflow

deepmd/descriptor/hybrid.py, deepmd/descriptor/loc_frame.py, deepmd/descriptor/se_a.py, deepmd/descriptor/se_a_ebd.py, deepmd/descriptor/se_a_ef.py, deepmd/descriptor/se_r.py, deepmd/descriptor/se_t.py, deepmd/fit/dipole.py, deepmd/fit/ener.py, deepmd/fit/polar.py, deepmd/fit/wfc.py, deepmd/infer/data_modifier.py, deepmd/infer/deep_tensor.py, deepmd/infer/model_devi.py, deepmd/model/ener.py, deepmd/model/tensor.py, deepmd/utils/data.py, deepmd/utils/data_system.py, deepmd/utils/learning_rate.py, deepmd/utils/neighbor_stat.py, deepmd/utils/pair_tab.py, deepmd/utils/tabulate.py, deepmd/utils/type_embed.py, doc/conf.py
Otherwise it won't be shown in the document.
Also contains other cleanups.
=> move parameters docstring from constructor method to class itself

deepmd/train/trainer.py
=> give a clear message if `model.get_ntypes()<data.get_ntypes()`

deepmd/entrypoints/train.py, source/tests/test_parallel_training.py
PR #914 breaks down the parallel training with multiple GPU cards because `NeightStat` creates a `tf.Session` covering all GPUs before the default `tf.ConfigProto` is reset to only use CPU. Then, the trainer will fail when it binds to only 1 GPU card with a different device ID.
Since there is no GPU machines in GitHub CI, regression test cannot be activated to ensure new PRs won't effect the feature of parallel training. We have to test multi-GPU training at local.
=> Instantiate RunOptions first when training.

deepmd/descriptor/loc_frame.py, deepmd/descriptor/se_a.py, deepmd/descriptor/se_a_ef.py, deepmd/descriptor/se_r.py, deepmd/descriptor/se_t.py, deepmd/infer/deep_eval.py, deepmd/utils/network.py
=> add docstring to `DescrptSeA`

doc/Doxyfile, source/api_cc/include/DeepPot.h, source/api_cc/include/common.h
This struct is necessary for C++ APIs. Without document, no one can understand this struct...
@Yi-FanLi I believe you need it.
Preview below:
=> add `InputNlist` into API doc

deepmd/fit/ener.py
=> add docstring for `EnerFitting`

deepmd/train/trainer.py
This commit saves checkpoint to `save_ckpt-step` (e.g. `model.ckpt-100`) instead of `save_ckpt` (e.g. `model.ckpt`), and keeps 5 recent checkpoint files (this is a default value of `tf.Saver`). Such thing is conducted by `tf.Saver`.  To not break any behaviors, a symlink will then be made from  `model.ckpt-100` to `model.ckpt`. (Usually such thing should be controlled by `checkpoint` file, but deepmd-kit doesn't read this file.)
This can fix #1023, as (1) we made symlink after a checkpoint has been already saved; (2) if something is still wrong, one can use a previous checkpoint instead.
=> save checkpoint files with step and keep recent files

deepmd/entrypoints/train.py
When parallel training, each worker should read different batch of frames. Normally, this is achieved by shuffling the whole dataset.
In case user explicitly set the random seed, we involve a **reproducible** value change (+`rank`) on the seed.
=> Avoid the same batch sequence among workers.

deepmd/train/trainer.py
=> fix hybrid descriptor training error

source/lmp/pair_deepmd.cpp
Fix #1068.
This bug is produced by #594.
=> copy `all_virial` for float precision

source/tests/test_model_compression.py, source/tests/test_transfer.py
Upgrade the os.system to subporcess.popen method. According to the [doc](https://docs.python.org/3/library/os.html#os.system) of os.system method:
> The subprocess module provides more powerful facilities for spawning new processes and retrieving their results; using that module is preferable to using this function. See the Replacing Older Functions with the subprocess Module section in the subprocess documentation for some helpful recipes.
In general, `subprocess.Popen()` is super-set of `os.system()`.
=> upgrade os.system to subporcess.popen method

deepmd/env.py
Currently, TF only initializes GPUs once, and never releases memory. As a result, we must set `allow_growth` in the first Session (or every session?), otherwise it doesn't work.
Please confirm the `allow_growth` config in `trainer.py` is expected, otherwise we should remove it instead.
https://github.com/deepmodeling/deepmd-kit/blob/1a25414dcd18b12316250baa330b690f3f5510fe/deepmd/train/trainer.py#L400
=> set `allow_growth` in `default_tf_session_config`

source/op/CMakeLists.txt
This fixes another python op library importing issue on macOS.
C++ library may have the similar issue, but I don't have machines to test.
=> use @loader_path on macos instead of $ORIGIN

.github/workflows/test_python.yml, deepmd/train/trainer.py, source/tests/test_parallel_training.py
With the latest TensorFlow package, enable parallel training unit test.
=> Enable parallel training UT in GitHub CI.

deepmd/env.py
Reverts deepmodeling/deepmd-kit#1036
It doesn't work on macos, so I'm going to revert.
=> Revert "get library extension suffix from built-in method"

deepmd/descriptor/descriptor.py, deepmd/descriptor/hybrid.py, deepmd/descriptor/se_a.py, deepmd/entrypoints/compress.py, deepmd/train/trainer.py, deepmd/utils/graph.py, deepmd/utils/tabulate.py
Also fixes some typos like `RunTimeError`->`RuntimeError`.
=> make compress work for hybrid descriptor composed of se_e2_a

deepmd/train/trainer.py, doc/train/parallel-training.md
The injection of gradient averaging OPs happens at [horovod.tensorflow.DistributedOptimizer.compute_gradients](https://github.com/horovod/horovod/blob/v0.19.5/horovod/tensorflow/__init__.py#L292).
Before this pull request, each worker trains its own data without synchronization except variables' broadcast at the beginning.
This BUG may explain no acceleration on loss convergence when parallel training.
=> Fix gradient not averaged when parallel training.

deepmd/descriptor/descriptor.py, deepmd/descriptor/se_a.py, deepmd/train/trainer.py, deepmd/utils/network.py
This PR enables `init-frz-model` support for the original model within the `dp train` interface. Now both original and compress pb file(with `se_a` type descriptor) can be used to initialize the dp train interface.
The results in the example water benchmark system show that the `step 0` of the `lcurve.out` output of the original model(`original.out`) and the compressed model(`compress.out`) under the `dp train --init-frz-model` interface is consistent:
result of original.out:
```
root se_e2_a $ head original.out 
0      2.58e+00    2.40e+00      2.81e-02    2.74e-02      8.17e-02    7.58e-02    1.0e-03
```
result of compress.out:
```
root se_e2_a $ head compress.out 
0      2.58e+00    2.40e+00      2.81e-02    2.74e-02      8.17e-02    7.58e-02    1.0e-03
```
=> Enable init-frz-model support for the original model

deepmd/entrypoints/train.py, deepmd/train/trainer.py
Note: this is a simple fix to resolve #1088, but I think we should design a clear architecture to call neighbor stat.
This should reduce the half of the time, but it may be still too long. We can consider some better algorithm to calculate neighbour stat (like KDtree?) for further optimization.
=> merge duplicated NeighborStat.get_stat

deepmd/entrypoints/compress.py, deepmd/entrypoints/train.py, deepmd/utils/graph.py, deepmd/utils/tabulate.py
The model compression with float precision has problems in reading model parameters and parameter checking. This PR should be able to fix these problems. Now single-precision model compression can be used normally.
=> Fix bug of single precision model compression

deepmd/entrypoints/transfer.py
=> Fix bug of single precision transfer

source/lmp/fix_dplr.cpp, source/lmp/pppm_dplr.cpp, source/lmp/pppm_dplr.h
When I debug #1109, I accidentally find the LAMMPS_VERSION_NUMBER condition is wrong, making builds fail. (but this is not related to #1109)
=> fix LAMMPS_VERSION_NUMBER condition

deepmd/infer/deep_polar.py
As detected by LGTM, here is an error:
Call to method DeepTensor.__init__ with too many arguments; should be no more than 4.
I agree with the automatic code analysis tool.
=> fix "Call to method DeepTensor.__init__ with too many arguments"

source/lmp/pair_deepmd.cpp
It seems that the default behavior of handling neigh_request is changed in Lammps `patch_14May2021`, which introduces a wrong stencil for the neighbor list. 
Before this fix the stencil is half
```
(1) pair deepmd, perpetual
attributes: , newton on
pair build: full/bin/atomonly
stencil: half/bin/3d/tri
bin: standard
```
After this fix the stencil is full,
```
(1) pair deepmd, perpetual
attributes: full, newton on
pair build: full/bin/atomonly
stencil: full/bin/3d
bin: standard
```
=> explicitly set neighbor request to full to fix bug #1109

deepmd/descriptor/se_a.py
This commit fixes a typo in Eq. of se_a.
=> fix a typo in Eq. of se_a

deepmd/utils/argcheck.py
=> fix a typo in #1118

deepmd/model/ener.py, deepmd/model/tensor.py
The `tf.import_graph_def` function prepends 'import' to tensor names, so that we could not load the tensors, such as `o_rmat`, from the frozen model generated by the `init-frz-model` command, which is also discussed by #1133 .
This PR should fix this problem by pass `""` to the `tf.import_graph_def`.
Note this PR was inspired by the related tensorflow [issue](https://github.com/tensorflow/tensorflow/issues/7212).
=> Fix init-frz-model command implementation

deepmd/descriptor/se.py, deepmd/descriptor/se_a.py, deepmd/descriptor/se_r.py, deepmd/descriptor/se_t.py, deepmd/utils/graph.py
I just copied several codes from se_a, which can also be applied to se_r and se_t.
=> support init-frz-model for se_r and se_t

deepmd/entrypoints/test.py, deepmd/infer/deep_pot.py, deepmd/utils/batch_size.py, deepmd/utils/errors.py, deepmd/utils/sess.py, doc/troubleshooting/model-compatability.md, source/tests/test_auto_batch_size.py
Resolves #1149.
We start nbatch * natoms from 1024 (or we can set a different number), and iteratively multiply it by 2 until catching the OOM error.
A small issue is that it's a bit slow to catch the TF OOM error. It's a problem of TF and I don't know how to resolve it. Luckily we only need to catch once.
=> automatic batch size for `dp test`

deepmd/entrypoints/freeze.py
Fix error when executing `dp test` on checkpoint saved by parallel training:
```
File "/usr/local/lib/python3.7/dist-packages/deepmd_kit-2.0.0b3.dev51+gae6a5ab-py3.7-linux-x86_64.egg/deepmd/entrypoints/freeze.py", line 155, in freeze
f"{input_checkpoint}.meta", clear_devices=clear_devices
File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saver.py", line 1461, in import_meta_graph
**kwargs)[0]
File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saver.py", line 1485, in _import_meta_graph_with_return_elements
**kwargs))
File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 804, in import_scoped_meta_graph_with_return_elements
return_elements=return_elements)
File …
```
=> Fix freezing error on checkpoint from parallel training.

deepmd/train/trainer.py, deepmd/utils/argcheck.py, doc/train/parallel-training.md
In some cases, convergence speed of scale learning rate linearly can be worse than not scaling.
Thus, an argument is exposed for users.
=> Allow to scale LR in different ways.

doc/conf.py
Sometimes we will forget re-generating train-input-auto.rst (e.g. in #1167), so we may want to regenerate it when running sphinx. This will not affect that file on the GitHub.
=> generate sphinx doc on the fly for training parameters

deepmd/descriptor/loc_frame.py, deepmd/entrypoints/train.py
Fix #1248 (only the first part).
=> fix Python bugs of loc_frame descriptor

source/op/descrpt.cc
this bug is introduced by the the changed convention of neighbor list storage in v2
=> fix bug of loc_frame descriptor when using lammps

deepmd/entrypoints/transfer.py
fix the np.frombuffer in dp transfer
=> Fix bug in transfer.py

source/lib/src/cuda/tabulate.cu
- Due to the sorted environment matrix, during the execution of model compression process, we can use this rule to reuse GPU kernel registers. Thus accelerate the tabulate_fusion_grad_se_a kernel by a factor of 1.1.
- Abstract part of the code.
A rocm implementation will be added later.
=> Accelerate model compression

deepmd/utils/graph.py
https://github.com/deepmodeling/deepmd-kit/runs/4160505428?check_suite_focus=true#step:8:10
/home/runner/work/deepmd-kit/deepmd-kit/deepmd/utils/graph.py:156: SyntaxWarning: "is not" with a literal. Did you mean "!="?
=> fix SyntaxWarning in graph.py

deepmd/utils/tabulate.py, doc/freeze/compress.md, doc/train/train-input.rst, source/op/unaggregated_grad.cc
Now the model with activation functions such as  'relu', 'relu6', 'softplus', 'sigmoid'  in descriptor can be compressed, and the output results have been well tested.
Modified related document with activation function.
=> Added all activation functions for model compression.

deepmd/entrypoints/compress.py
This ensures the old model can be compressed by the new program.
=> updata_deepmd_input when compress

deepmd/env.py, doc/train/parallel-training.md, doc/train/training-advanced.md
=> update guidelines for the number of threads

deepmd/descriptor/se_a.py, deepmd/descriptor/se_t.py, deepmd/utils/tabulate.py
=> Add embedding network dimension check of model compression

deepmd/fit/ener.py, deepmd/train/trainer.py
=> Fix model compression bug when fparam or aparam is not zero

deepmd/entrypoints/test.py
=> do not print virial error with nopbc data

deepmd/entrypoints/main.py, deepmd/entrypoints/train.py, doc/train/training-advanced.md, source/tests/test_train.py
Resolves #1088.
Also fixes a bug in `update_sel`.
=> provide an option to skip neighbor stat

.github/workflows/build_cc.yml, source/api_cc/tests/CMakeLists.txt, source/cmake/Findtensorflow.cmake
This PR fixes test errors with the new TensorFlow packages that I uploaded today.
=> Fix test errors with TensorFlow 2.7

deepmd/entrypoints/compress.py, deepmd/entrypoints/freeze.py, deepmd/utils/errors.py
As reported by #1318, the message was not covered here.
=> add an error message for copress/freeze

source/lmp/pair_deepmd.cpp
This commit redirects `print_summary` output to LAMMPS log function, so
it will be also shown in `log.lammps`.
=> redirect `print_summary` to LAMMPS log

source/api_cc/include/common.h, source/api_cc/src/DeepPot.cc, source/api_cc/src/DeepTensor.cc, source/api_cc/src/common.cc, source/lib/include/errors.h, source/lmp/pair_deepmd.cpp
This commits unifies all C++ errors (including TF) into `deepmd::deepmd_exception`
and passes the error message to LAMMPS.
=> unify C++ errors and pass message to LAMMPS

deepmd/utils/tabulate.py
This commit optimizes the execution time of `DPTabulate._build_lower` from 1s to 0.1s.
I confirm that the returned value (`self.data[net]`) does not change.
=> optimize `DPTabulate._build_lower` method

source/ipi/driver.cc
i-Pi assumes column-major storage to store cell and virial.
Fix #1351.
See i-Pi manual: https://ipi-code.org/i-pi/_static/manual.pdf (page 33 and page 78)
See also i-pi/i-pi#48 and i-pi/i-pi#196.
=> Fix cell and virial transpose bug in dp_ipi

source/lib/src/prod_force.cc, source/lib/src/prod_force_grad.cc, source/lib/src/prod_virial.cc, source/lib/src/prod_virial_grad.cc
About 1 ms can be saved in each training step.
=> enable OpenMP for `prod_force` and `prod_virial`

source/lmp/compute_deeptensor_atom.cpp
The similar change to pull #1128. This pull request fixes bug #1381.
=> explicitly set neighbor request to full in compute deeptensor/atom to fix bug #1381

source/api_cc/src/DeepPot.cc
Fix #1123.
Thanks for debugging from @Yi-FanLi !
=> initialize input virial vector to zero

source/lib/src/cuda/CMakeLists.txt
Fix nvcc warning when using cuda-11.x toolkit:
```nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).```
=> Fix nvcc warning when using cuda-11.x toolkit

.gitmodules
Since today, GitHub disabled unencrypted `git://`. See https://github.blog/2021-09-01-improving-git-protocol-security-github/. We use `https://` instead.
The PR should be cherry-picked to the previous version.
=> fix github git url

deepmd/entrypoints/freeze.py, deepmd/env.py, deepmd/train/trainer.py, deepmd/utils/argcheck.py
Enable by setting `enable_profiler` to true.
Fix #1407.
=> introduce TensorFlow Profiler

deepmd/loss/ener.py
During profiling, I found that the virial will be calculated in the test process even if I don't provide virial data.
This is meaningless and the viral has never been outputted.
This commit removes such behavior.
(cherry picked from commit 9a55069b40dc2892adeed8b153c67ba2d407a62b)
=> only test/eval fitting properties

deepmd/fit/ener.py, deepmd/model/ener.py, source/tests/test_fitting_ener_type.py
When profiling on multiple CPU threads, I notice that `inputs_zero` always runs after descriptor is computed. However, Some threads have nothing to do during `ProdEnvMatA`.
`inputs_zero` can be used to fill waiting time and runs with `ProdEnvMatA` at the same time...
(cherry picked from commit e704b4af1df7c23465615454bf7dfc0fc2f8d18f)
=> remove the dependency on `inputs` from `inputs_zero`

deepmd/utils/network.py
TF supports a [remapper optimizer](https://www.tensorflow.org/guide/graph_optimization) which remaps subgraphs onto more efficient implementations by replacing commonly occuring subgraphs with optimized fused monolithic kernels. However, its support is limited: (1) `MatMul` + `BiasAdd` (not `Add`) + Activation; (2) Float32 (but not float64); (3) Activation is Tanh; (4) MKL is built and used.
This commit replaces `Add` by `BiasAdd` in the NN. The speed of a single op can be improved by about 20% when TF is using MKL and precision is set to float32. One can find `_MklNativeFusedMatMul` op in the profiler.
Original graph. Ops include MklMatMul, AddV2, and Tanh.
New graph. `_MklNativeFusedMatMul` is used here.
See also:
- https://www.tensorflow.org/guide/graph_optimization
- …
=> enable TF remapper optimizer

deepmd/common.py
Method description disappears here.
=> fix `cast_precision` breaking docstring

doc/data/data-conv.md
=> fix a typo in document

deepmd/train/trainer.py
`std` and `avg` are stored as variables. `saver.restore` will restore and override it. So `data_stat` before `saver.restore` is useless.
Note that currently `init_from_frz_model` does not restore these variables.
I also add a message before `data_stat`. It sometimes takes long time.
=> skip `data_stat` in `init_from_model` and `restart` mode

.github/workflows/build_wheel.yml, .github/workflows/test_python.yml
Test whether deepmd-kit is compatible with the latest Python. Also add Python 3.10 to wheel building.
TF 2.8 was just released with Python 3.10 support.
Also note that Python 3.6 is reaching its end of life as of December 2021.
=> bump the Python version to 3.10

deepmd/descriptor/se_a.py, deepmd/train/trainer.py, deepmd/utils/network.py, source/tests/test_mixed_prec_training.py
#1469 should be fixed by this PR.
=> fix bug of mixed precision training

deepmd/fit/ener.py, source/tests/test_gen_stat_data.py
Atomic energies stats may be incorrect. Here, we use assigned atomic energies instead.
I am training a model against multiple systems, where some atoms should not contribute energies. Before this commit, the loss of my model could not decrease. After this commit, it decreased quickly.
=> assign energy shift stats if atomic energies are assigned

README.md, deepmd/entrypoints/__init__.py, deepmd/entrypoints/main.py, deepmd/entrypoints/neighbor_stat.py, doc/model/index.md, doc/model/index.rst, doc/model/sel.md, source/tests/test_neighbor_stat.py
In many cases, we need to confirm neighbor statistics before training.
This command provides such CLI option.
=> calculate neighbor statistics from CLI

deepmd/descriptor/loc_frame.py, deepmd/descriptor/se.py, deepmd/train/trainer.py
Before, only NN parameters were recovered.
=> recover input stats from frozen models

source/lib/src/cuda/prod_env_mat.cu, source/lib/src/cuda/prod_force.cu, source/lib/src/cuda/prod_force_grad.cu, source/lib/src/cuda/prod_virial.cu, source/lib/src/cuda/prod_virial_grad.cu, source/lib/src/cuda/tabulate.cu, source/lib/src/prod_force.cc, source/lib/src/rocm/prod_env_mat.hip.cu, source/lib/src/rocm/prod_force.hip.cu, source/lib/src/rocm/prod_force_grad.hip.cu, source/lib/src/rocm/prod_virial.hip.cu, source/lib/src/rocm/prod_virial_grad.hip.cu, source/lib/src/rocm/tabulate.hip.cu, source/lib/src/tabulate.cc
`memset`, `cudaMemset`, and `hipMemset` only accept integer as value. It's meaningless to pass a float, whether the compiler optimizes or not.
References:
https://www.cplusplus.com/reference/cstring/memset/
https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1gf7338650f7683c51ee26aadc6973c63a
https://rocmdocs.amd.com/en/latest/ROCm_API_References/HIP_API/Memory-Management.html#hipmemset
=> pass integer zero to memset

doc/inference/cxx.md
=> fix the example of inference with C++ interface

deepmd/env.py
The library type was changed from SHARED to MODULE in #1384.
Fixes errors in conda-forge/deepmd-kit-feedstock#31
=> fix macos library name

deepmd/descriptor/loc_frame.py, deepmd/descriptor/se.py, deepmd/descriptor/se_a.py, deepmd/train/trainer.py, doc/train/training-advanced.md, source/tests/test_adjust_sel.py
This PR adds the folling features:
- save checkpoints when `numb_steps == 0`
- fix a typo in #1482
- restore `sel` in the graph
- support recovering when sel != original_sel (only when `set_davg_zero` is `true`)
So, when `set_davg_zero` is `true`, one can use `dp train input.json -f graph.pb` to get a new model, where `input.json` decreased or increased `sel` and set `numb_steps` to zero, and then freeze the model. Two models should get the same result (descriptors, energies, forces) when sel is enough for both models. The UT confirms it.
As discussed, the theory behind it is also clear.
Here we may have the following motivations to use this feature:
(1) One can train a model that sel fits the training data to get the best performance during training, and then increase the sel, to prevent …
=> adjust sel of frozen models

source/lib/src/cuda/tabulate.cu
This PR should also fix #1444 .
=> fix model compression bug of nan output

deepmd/entrypoints/convert.py, deepmd/entrypoints/main.py, doc/troubleshooting/model-compatability.md
#1583
It looks like there's no breaking changes between v1.1 and v1.2. https://github.com/deepmodeling/deepmd-kit/compare/v1.1.5...v1.2.0
=> support `dp convert-from 1.1`

deepmd/fit/ener.py
Fix #684, where systems have different `atom_numb`. After this fix, RMSE of energy should be quickly decreased in the very beginning.
=> add atom energy bias to type embedding energy

source/lib/src/cuda/CMakeLists.txt
Close #1588.
`-arch=all` was added in CUDA 11.5. See reference.
Ref: https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-steering-gpu-code-generation-gpu-architecture
=> compile CUDA code for all archs

deepmd/entrypoints/convert.py, deepmd/entrypoints/main.py, deepmd/utils/convert.py, deepmd/utils/plugin.py, doc/troubleshooting/model-compatability.md
#1583
The commit also contains some common docstring fixes.
=> support dp convert-from 1.0

source/lmp/plugin/deepmdplugin.cpp
`compute` and `fix` style should use `creator.v2` - see https://docs.lammps.org/stable/Developer_plugins.html
(however, it looks like there is nothing wrong with v1)
=> fix lammps plugin creator pointer

source/lmp/compute_deeptensor_atom.cpp, source/lmp/fix_dplr.cpp, source/lmp/pair_deepmd.cpp
Fix #1599.
See: lammps/lammps#3148, lammps/lammps#3159.
=> follow API changes from latest LAMMPS

source/lmp/pair_deepmd.cpp
The compute style centroid/stress/atom does not work due to [lammps/lammps#2481](https://github.com/lammps/lammps/pull/2481) 
I change the constant of `centroidstressflag` according to the [definition](https://github.com/lammps/lammps/blob/e1835250c7351a2ba0145e448753216f8346168c/src/pair.h#L71-L74).
LAMMPS version : 24Mar2022
DeePMD-kit version: devel
This PR fixes the issue #1589
=> fix the atomic virial bug introduced by lammps PR #2481

source/lmp/plugin/deepmdplugin.cpp
<del>Do not merge - `LAMMPS_VERSION_NUMBER` needs to be updated after the next LAMMPS release.</del>
Fix #1567.
=> add kspace pppm/dplr to lmp plugin library

deepmd/descriptor/se_a.py, deepmd/fit/ener.py
Following #1592, I noticed that constants cannot be recovered when restart training.
(but it can be recovered automatically if it is a variable instead)
=> convert constants (which may change) to variables

deepmd/descriptor/descriptor.py, deepmd/descriptor/hybrid.py, deepmd/descriptor/loc_frame.py, deepmd/descriptor/se.py, deepmd/descriptor/se_a.py, deepmd/env.py, deepmd/fit/dipole.py, deepmd/fit/ener.py, deepmd/fit/fitting.py, deepmd/fit/polar.py, deepmd/model/ener.py, deepmd/model/model.py, deepmd/model/tensor.py, deepmd/train/trainer.py, deepmd/utils/graph.py, deepmd/utils/type_embed.py
Fix #1578. This commit refactors init_variable for both Descriptor and Fitting, so they can accept graph and graph_def instead of the filename. Opening the same file multiple times is bad behavior.
Moves some codes in Trainer to Model. Indeed Trainer should not operate Descriptor and Fitting directly.
Add init_variable method to type_embedding.
@denghuilu - I think `enable_compression` may have some similar issues.
=> refactor init_variable and support type embedding

deepmd/infer/data_modifier.py
Rewrite the dplr data modifier graph to use head gradient instead of looping over the Jacobian. This should largely reduce the graph size and can also improve the computation speed.
=> optimize the graph of dplr data modifier

deepmd/infer/model_devi.py
Otherwise, it's challenging to know which system the model deviation belongs to when multiple systems exist.
=> add system names to model devi header

source/op/optimizer/parallel.cc
1. "and" should be "or" and "or" should be "and"
2. forgot to introduce `TF_MAJOR_VERSION` and `TF_MINOR_VERSION` from `version.h`
So it couldn't be compiled...
=> fix TF version bug in #1429

deepmd/utils/argcheck.py
=> change default NN precision from `float64` to `default`

source/lib/tests/test_tabulate_se_r.cc
This variable declaration error would cause a UT compilation error in a CUDA environment.
=> fix variable declaration error

source/api_cc/src/DeepPot.cc
=> fix bug of aparam size, should be nlocal_real

deepmd/utils/tabulate.py
A tensor can be reused in a graph but a numpy array can't. This avoids saving duplicated constants in the case #1423.
=> convert tabulate data from np.ndarray to tf.Tensor

deepmd/entrypoints/compress.py
A graph has a size limitation of 2 GB, so if we do not clean the graph, the limitation will be indeed 1GB...
This PR will increase the limitation from 1 GB to 2 GB.
=> reset the graph before freezing the compressed model

deepmd/utils/tabulate.py
The current way `self.graph.get_operation_by_name('ProdEnvMatA')` to get `rcut` is incorrect for hybrid models. There may be several  ProdEnvMatA ops in a graph.
=> fix rcut in hybrid model compression

deepmd/calculator.py
=> add free_energy to ase calculator

doc/install/install-from-source.md, doc/install/install-gromacs.md, doc/install/install-lammps.md
=> doc: add information abotu supported versions of dependencies

deepmd/entrypoints/convert.py, deepmd/entrypoints/main.py, deepmd/utils/convert.py, doc/troubleshooting/model-compatability.md, source/op/prod_env_mat_multi_device.cc, source/op/prod_force_multi_device.cc, source/op/prod_virial_multi_device.cc
Resolves #1583.
See #40, 7c6c8193e164bf7f5209b45fe0948b2eb8e2cb55.
=> supports dp convert-from 0.12

source/op/tabulate_multi_device.cc
Fix #1681.
And the result of dp train shows the correctness of model compression training:
`dp train input.json -f frozen_model_compressed.pb`
```
(tensorflow_venv) root@iZ8vb672g6x8vab6ywhddcZ:~/deepmd-kit/examples/water/se_e2_r# cat lcurve.out 
0      9.07e+00    9.24e+00      2.93e-01    2.95e-01      2.86e-01    2.92e-01    5.0e-03
100      6.94e+00    6.68e+00      1.20e-01    1.19e-01      2.19e-01    2.11e-01    5.0e-03
200      7.01e+00    7.15e+00      4.73e-02    4.52e-02      2.22e-01    2.26e-01    5.0e-03
300      7.06e+00    6.93e+00      5.68e-02    5.37e-02      2.23e-01    2.19e-01    5.0e-03
400      6.80e+00    7.43e+00      2.92e-01    2.91e-01      2.14e-01    2.34e-01    5.0e-03
500      6.85e+00    6.88e+00      1.78e-01    1.76e-01      2.16e-01    2.17e-01 …
```
=> fix bug of model compression training with se_e2_r type descriptor

doc/data/index.md, doc/data/index.rst
=> Change Typo

deepmd/fit/ener.py
=> set default fparam and aparam stat and recover from graph

source/lib/src/fmt_nlist.cc
1. Compare square value instead of square root value. Square root is expensive.
2. Compare float instead of double, considering rcut is provided as float.
`ProdEnvMatA` (CPU) is observed to improve over 5%.
=> optimize format_nlist_i_cpu

deepmd/descriptor/se_a.py, deepmd/descriptor/se_r.py, deepmd/descriptor/se_t.py, deepmd/utils/tabulate.py
This PR uses different tabulate ranges for different NNs, in order to reduce the graph size.
Resolves #1388.
=> use net-wise tabulate range

deepmd/utils/neighbor_stat.py, deepmd/utils/parallel_op.py
benchmark on ANI-1x dataset: 19:25 -> 14:32
when setting `OMP_NUM_THREADS=1 TF_INTRA_OP_PARALLELISM_THREADS=1 TF_INTER_OP_PARALLELISM_THREADS=12`
(I think `OMP_NUM_THREADS=2 TF_INTRA_OP_PARALLELISM_THREADS=2 TF_INTER_OP_PARALLELISM_THREADS=6` may have better performance, but I have no interest to test it)
=> implement parallelism for neighbor stat

doc/conf.py, doc/development/type-embedding.md, doc/freeze/compress.md, doc/model/dplr.md, doc/model/train-energy.md, doc/model/train-hybrid.md, doc/third-party/lammps-command.md, doc/train/training-advanced.md
See https://github.blog/changelog/2022-05-19-render-mathematical-expressions-in-markdown/
=> render equations in markdown files

source/cmake/tf_cxx_abi.cpp
See https://github.com/tensorflow/tensorflow/commit/739002567ff81d731179a4b949def7e0f14737c8
=> fix tf_cxx_abi in TF 2.9

doc/install/easy-install.md
CUDA version has bumped to 11.6 to fix #1062.
=> update the latest state of easy installation

source/cmake/tf_cxx_abi.cpp
Follow up #1723. It's quite confusing that no `version_info.h` is generated
when building TF 2.9 C++ library only (but Python library has). So the
definition is copied here..
=> fix finding TF 2.9 ABI

source/lib/src/cuda/prod_env_mat.cu, source/lib/src/rocm/prod_env_mat.hip.cu
Per NVIDIA doc:
> 11.1.3. Reciprocal Square Root
> **The reciprocal square root should always be invoked explicitly as rsqrtf() for single precision and rsqrt() for double precision.** The compiler optimizes 1.0f/sqrtf(x) into rsqrtf() only when this does not violate IEEE-754 semantics.
See https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#reciprocal-square-root
=> replace GPU 1./sqrt with rsqrt

doc/conf.py, doc/train/train-input.rst, setup.py
See https://docs.deepmodeling.com/projects/dargs/en/stable/sphinx.html
=> docs: switch to dargs directive

doc/conf.py
by changing the main font to Symbola.
This font has been installed in the RTD image. But if one wants to build locally, first install the font:
```sh
apt-get install fonts-symbola
```
=> docs: fix emoji in PDF

setup.py
Before this commit, only global site-packages directory was searched.
=> search TF from user site-packages during installation

deepmd/descriptor/se_a.py
1e-2 is too small making the compression table have a large upper.
=> set a proper std when there is no atoms in the data

.github/workflows/build_wheel.yml
... it looks that both TF and `gprcio` (dependency of TF) has dropped the manylinux2010 wheels
=> bump manylinux image to 2014

deepmd/common.py, deepmd/descriptor/se_a.py, deepmd/descriptor/se_a_ef.py, deepmd/descriptor/se_r.py, deepmd/descriptor/se_t.py, deepmd/fit/dipole.py, deepmd/fit/ener.py, deepmd/fit/polar.py, deepmd/fit/wfc.py, deepmd/utils/argcheck.py, deepmd/utils/type_embed.py, doc/conf.py
=> deprecated docstring_parameter; use sphinx rst_epilog instead

.github/workflows/build_wheel.yml, deepmd/env.py
fix #1791.
Notes: 2_24 (glibc 2.24) is based on Debian 9
=> bump manylinux image to 2_24; add error message when TF_CXX11_ABI_FLAG is 1

source/lib/include/gpu_rocm.h
Wrongly written as "cuda assert" (#1801).
=> fix typo in hip assert error message

doc/install/easy-install.md
=> improve conda installation in the documentation

source/lmp/pair_deepmd.h.in
Throw an error if some one (like @Yi-FanLi) compiles LAMMPS with USER-DEEPMD using CMAKE and does not define `LAMMPS_VERSION_NUMBER`.
=> error if LAMMPS_VERSION_NUMBER is not defined

deepmd/entrypoints/train.py
#921 discussed that the tensors are compressed in the graph file. But it looks no... So at least we remove white space.
When any graph file is opened, it is clear that `train_attr/training_script` is stored as raw text.
=> remove white space from train_attr/training_script

deepmd/utils/convert.py
FastGFile throws a deprecated warning.
> WARNING:tensorflow:From /home/jz748/codes/deepmd-kit/deepmd/utils/convert.py:135: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.gfile.GFile.
See also
https://github.com/tensorflow/tensorflow/blob/d8ce9f9c301d021a69953134185ab728c1c248d3/tensorflow/python/platform/gfile.py#L128
=> replace FastGFile with GFile

deepmd/fit/dipole.py, deepmd/fit/ener.py, deepmd/fit/polar.py, deepmd/utils/graph.py
Note: commonly there is no suffix for a fitting.
=> support initilize parameters from a fitting with suffix

deepmd/env.py
> deepmd/env.py:8: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
See also https://docs.python.org/3/library/imp.html#imp.reload
=> fix DeprecationWarning of imp

source/cmake/Findtensorflow.cmake
=> find protobuf headers from extra paths

deepmd/common.py, source/op/_gelu.py, source/op/gelu_multi_device.cc, source/tests/test_activation_fn_gelu.py
This should avoid the conflicts related to the custom `Gelu` and Tensorflow's `Gelu`. Also Fix #1913.
=> Use GeluCustom as operator name

deepmd/utils/data_system.py, source/tests/test_deepmd_data_sys.py
=> handle float point error in sys_probs

deepmd/utils/convert.py
Fix #1934.
Add `descrpt_attr/rcut`, `descrpt_attr/ntypes`, `fitting_attr/dfparam`, `model_type`, `o_energy`, `o_force`, `o_virial`, `o_atom_energy`, `o_atom_virial`.
=> fix model conversion of 0.12

doc/install/install-from-source.md, doc/install/install-lammps.md, source/lmp/CMakeLists.txt, source/lmp/env.sh.in, source/lmp/env_py.sh.in, source/lmp/lmp_version.sh, source/lmp/plugin/CMakeLists.txt
Set `LAMMPS_VERSION_NUMBER` during `make yes-user-deepmd`. Fixes #1947. The corresponding CMake argument is deprecated.
=> perceive LAMMPS version for built-in mode

source/CMakeLists.txt
Fixes #1958. There was an ImportError from Python when TF and TF's dependency were not installed in the same directory, and one built with PEP 517.
The reason is that only TF's parent directory is added to `sys.path`.
=> use CPP_CXX_ABI for Python libraries

source/api_cc/tests/CMakeLists.txt, source/cmake/googletest.cmake.in, source/lib/tests/CMakeLists.txt
=> fix googletest download

deepmd/descriptor/loc_frame.py, deepmd/utils/argcheck.py
=> fix typo in the doc of `loc_frame`

.github/workflows/test_python.yml, setup.py, source/CMakeLists.txt, source/op/CMakeLists.txt
Coverage for C++ libraries will be counted when testing Python. It's expected to see the codecov coverage increases.
=> enable gcov for Python tests

setup.py, source/CMakeLists.txt, source/cmake/Findtensorflow.cmake
=> find protobuf headers in an automatic way

source/cmake/Findtensorflow.cmake
Follow-up of #1975 to fix #1957.
=> search TF deps from LD_LIBRARY_PATH; eliminate errors

source/cmake/Findtensorflow.cmake
=> replace `:` by `;` from `LD_LIBRARY_PATH` in cmake

source/lmp/pair_deepmd.cpp
Otherwise it returns zero atomic virials.
=> lmp: throw errors when 6-element atomic virial requested

deepmd/utils/convert.py
Strange, I added duplicated `convert_13_to_21` in #1597.
=> remove duplicated `convert_13_to_21`

.github/workflows/build_cc.yml, source/api_cc/src/AtomMap.cc
Clang is the default compiler for macos. For errors see also https://docwiki.embarcadero.com/RADStudio/Sydney/en/Explicit_instantiation_of_%27namespace::templated_class%27_must_occur_in_namespace_%27namespace%27_(C%2B%2B)
=> c++: add clang tests and fix clang errors

source/api_cc/CMakeLists.txt, source/cmake/Findtensorflow.cmake, source/ipi/CMakeLists.txt, source/lmp/plugin/CMakeLists.txt, source/op/CMakeLists.txt
This is also aimed at resolving macos clang errors:
1. link to protobuf if it's used and separated;
2. add link flags to lmp lib.
3. set rpath; remove gnu specific flags;
=> resolve macos clang errors

.github/workflows/build_wheel.yml, pyproject.toml
=> migrate cibuildwheel configs to pyproject.toml and add tests

source/cmake/Findtensorflow.cmake
Just add quotes for cmake empty variables. See https://stackoverflow.com/a/52481212/9567349
=> fix Findtensorflow when LD_LIBRARY_PATH is empty

.github/workflows/build_cc.yml, doc/install/install-from-source.md, setup.py, source/cmake/FindROCM.cmake, source/install/build_cc.sh, source/lib/src/rocm/CMakeLists.txt, source/lib/src/rocm/neighbor_list.hip.cu
Fixes #1400. Fixes #2009.
1. Uses cmake native module `CMakeDetermineHIPCompiler` to find the search path;
2. for ROCm>=3.5.1, `hip-hcc hiprtc` is replaced by `amd_comgr amdhip64`, per https://github.com/RadeonOpenCompute/ROCm/issues/1200. (I am not sure about the situation of `amd_comgr`?)
3. Removes `-hc` from the flag for ROCm>=3.5.1.
4. Bumps from C++11 to C++14 as C++ 14 required by `amd_comgr`.
5. Removes `--amdgpu-target=gfx906`. I don't see the reason why it is in the flag.
6. Fixes a typo in #1866.
=> Fix compatibility with ROCm>=3.5.1; fix typo in hip neighbor_list

deepmd/train/run_options.py
The previous code logs CUDA_VISIBLE_DEVICES in all situations. Here we only log CUDA_VISIBLE_DEVICES when CUDA is available and log HIP_VISIBLE_DEVICES when ROCm is available.
=> log HIP_VISIBLE_DEVICES for ROCm

source/install/build_tf.py
- fix error when LD_LIBRARY_PATH is not set
- add `/bin` to `PATH` considering `/bin` is not a symbolic link to `/usr/bin` on some systems
=> build_tf.py: mirror fixes

doc/third-party/lammps-command.md
=> docs: document lammps keyword `relative_v`, `aparam`, and `ttm`

source/install/build_tf.py
There is an unresolved issue when building with CUDA and NCCL (https://github.com/tensorflow/tensorflow/issues/57826). So this PR rolls back the TensorFlow version to 2.9.
=> build_tf.py: roll back TF version to 2.9

.github/workflows/package_c.yml, .gitignore, examples/infer_water/.gitignore, source/api_c/CMakeLists.txt, source/install/docker_package_c.sh, source/install/docker_test_package_c.sh, source/install/package_c.sh
Fix #2058.
This patch builds DeePMD-kit C library against TensorFlow 2.9.2 C++ library with CUDA support on CentOS 7 and then packages DeePMD-kit C library along with TensorFlow libraries. Then it is tested with GCC 4.9.0 and GLIBC 2.19. Finally, the package is uploaded and released. GitHub Actions and Docker drive all these things.
The minimum GLIBC requirement is 2.17, and the minimum GLIBCXX requirement is 3.4.19. It should work with any version of GCC.
Note that one still needs to install CUDA Toolkit 11 and cuDNN 8 manually for GPUs, otherwise TF falls back to CPUs.
=> build, package, and release C library

.github/workflows/build_wheel.yml, pyproject.toml, source/cmake/Findtensorflow.cmake
This patch includes the following improvements about building wheels:
- drop Python 3.6 support;
- split a single job into multiple jobs
- use auditwheel's new option `--exclude`, so we do not need to patch `policy.json` any more
- use `build` to build sdist and include submodules in the sdist
=> improve building wheel workflow

source/cmake/Findtensorflow.cmake
This patch skips detecting `_GLIBCXX_USE_CXX11_ABI` on windows and osx. These platforms do not have GNU C++ library.
=> skip checking `_GLIBCXX_USE_CXX11_ABI` on windows or osx 

source/api_cc/src/common.cc, source/lib/CMakeLists.txt, source/lib/src/cuda/CMakeLists.txt, source/lib/src/cuda/cudart/CMakeLists.txt, source/lib/src/cuda/cudart/cuda_runtime_10_0.inc, source/lib/src/cuda/cudart/cuda_runtime_10_1.inc, source/lib/src/cuda/cudart/cuda_runtime_10_2.inc, source/lib/src/cuda/cudart/cuda_runtime_11_0.inc, source/lib/src/cuda/cudart/cuda_runtime_11_2.inc, source/lib/src/cuda/cudart/cuda_runtime_9_0.inc, source/lib/src/cuda/cudart/cudart_stub.cc, source/lib/tests/CMakeLists.txt
This patch dynamically loads the CUDA runtime library (`libcudart.so`) instead of static linking. I referred to how TF does it and copied some open-source codes from TF. The advantage is that a CUDA package can be distributed that works on CPUs without any CUDA Toolkit libraries installed or packaged. (Currently, the packaged C library tarball contains `libcudart.so`)
Also fixes some minor issues.
=> dynamically load CUDA runtime library

backend/find_tensorflow.py, setup.py
So if one use `pip install deepmd-kit[gpu]`, the correct TF version will be installed.
=> store TF version in the wheel's extras_require

pyproject.toml
Builds linux-64 wheels against CUDA 11.8, but per [NVIDIA documentation](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#default-to-minor-version) it should work if the driver version >= 450.80.02. If GPU is not available, it should be able to fall back to CPUs.
The wheel size increases to about 3 MB, but is still not too big.
=> enable CUDA for linux-64 wheels

deepmd/.gitignore, deepmd/env.py, source/config/CMakeLists.txt
This fixes a warning during installation:
```
!!
############################
############################
Python recognizes 'deepmd.pkg_config' as an importable package,
but it is not listed in the `packages` configuration of setuptools.
'deepmd.pkg_config' has been automatically added to the distribution only
because it may contain data files, but this behavior is likely to change
in future versions of setuptools (and therefore is considered deprecated).
Please make sure that 'deepmd.pkg_config' is included as a package by using
the `packages` configuration field or the proper discovery methods
(for example by using `find_namespace_packages(...)`/`find_namespace:`
instead of `find_packages(...)`/`find:`).
You can read more about "package discovery" and "data files" on setuptools …
```
=> move run_config.ini into the root directory

source/op/optimizer/parallel.cc, source/op/optimizer/parallel.h
Fix the following warning
> warning: ‘static tsl::Status tsl::Status::OK()’ is deprecated: Use `OkStatus()` (preferred) or `Status()` (which is backward compatible with TF v2.9 and lower) instead. [-Wdeprecated-declarations]
=> fix TF compile warnings about Status::OK

deepmd/infer/deep_pot.py, deepmd/utils/convert.py
- Added model_attr/tmap to the convert_dp012_to_dp10 function of deepmd/utils/convert.py.
- Changed the reshape behavior of the feed_dict_test elements in the _prepare_feed_dict function of deepmd/infer/deep_pot.py.
After these modifications, the v0.12 model can be successfully converted to a model compatible with DeePMD-kit v2.1.5.
=> Fix version 0.12 model conversion

source/api_cc/src/DeepPot.cc, source/api_cc/tests/test_deeppot_a.cc
=> add shuffle_exclude_empty to DeepPot.compute(nlist, atomic)

source/tests/test_neighbor_stat.py
In #2117, we found that `test_neighbor_stat` is too slow, which takes over one minute. This PR uses a minor system and fewer frames to speed up `test_neighbor_stat`, so it only takes <0.2 s now.
=> speed up test_neighbor_stat

deepmd/cluster/local.py, source/tests/test_cluster.py
When I benchmark deepmd-kit on my machine, I found `get_gpus` takes about 2s and is quite slow. In #905, a subprocess was added to get available GPUs. As benchmarked in #2121, it's quite slow to import tensorflow.
I don't have better ideas not to call a subprocess, but we can skip this process when TensorFlow is not built against GPUs. The tests on the GitHub Actions will also benefit.
Attached is the selected profiling:
>  ncalls  tottime  percall  cumtime  percall filename:lineno(function)
> 1    0.000    0.000    2.141    2.141 local.py:15(get_gpus)
> 1    0.000    0.000    2.133    2.133 subprocess.py:1090(communicate)
=> skip `get_gpus` subprocess when TF is cpu only

pyproject.toml
Today manylinux_2_28 bumps the GCC version to 12 in https://github.com/pypa/manylinux/pull/1415. However, at present, CUDA only supports GCC 11.
TODO: when CUDA supports GCC 12, revert this change and bump the CUDA version.
=> pin manylinux image to a specific tag for GCC 11

deepmd/common.py, deepmd/descriptor/descriptor.py, deepmd/descriptor/se_a.py, deepmd/descriptor/se_a_ebd.py, deepmd/descriptor/se_a_ef.py, deepmd/descriptor/se_atten.py, deepmd/descriptor/se_r.py, deepmd/descriptor/se_t.py, deepmd/fit/dipole.py, deepmd/fit/ener.py, deepmd/fit/polar.py, deepmd/model/multi.py, deepmd/utils/parallel_op.py, deepmd/utils/path.py, deepmd/utils/random.py, deepmd/utils/type_embed.py
script:
```py
from glob import glob
import re
regex = re.compile(r"([^,\(\)= ]+):[ ]*((?!Optional)[^,\(\)= ]+)[ ]*=[ ]*None")
for ii in glob("deepmd/**/*.py", recursive=True):
with open(ii, 'r') as ff:
content = ff.read()        
has_optional = "Optional" in content
has_typing = "from typing" in content
content, nsub = regex.subn(r"\1: Optional[\2] = None", content)
if nsub > 0:
if not has_optional:
if has_typing:
content = content.replace("from typing import", "from typing import Optional,")
else:
content = "from typing import Optional\n" + content
with open(ii, 'w') as ff:
ff.write(content)
```
=> add Optional to type hints when default is None

deepmd/descriptor/descriptor.py, deepmd/descriptor/hybrid.py, deepmd/descriptor/se_a.py, deepmd/descriptor/se_r.py, deepmd/descriptor/se_t.py, deepmd/fit/ener.py, deepmd/train/trainer.py, deepmd/utils/tabulate.py
1. pass `graph` and `graph_def` instead of `model_name` so the model will be read from the disk only once;
2. remove `Fitting.enable_compression` as it is duplicated as `Fitting.init_variables`.
=> refactor enable_compression

deepmd/utils/batch_size.py, source/tests/test_auto_batch_size.py
On CPUs, the batch size will not be increased anymore.
This PR also introduces an environment variable `DP_INFER_BATCH_SIZE`. It can be used to override the initial batch size.
To clarify: higher batch size also has better performance on CPUs.
=> do not apply automatic batch size on CPUs

doc/install/install-from-source.md, setup.py, source/CMakeLists.txt
After I enable it, I can observe speedup in some cases. For `examples/water/se_e2_a`, compress training FP32 networks:
```sh
CUDA_VISIBLE_DEVICES= OMP_NUM_THREADS=8 TF_INTRA_OP_PARALLELISM_THREADS=8 TF_INTER_OP_PARALLELISM_THREADS=2 dp train input.json -f frozen_model_compressed.pb
```
Before enabling it,
```
DEEPMD INFO    batch     100 training time 1.67 s, testing time 0.03 s
DEEPMD INFO    batch     200 training time 1.25 s, testing time 0.03 s
DEEPMD INFO    batch     300 training time 1.23 s, testing time 0.03 s
DEEPMD INFO    batch     400 training time 1.24 s, testing time 0.03 s
DEEPMD INFO    batch     500 training time 1.24 s, testing time 0.03 s
DEEPMD INFO    batch     600 training time 1.23 s, testing time 0.03 s
DEEPMD INFO    batch     700 training time 1.24 s, testing …
```
=> add an option to enable native compilation optimization

deepmd/descriptor/descriptor.py, deepmd/descriptor/se_a.py, deepmd/descriptor/se_r.py, deepmd/fit/ener.py, source/tests/test_model_se_a.py, source/tests/test_type_one_side.py
This patch supports DPRc + type embedding, including
1. refactor `exclude_types` + `type_one_side`. Considering `exclude_types` is equivalent to $\forall i,j \in \text{exclude types}, \frac{\partial{E}}{\partial{r_{ij}}}=0$, a mask is created to apply to the environmental matrix, which is faster than the previous implementation in #1423.
2. implement `atom_ener` + type embedding.
=> support DPRc + type embedding

source/cmake/Findtensorflow.cmake, source/lmp/env_py.sh.in
Fix #2015. Fix #2039.
test log: https://gist.github.com/njzjz/7ebb2a9c6ac60f12475a084a0222dbc1
=> refactor `USE_TF_PYTHON_LIBS`

.github/workflows/build_wheel.yml, pyproject.toml, setup.py
Our wheels do not link against any Python ABIs. The libraries only link against TensorFlow ABIs. So it's safe to retag them to `py37-none-<platform>` but keep the platform tag. We only need to build the wheel once for a platform to reduce the CI time, and the wheel should work for all Python versions.
References: [PEP 425](https://peps.python.org/pep-0425/)
=> retag wheels to `py37-none-<platform>`

.github/workflows/build_wheel.yml, backend/find_tensorflow.py, doc/install/easy-install.md, pyproject.toml
With #2180, now it only has 4 tasks to build wheels. But this task is still so slow..
=> build wheels for Linux ARM64

source/install/build_tf.py
In some machines, this is required for Python.
=> build_tf.py: export `LD_LIBRARY_PATH` when executing `configure`

.github/workflows/build_cc.yml, source/lib/src/cuda/cudart/cuda_runtime_11_8.inc, source/lib/src/cuda/cudart/cuda_runtime_12_0.inc, source/lib/src/cuda/cudart/cudart_stub.cc
Fix #2176.
See also https://github.com/tensorflow/tensorflow/pull/58867.
Note that CUDA Toolkit 12.0 requires CUDA driver 525.60.13.
=> support CUDA 12.0

source/api_c/include/c_api.h, source/api_c/include/c_api_internal.h, source/api_c/include/deepmd.hpp, source/api_c/src/c_api.cc, source/api_c/tests/CMakeLists.txt, source/api_c/tests/test_dipolecharge.cc, source/api_cc/include/DataModifier.h, source/api_cc/include/DeepTensor.h, source/api_cc/src/DataModifier.cc, source/api_cc/src/DeepTensor.cc
Add `DipoleChargeModifier` to C API.
In addition, this patch also contains the following changes:
* fix bugs in `deepmd::DeepTensor::DeepTensor` and `deepmd::DipoleChargeModifier::DipoleChargeModifier`
* add comments to `deepmd::DipoleChargeModifier`
* support `gpu_rank` and other parameters for `deepmd::hpp::DeepPot` and `deepmd::hpp::DeepTensor`
=> c: add DipoleChargeModifier 

source/api_c/include/c_api.h, source/api_c/include/deepmd.hpp, source/api_c/src/c_api.cc, source/api_c/tests/test_deeppolar_hpp.cc, source/api_c/tests/test_deeppot_a_hpp.cc, source/api_c/tests/test_dipolecharge.cc, source/api_cc/include/common.h, source/api_cc/src/DataModifier.cc, source/api_cc/src/DeepPot.cc, source/api_cc/src/DeepTensor.cc, source/api_cc/src/common.cc, source/api_cc/tests/test_deeppolar.cc, source/api_cc/tests/test_deeppot_a.cc, source/api_cc/tests/test_dipolecharge.cc
* merge the implementation of `deepmd::DeepPot::print_summary` and `deepmd::DeepTensor::print_summary` to `deepmd::print_summary`
* add the implementation of `deepmd::DipoleChargeModifier::print_summary`
* add `DP_PrintSummary`, `deepmd::hpp::DeepPot::print_summary`, `deepmd::hpp::DeepTensor::print_summary`, and `deepmd::hpp::DipoleChargeModifier::print_summary`
* add tests for above
=> merge print_summary and add it to C API

deepmd/common.py, deepmd/utils/data.py, doc/data/system.md, source/tests/test_deepmd_data.py
Before, `sys_probs` only specifies the probability of each system. This patch allows `numb_copy.npy` (`int`) to specify each frame is copied by the "numb_copy" (int) times. The default is 1 for all frames, which keeps the same behavior as before.
=> support the custom training times for each frame

deepmd/env.py
When `atom_ener` is set, there will be variables named `layer_xx_suffix_1/MatMul` (the automatic name when  `layer_xx_suffix/MatMul` has been used).
=> fix `dp freeze` for multi-task when `atom_ener` is set

deepmd/env.py
This fixes an error:
```
OSError: /home/jz748/anaconda3/envs/tf/lib/python3.10/site-packages/nvidia/cublas/lib/libcublas.so.11: symbol cublasLtHSHMatmulAlgoInit, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference
```
=> load libcublasLt before libcublas

pyproject.toml
0.2.8 does not pass the tests. See https://github.com/njzjz/deepmd-kit/actions/runs/3890065119/jobs/6638845358. See also https://github.com/deepmodeling/dargs/pull/8.
=> bump minimal dargs version to 0.2.9

deepmd/loggers/loggers.py
=> prevent logging messages from other modules

deepmd/utils/argcheck.py, doc/data/system.md, doc/model/dplr.md, doc/third-party/lammps-command.md, doc/third-party/lammps.md, examples/water/lmp/in.lammps, examples/water/lmp/in.plugin.lammps, source/lmp/pair_deepmd.cpp, source/lmp/pair_deepmd.h.in, source/lmp/tests/data_type_map.lmp, source/lmp/tests/test_lammps.py
Fix #2237. Use the LAMMPS `pair_coeff` command to set `type_map`, like ReaxFF, EAM, etc.
Add and improve the documentation about `type_map`. From now on, setting `type_map` explicitly is encouraged (but not necessary).
=> assign type map for LAMMPS `pair_style deepmd`

setup.py
=> Added option to read HIPCC_FLAGS environment variable.

deepmd/model/ener.py, deepmd/model/model.py, deepmd/model/multi.py, deepmd/model/tensor.py, deepmd/train/trainer.py
Fix #1700. Fix #1936.
* Supports restarting from compressed checkpoints.
* When initializing from a frozen compressed model, only import a sub graph_def. This is critical, as #1700 will make it fail to restart.
* Merge methods in `EnerModel` and `TensorModel` to `Model`.
=> support restarting from compressed checkpoints

deepmd/env.py
As `logging.warn` is deprecated, use `logging.warning` instead. See https://docs.python.org/3/library/logging.html#logging.Logger.warning
=> fix deprecated `logging.warn`

source/api_cc/include/AtomMap.h, source/api_cc/include/DeepPot.h, source/api_cc/include/common.h, source/api_cc/src/AtomMap.cc, source/api_cc/src/DeepPot.cc, source/api_cc/src/common.cc, source/api_cc/tests/test_deeppot_a_nframes.cc, source/api_cc/tests/test_utils.h
Fix #2234.
When evaluating multiple frames, `ener` should be `std::vector<double>` instead of `double`. We assume `atype` is the same for all frames (follow the current docs).
=> support multiple frames with C++ DeepPot

.pre-commit-config.yaml, deepmd/entrypoints/compress.py, deepmd/entrypoints/test.py, deepmd/entrypoints/transfer.py, deepmd/fit/polar.py, deepmd/infer/deep_pot.py, deepmd/infer/deep_tensor.py, deepmd/nvnmd/entrypoints/mapt.py, deepmd/nvnmd/utils/config.py, deepmd/train/trainer.py, deepmd/utils/argcheck.py, deepmd/utils/data.py, deepmd/utils/graph.py, deepmd/utils/network.py, doc/conf.py, doc/sphinx_contrib_exhale_multiproject.py, pyproject.toml, source/tests/common.py, source/tests/test_data_large_batch.py, source/tests/test_deepmd_data_sys.py, source/tests/test_descrpt_se_atten.py, source/tests/test_embedding_net.py, source/tests/test_model_se_a.py, source/tests/test_model_se_atten.py, source/tests/test_nvnmd_op.py
Generally, with my configuration, it will automatically fix the following:
- `== None` -> `is None`
- unnecessary f-string
- `not xx in yy` -> `xx not in yy`
It will check but does not automatically fix the following:
- F821: undefined name (critical)
- F811: Redefinition of unused variable (maybe critical or typo)
- F722: bare except (critical)
I have ignored these rules: E501 (line too long), F401 (unused imports), F841 (unused variable), E741 (one-char variable), E402 (import should be the top)
=> Cleanup with flake8 E and F rule sets

source/api_c/include/c_api.h, source/api_c/include/deepmd.hpp, source/api_c/src/c_api.cc, source/api_c/tests/test_deeppot_a_nframes_hpp.cc, source/api_c/tests/test_utils.h, source/install/test_cc.sh
* Add DeepPot C API v2 to support multiple frames. Also, preserve the arguments for fparam and aparam for future use (planned in #2236). V1 is kept for API and ABI compatibility.
* Support multiple frames for DeepPot hpp API. The API compatibility is kept. Add tests for new situation.
=> support multiple frames DeepPot in C/hpp API

deepmd/train/trainer.py
#2253 supports restarting from the compressed model but breaks the original model. This PR fixes the error by detecting the model type first.
```
FAILED_PRECONDITION: Attempting to use uninitialized value
```
=> fix restarting from the original model

source/cmake/Findtensorflow.cmake
In TF 2.12, `.dylib` files was removed from macOS wheels with only `.2.dylib` left.
=> fix macOS library suffix for TF 2.12

deepmd/descriptor/se_a.py
When expanding `sel`, copy `std` from other neighbors instead of making the new values one.
It's useful to convert a `se_e2_a` model to a `se_atten` model with `atten_layer = 0`.
=> copy std when expanding `sel`

source/api_cc/tests/test_read_file_to_string.cc
=> fix `TestReadFileToString.readfiletostring`

source/api_c/include/deepmd.hpp
Fix `error: ‘strlen’ was not declared in this scope`
=> fix: add declaration of strlen to deepmd.hpp

deepmd/descriptor/se_atten.py, deepmd/fit/ener.py, source/lib/include/neighbor_list.h, source/lib/src/cuda/neighbor_list.cu, source/lib/src/cuda/prod_env_mat.cu, source/lib/src/fmt_nlist.cc, source/lib/src/prod_env_mat.cc, source/lib/src/rocm/neighbor_list.hip.cu, source/lib/src/rocm/prod_env_mat.hip.cu, source/op/prod_env_mat_multi_device.cc, source/tests/infer/virtual_type.pbtxt, source/tests/test_virtual_type.py
Support virtual atom types (`-1`) for `se_atten`. Thus, mixed numbers of atoms can be input for inference with mixed_type.
=> support mixed numbers of atoms with mixed_type

deepmd/env.py, source/api_cc/src/common.cc
The URL links to https://deepmd.rtfd.io/parallelism/.
=> add an URL to the warning of parallelism

source/cmake/Findtensorflow.cmake
Since the Red Hat Developer Toolset does not support the custom `_GLIBCXX_USE_CXX11_ABI` flag, this PR improves the flag and the message.
- if both `_GLIBCXX_USE_CXX11_ABI=0` and `_GLIBCXX_USE_CXX11_ABI=1` work, throw a warning and set `_GLIBCXX_USE_CXX11_ABI=1` (this flag should not take actual effect).
- if both flags do not work, throw an error message about the compiler issue.
=> improve cxx11 abi flags and messages for Red Hat Developer Toolset

.github/workflows/build_wheel.yml
The error was found when v2.2.0 was released. I have manually uploaded v2.2.0 to PyPI.
=> fix the version of pypa/gh-action-pypi-publish

deepmd/descriptor/se_atten.py, deepmd/utils/argcheck.py
Add `set_davg_zero` para in `se_atten` with default value True. This will fix incompatibility after fixing the incontinuity of se_atten. #2393 #2394
=> Fix incompatibility after fixing the incontinuity of se_atten

deepmd/utils/argcheck.py, deepmd/utils/data_system.py, examples/nopbc/mixed/input.json, source/tests/test_deepmd_data_sys.py
With the new option, a batch of data could come from all systems with different numbers of atoms and is generated and padded into a mixed system on the fly.
This PR is independent of #2366, which provides a manual way to use mixed systems. In theory #2366 should have better performance and this PR is more convenient.
=> support mixed systems training

deepmd/descriptor/se_a.py, deepmd/descriptor/se_a_mask.py, deepmd/fit/ener.py, deepmd/utils/network.py, doc/conf.py
It looks that the documentation is broken
=> fix pdf docs

deepmd/loggers/loggers.py
It's not a problem for production, but during tests there might be multiple handlers added.
=> clean old handlers before adding new one

source/cmake/cmake_lammps.cmake.in
It looks that by default, CMake will remove the execute permission.
=> keep the file permission when `make lammps`

source/lmp/Install.sh
Fix #2409.
By default, `source` searches the file from `PATH` (see the help from `source --help`). This might conflict with other packages. To prevent this behavior, one has to source the relative path instead.
=> `source` a relative path

deepmd/descriptor/se_atten.py, deepmd/utils/data_system.py
When mixed systems training (#2372) is enabled, the mixed_type attribute will affect the data stat.
=> set mixed_type to True for mixed systems

examples/water/lmp/in.lammps, examples/water/lmp/in.plugin.lammps
Closes #2425.
It takes work to explain everything in the comment. So, instead, I add a link to the documentation.
=> docs: add links to documentation in LAMMPS input

source/cmake/Findtensorflow.cmake
... as TF directories may be changed due to PEP-517.
=> disable Findtensorflow caches for skbuild

deepmd/entrypoints/main.py, deepmd/utils/argcheck.py, source/tests/test_examples.py
Migrate sub arguments of hybrid descriptor from a seperated normalize method to the main argument. (by using `repeat=True, fold_subdoc=True`)
Miror changes:
1. add tests for hybrid example;
2. merge gen_args;
3. add choice for `dp doc-train-input --out-type`
=> add sub fields of hybrid descriptor

source/api_c/include/c_api.h, source/api_c/include/deepmd.hpp, source/api_c/src/c_api.cc, source/api_c/tests/test_deeppot_model_devi_fparam_aparam.cc, source/api_cc/tests/test_deeppot_model_devi_fparam_aparam.cc
In addition, add tests for both the C++ API and the header-only C++ API.
=> C: support fparam/aparam for DP model devi

source/lmp/pair_deepmd.cpp
The current code never prints energy deviation, so it is a waste of time computing it.
=> lmp: remove codes to calculate energy deviation

.github/workflows/build_wheel.yml
This is a new feature of PyPI - see https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/
=> using trusted publishing in upload_pypi

deepmd/utils/pair_tab.py, source/op/pair_tab.cc
Fix https://github.com/deepmodeling/deepmd-kit/issues/2499.
=> fix dtype in PairTabOp

deepmd/infer/model_devi.py, source/tests/test_model_devi.py
Here total energy per atom ($E/N$) is used instead of atomic energy $E_i$, as the decomposition of energy is arbitrary and not unique.
=> print model deviation of total energy per atom in `dp model_devi`

deepmd/utils/sess.py
Sometimes TF will raise CancelledError instead of ResourceExhaustedError:
```
2023-05-02 14:39:26.504134: W tensorflow/tsl/framework/bfc_allocator.cc:497] *____*****____****************__________*****************************************___________________
2023-05-02 14:39:26.504163: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at matmul_op_impl.h:730 : RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[165000,100,100] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
2023-05-02 14:39:26.504208: I tensorflow/core/common_runtime/executor.cc:1197] [/job:localhost/replica:0/task:0/device:GPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): RESOURCE_EXHAUSTED: OOM when …
```
=> catch tf.errors.CancelledError for OOM

.github/workflows/package_c.yml, README.md, doc/install/index.md, doc/install/index.rst, doc/install/install-from-c-library.md, source/CMakeLists.txt, source/cmake/cmake_lammps.cmake.in, source/install/build_from_c.sh
Also fix `cmake_lammps.cmake.in`.
=> allow building lmp/gmx from pre-compiled C library

deepmd/train/trainer.py
Fix #2229.
Train models and prefetch data in parallel to decouple the time when data is produced from the time when data is consumed.
=> prefetch data during training

deepmd/utils/data_system.py
Here for mixed systems, the system batch size is just a placeholder.
=> remove warnings of batch size for mixed systems training

source/lmp/compute_deeptensor_atom.cpp, source/lmp/fix_dplr.cpp, source/lmp/pair_deepmd.cpp
=> lmp: forward errors to error->one instead of error->all

source/lib/src/cuda/tabulate.cu, source/lib/src/rocm/tabulate.hip.cu, source/lib/src/tabulate.cc, source/tests/test_model_compression_se_t.py
=> fix se_e3 tabulate op

MANIFEST.in
Our PyPi source distribution package is over 30MB which is too large! See https://pypi.org/project/deepmd-kit/2.2.2/#files
By default, when using `setuptools-scm`, all files will be added to the package. This PR excludes directories that are not used for building and installing, including:
- source/tests
- source/api_c/tests
- source/api_cc/tests
- source/lib/tests
- source/lmp/tests
- doc
- examples
- data
- .github
After removing these files from the source distribution, the package is only 708 KB.
=> remove unnecessary files from pypi source distribution 

doc/install/install-from-source.md, doc/install/install-tf.2.12.md, source/cmake/Findtensorflow.cmake, source/install/build_tf.py
In TF 2.11, TensorFlow adds a new directory, "tensorflow/tsl" where the headers should be copied.
1. add docs to install TF 2.12;
2. build_tf.py: bump to TF 2.12, and copy `tensorflow/tsl`;
3. output the detailed errors when checking ABIs. Sometimes the reason is missing header files instead of ABI.
=> improve docs and scripts to install libtensorflow_cc 2.12

source/lmp/fix_dplr.cpp, source/lmp/fix_dplr.h, source/lmp/tests/test_dplr.py
The corresponding functions (min_pre_force and min_post_force) in fix dplr are added so that the positions and forces of Wannier centroids can be correctly assigned during minimization.
=> Support minimization in dplr

doc/install/install-lammps.md
so old rpath will not be removed
=> docs: change `set-rpath` to `add-rpath`

deepmd/entrypoints/train.py
The current model compression feature will miss data modifier if it is used to compress a dplr model. This PR builds the modifier in the compressing process if there is a modifier in the uncompressed model.
=> fix the missing modifier issue of dp compress

deepmd/infer/data_modifier.py
=> import deepmd.op in infer.data_modifier

source/lib/tests/test_env_mat_a_mix.cc
`new[]` should be used with `delete[]`.
=> fix memory leaking in test_env_mat_a_mix.cc

source/lib/include/prod_force_grad.h, source/lib/src/cuda/prod_force_grad.cu, source/lib/src/prod_force_grad.cc, source/lib/src/rocm/prod_force_grad.hip.cu, source/lib/tests/test_prod_force_grad_a.cc, source/lib/tests/test_prod_force_grad_r.cc, source/op/prod_force_grad_multi_device.cc
=> prod_force_grad: support multiple frames in parallel

source/lib/include/prod_force.h, source/lib/src/cuda/prod_force.cu, source/lib/src/prod_force.cc, source/lib/src/rocm/prod_force.hip.cu, source/lib/tests/test_prod_force_a.cc, source/lib/tests/test_prod_force_r.cc, source/op/prod_force_multi_device.cc
The previous `prod_force` did not support multiple frames in parallel, which was slow when the batch size was large.
This PR adds support so that prod_force can be parallelized in the dimension of the samples.
When the batch size is about 70, the `prod_force` op is 10x faster than before on GPU cards.
=> prod_force: support multiple frames in parallel

deepmd/descriptor/hybrid.py, source/tests/test_descrpt_hybrid.py, source/tests/water_hybrid.json
Fix a bug introduced in #2549.
Add tests for it.
=> pass ntypes to sub descriptors in the hybrid descriptor

data/json/json2yaml.py, deepmd/descriptor/se_a.py, deepmd/fit/dipole.py, deepmd/fit/ener.py, deepmd/fit/polar.py, deepmd/infer/deep_dos.py, deepmd/infer/deep_pot.py, deepmd/train/trainer.py, deepmd/utils/multi_init.py, deepmd/utils/path.py, deepmd/utils/tabulate.py, deepmd/utils/type_embed.py, pyproject.toml, source/install/build_tf.py, source/tests/test_argument_parser.py, source/tests/test_gen_stat_data.py
Apply flake8-comprehensions to make codes simpler.
=> apply the C4 rule (flake8-comprehensions)

.github/workflows/test_python.yml
When using `gcc-8` on Ubuntu, `gcov-8` should be used instead of `gcov`. Thanks to https://stackoverflow.com/a/72435771/9567349
=> fix uploading C++ coverage for test_python workflow

deepmd/descriptor/se_atten.py
It seems that #1891 wrongly added a suffix to the variable names to make them like `filter_type_all_suffix/matrix_1_suffix`. However, it is expected to be `filter_type_all_suffix/matrix_1`, consistent in other descriptors and the following method.
https://github.com/deepmodeling/deepmd-kit/blob/5308c66d4f3069047af4a8aa07ece1df4b9628bc/deepmd/utils/graph.py#L166-L171
=> fix se_atten variable names when suffix is given

source/op/prod_env_mat_multi_device.cc
This PR moves filter_ftype out of the frame loop, so it can be parallelized in the frame index.
(it's the easiest part to refactor in the ProdEnvMatAMixOp; other codes are too complex to refactor)
=> ProdEnvMatAMixOp: move filter_ftype out of nsamples loop

deepmd/common.py, deepmd/infer/data_modifier.py, deepmd/infer/deep_dos.py, deepmd/infer/deep_pot.py, deepmd/infer/deep_tensor.py, deepmd/utils/data_system.py, source/api_cc/src/common.cc, source/op/descrpt.cc, source/op/descrpt_se_a_ef.cc, source/op/descrpt_se_a_ef_para.cc, source/op/descrpt_se_a_ef_vert.cc, source/op/neighbor_stat.cc, source/op/prod_env_mat_multi_device.cc, source/op/prod_env_mat_multi_device_nvnmd.cc, source/tests/test_deepmd_data_sys.py
This PR sets specific mesh shapes (7 for pbc and 1 for no pbc) for mixed type.
So when an operator does not throw mixed type, it will throw errors. It will be more accurate than the implementation in #2433 to check if a model supports DPRc.
`make_default_mesh` is updated and out-of-date behaviors are removed.
=> set specific mesh shapes for mixed type

deepmd/descriptor/se_atten.py, deepmd/utils/tabulate.py
=> fix se_atten compression when suffix is given

source/lib/src/cuda/coord.cu, source/lib/src/cuda/gelu.cu, source/lib/src/cuda/neighbor_list.cu, source/lib/src/cuda/prod_env_mat.cu, source/lib/src/cuda/prod_force.cu, source/lib/src/cuda/prod_force_grad.cu, source/lib/src/cuda/prod_virial.cu, source/lib/src/cuda/prod_virial_grad.cu, source/lib/src/cuda/region.cu, source/lib/src/cuda/tabulate.cu
Fix #2660.
TensorFlow made streams non-blocking in https://github.com/tensorflow/tensorflow/commit/9d1262082e761cd85d6726bcbdfdef331d6d72c6. Our own CUDA functions uses the default streams that is different from TensorFlow's, so we need to synchronize in the beginning of all functions.
In the future, it might be worth using the same stream as TensorFlow's to improve the performance.
=> synchronize in the beginning of all CUDA functions

examples/dos/train/input.json, examples/fparam/train/input.json, examples/fparam/train/input_aparam.json, examples/nopbc/mixed/input.json, examples/spin/se_e2_a/input.json, examples/water/dplr/train/dw.json, examples/water/dplr/train/ener.json, examples/water/hybrid/input.json, examples/water/se_atten/input.json, examples/water/se_atten_compressible/input.json, examples/water/se_atten_dpa1_compat/input.json, examples/water/se_e2_a/input.json, examples/water/se_e2_a_mixed_prec/input.json, examples/water/se_e2_a_tebd/input.json, examples/water/se_e2_r/input.json, examples/water/se_e3/input.json, examples/water/zbl/input.json, examples/water_multi_task/ener_dipole/input.json, examples/water_tensor/dipole/dipole_input.json, examples/water_tensor/polar/polar_input.json, examples/zinc_protein/zinc_se_a_mask.json
Set precision=float32 for NNs in examples, since we have found that float64 and float32 have the same accuracy in almost all the situation.
=> add precision arguments explicitly to examples

source/tests/test_model_compression_se_a.py
I found that #956 broke this unit test, making it only testing a standard model.
=> fix TestDeepPotAPBCExcludeTypes

deepmd/descriptor/se_atten.py, source/lib/include/tabulate.h, source/lib/src/cuda/tabulate.cu, source/lib/src/rocm/tabulate.hip.cu, source/lib/src/tabulate.cc, source/op/_tabulate_grad.py, source/op/tabulate_multi_device.cc, source/tests/test_model_compression_se_atten.py
This PR is similar to #2552. Usually, the input to tabulate OP is sorted, but if `exclude_types` is given, the input will not be sorted anymore.
=> fix se_atten tabulate when `exclude_types` is given

deepmd/fit/dos.py, deepmd/fit/ener.py, deepmd/fit/polar.py, deepmd/utils/argcheck.py, deepmd/utils/data_system.py, deepmd/utils/multi_init.py, source/tests/common.py
This is a breaking change. `rcond=1e-3` is found inaccurate. Using NumPy's default value is more accurate and not too slow.
=> breaking: change the default value of `rcond` from `1e-3` to `None`

deepmd/fit/ener.py, deepmd/model/ener.py, deepmd/model/model.py, deepmd/utils/argcheck.py
See #2662.
Forces and virials will be changed accordingly.
One can turn off the new behavior by setting `srtab_add_bias` to False.
=> breaking: add energy bias to tab potential

source/CMakeLists.txt
Although we have set it in `source/lib/src/cuda/CMakeLists.txt`, the main `CMakeLists.txt` needs it.
=> set cmake_minimum_required for CUDA/ROCm

deepmd/utils/argcheck.py
Add `fitting_args_plugin` and `loss_args_plugin` into `deepmd.utils.argcheck`. With these decorators, new parameters for fitting and loss can be defined in the external package.
=> add args decorator for fitting and loss

deepmd/train/run_options.py
=> make only the local GPU visible

deepmd/utils/compat.py
=> raise error if both v1 and v2 parameters are given

doc/third-party/lammps-command.md, source/lmp/pair_deepmd.cpp
Currently  `pair_coeff` support customizing mapping rule by the following way
```
pair_coeff * * H O H
```
But there are cases that need to mapping specific atom type to ghost type, or type that doesn't existed in deepmd. 
This PR addresses the issue by treating `NULL` as ghost type, so that users can specify atoms type to be ghost type by the following way
```
pair coeff * * H O NULL
```
=> support mapping to ghost type

deepmd/infer/model_devi.py, deepmd_cli/main.py, source/tests/test_model_devi.py
This PR adds a new argument `dp model-devi --real_error`. With that, the real error given in the DP-GEN paper is calculated.
One can use this feature for `dpgen simplify` if the labeled data exists.
=> feat: calculate the real error in dp model-devi

deepmd/entrypoints/test.py, deepmd_cli/main.py
Previously, we need to set `numb_test` to a quite large number to test all data. In this PR, passing 0 will lead to infinity.
Breaking change: the default value of `numb_test` is set to 0.
=> breaking: dp test all data

deepmd/env.py
Fix #2751.
If `__init__.py` does not exist, `module.__file__` is `None` (it is expected to give the path to `__init__.py`). In this case, `module.__path__[0]` will give the directory path.
=> Use `module.__path__[0]` instead of `module.__file__`

source/lmp/Install.sh
See https://github.com/search?q=repo%3Alammps%2Flammps+%22Must+install%22&type=code. Just use the same logic as LAMMPS.
=> lmp: throw error for traditional installation if dependent packages are not installed

README.md, deepmd/entrypoints/train.py, deepmd/infer/__init__.py, deepmd/infer/deep_dipole.py, deepmd/infer/deep_dos.py, deepmd/infer/deep_eval.py, deepmd/infer/deep_polar.py, deepmd/infer/deep_pot.py, deepmd/infer/deep_tensor.py, deepmd/infer/deep_wfc.py, deepmd/model/frozen.py, deepmd/model/linear.py, deepmd/model/model.py, deepmd/train/trainer.py, deepmd/utils/argcheck.py, doc/getting-started/quick_start.ipynb, doc/model/index.md, doc/model/index.rst, doc/model/linear.md, examples/water/linear/input.json, source/tests/test_examples.py, source/tests/test_linear_model.py
Fix #2724. Fix #2780.
Add the linear energy model, where the energy is the linear combination of several sub-energy models.
Add the frozen model to load the external DP model into the graph.
=> add linear models

source/lmp/pair_deepmd.cpp
Previously, the header line does not have columns for atomic model deviation.
=> lmp: add the header for atomic model deviation

source/op/prod_env_mat_multi_device.cc
=> check status of allocate_temp

deepmd/entrypoints/train.py, deepmd/model/frozen.py, deepmd/model/linear.py, deepmd/model/model.py, deepmd/utils/argcheck.py, deepmd_cli/main.py, doc/nvnmd/nvnmd.md, doc/train/training-advanced.md
=> docs: improve checkpoint description

source/lmp/compute_deeptensor_atom.cpp
The input of the model should be Angstron so that the unit style can only be metal or real.
=> lmp: add unit_style requirement for compute deeptensor/atom

deepmd/entrypoints/test.py, deepmd/utils/data.py, deepmd/utils/data_system.py, source/tests/test_dp_test.py
=> do not sort atoms in dp test

doc/model/dplr.md, source/api_c/include/c_api.h, source/api_c/include/deepmd.hpp, source/api_c/src/c_api.cc, source/api_cc/include/DeepTensor.h, source/api_cc/src/DeepTensor.cc, source/lmp/fix_dplr.cpp, source/lmp/fix_dplr.h, source/lmp/pair_deepmd.cpp, source/lmp/pair_deepmd.h, source/lmp/tests/test_dplr.py
When `pair_coeff` has set LAMMPS `type_map` (e.g. `pair_coeff * * O H`), `fix_dplr` uses the same LAMMPS `type_map` (i.e. `O H` in this case) to map from LAMMPS types to the DP model types, considering LAMMPS types should always be the same among different commands.
=> lmp: `fix_dplr` use the same `type_map` from `pair_deepmd`

deepmd/utils/data.py
```
DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
* make sure the original data is stored as integers.
* use the `converters=` keyword argument.  If you only use
NumPy 1.23 or later, `converters=float` will normally work.
* Use `np.loadtxt(...).astype(np.int64)` parsing the file as
floating point and then convert it.  (On all NumPy versions.)
(Deprecated NumPy 1.23)
return np.loadtxt(str(self.path), **kwargs)
```
=> fix np.loadtxt DeprecationWarning

deepmd/infer/model_devi.py, deepmd_cli/main.py, doc/test/model-deviation.md, doc/third-party/lammps-command.md, pyproject.toml, source/tests/test_model_devi.py
=> support atomic/relative model deviation in CLI

deepmd/loss/ener.py
This PR fixes an error for the example in the `examples` directory.
=> ignore drdq when generalized force loss is not set

deepmd/entrypoints/transfer.py
`tostring` has been deprecated. See https://numpy.org/devdocs/reference/generated/numpy.ndarray.tostring.html
=> `ndarray.tostring` -> `ndarray.tobytes`

deepmd/descriptor/se_a.py
`tf.accumulate_n` has been deprecated, and from the source code, I see that `tf.accumulate_n` is just a wrapper of `tf.add_n` since TF 2.1 (https://github.com/tensorflow/tensorflow/commit/292d3094313136b77bb5f444561bc3ffc529b246).
See:
https://www.tensorflow.org/api_docs/python/tf/math/accumulate_n
https://www.tensorflow.org/api_docs/python/tf/math/add_n
=> `tf.accumulate_n` -> `tf.add_n`

source/lmp/pair_deepmd.cpp
One should set the variable do_compute in pair_deepmd.cpp false by default, so that fparam can be used correctly. The current version will trigger the error https://github.com/deepmodeling/deepmd-kit/blob/7da9aaf075e8dea1eca9a08f99f3917235b55e3b/source/lmp/pair_deepmd.cpp#L1044-L1046 unexpectedly.
=> lmp: let fparam_do_compute not execute by default

.github/workflows/build_cc.yml, .github/workflows/build_wheel.yml, .github/workflows/test_cc.yml, source/install/build_cc.sh, source/install/build_from_c.sh, source/install/package_c.sh, source/install/test_cc.sh, source/install/test_cc_local.sh
This PR speeds up multiple GitHub Actions in the following way:
- only install `cuda-nvcc` and `cuda-cudart-dev` instead of the whole cudatoolkit
- skip installing clang as it's already shipped with the GitHub Action image
- enable cache for all `setup-python`
- use Ninja instead of Make as the CMake generator
=> speed up GitHub Actions

deepmd/descriptor/se_a_mask.py, deepmd/entrypoints/freeze.py, deepmd/model/pairwise_dprc.py, source/api_c/include/c_api.h, source/api_c/include/c_api_internal.h, source/api_c/include/deepmd.hpp, source/api_c/src/c_api.cc, source/api_c/tests/test_deeppot_a_fparam_aparam.cc, source/api_cc/include/DeepPot.h, source/api_cc/include/common.h, source/api_cc/src/DeepPot.cc, source/api_cc/src/common.cc, source/lib/src/pairwise.cc, source/op/pairwise.cc, source/tests/infer/pairwise_dprc.pbtxt, source/tests/test_pairwise_dprc.py
- make `aparam` accepts `nall` instead of `nloc`. A variable `fitting_attr/aparam_nall` (dtype=bool) controls the behavior.
- enable this behavior for se_a_mask, by the way
- fix the shape of atomic energy in the pairwise DPRc model, which is `nloc` instead of `nall`
- set the minimal `nloc` to 1, as when nloc=0, many OPs (such as prod_force) throw floating-point exception
- fix backward map when the shape of `nloc` is padded
=> make pairwise_dprc model work with MPI

pyproject.toml
Now, one can execute `tox` to test the Python package in an isolated environment. (The required packages can be automatically installed)
=> add tox configutation

source/tests/test_pairwise_dprc.py
it seems pkg_resources is deprecated
=> use parse_version from packaging.version instead of pkg_resources

deepmd/utils/argcheck.py, deepmd/utils/convert.py
Fix the following warnings: DeprecationWarning: invalid escape sequence
=> Fix invalid escape sequence

deepmd/model/pairwise_dprc.py, source/lib/include/gpu_rocm.h, source/op/pairwise.cc, source/op/prod_env_mat_multi_device.cc, source/tests/test_pairwise_dprc.py
This PR does a trick to speed up the pairwise DPRc model. Considering #2618 is not ready and is quite difficult to implement, in this PR, multiple frames are merged into one frame before feed to `prod_env_mat` OP, and the mesh is faked to make it perform the same behavior as the multiple frames.
A new `mesh` shape is proposed. The first element stores `nloc`, and the following 15 elements store nothing to distinguish it from other mesh. The `(16 : 16 + nloc)` elements store `ilist`, `(16 + nloc : 16 + nloc * 2)` store `numneigh`, and the rest elements (in the shape of `sum(numneigh)`) store neighbors. The `nei_mode` is 4 for this situation.
`prod_env_mat` OP is not a bottleneck anymore, as shown below.
=> make the pairwise DPRc model 2x faster

deepmd/__init__.py, deepmd_cli/main.py, pyproject.toml
See https://github.com/scikit-build/scikit-build-core/issues/507.
Now it's written to `{site_packages}/deepmd_cli/_version/__init__.py`. The previous implementation is too complex.
=> fix missing version file with setuptools-scm v8

deepmd/env.py
=> fix compatibility with NumPy 1.26

doc/development/coding-conventions.rst
Update this section to reflect the latest state.
=> docs: rewrite coding conventions

source/CMakeLists.txt, source/cmake/Findtensorflow.cmake
When setting the `INSTALL_TENSORFLOW` variable, previously CMake calls conda to install tensorflow. Now we use pip to install it.
=> cmake: use pip to install tensorflow

deepmd/fit/ener.py
Fix #2472. The previous implementation tried to allocate a (N, N) array and the RMSE result was actually MAE instead.
=> fix finetune RMSE and memory issue

.github/workflows/build_cc.yml, .github/workflows/build_wheel.yml, .gitmodules, doc/install/install-from-source.md, source/lib/src/gpu/CMakeLists.txt
Many people suggest not using `git submodule`. CMake FetchContent might be a better option (which we have used for googletest and lammps).
(only take effect for CUDA 10; CUDA 11 contains cub)
=> download cub using CMake FetchContent

source/cmake/Findtensorflow.cmake
When cross compiling, TensorFlow cannot be imported. TENSORFLOW_ROOT needs to be given manually.
This commit has been patched in https://github.com/conda-forge/deepmd-kit-feedstock/pull/57
=> cmake: skip executing python when cross compiling

pyproject.toml
It seems GitHub Actions started to report a "no space left on device" error.
This PR reverts #2359 and then only installs nvcc and cudart.
=> fix cuda installation for building wheels

.github/workflows/build_wheel.yml
#2324 sets `fetch-depth: 0` for wheels but not source distribution so that the wheel versions are correct, but the source distribution version is wrong.
=> fix source distribution version in build-wheel.yml

source/api_cc/src/DataModifier.cc, source/api_cc/src/DeepTensor.cc
This modification explicitly sets GPU binding in api_cc's DeepTensor and DataModifier. The aim is to support the multi-GPU parallelization of DeepTensor and DataModifier in C++ API.
=> set GPU binding in DeepTensor and DataModifier

deepmd/lmp.py
It's annoying that in the CUDA Python wheels, the library filename is `libcudart.so.11.0`, instead of `libcudart.so` or `libcudart.so.11` or `libcudart.11.0.xxx`. There are no symlinks in these CUDA Python wheels on PyPI. Thus, in this case, when DeePMD-kit tries to load `libcudart.so`, no file can be found.
Python interface doesn't have this issue, as it tries to use `glob` to find detailed library names. For the LAMMPS executable called from Python, `LD_LIBRARY_PATH` doesn't work with CUDA Python libraries (but works with an installation that contains symlinks). Thus, in this PR, `LD_PRELOAD` is set instead to preload CUDA symbols.
This fixes the docker images for the development branch.
=> fix LAMMPS wheel with CUDA wheels

.github/workflows/test_cuda.yml
See https://github.com/deepmodeling/deepmd-kit/pull/2884#issuecomment-1744216845
=> run Test CUDA in container

pyproject.toml
Due to a bug in cibuildwheel (https://github.com/pypa/cibuildwheel/issues/1616), this typo didn't affect anything in previous cibuildwheel versions, but the bug got fixed in the latest version...
=> fix a typo in tool.cibuildwheel.linux.environment

source/3rdparty/implib/arch/aarch64/table.S.tpl, source/3rdparty/implib/arch/arm/table.S.tpl, source/3rdparty/implib/arch/i386/table.S.tpl, source/3rdparty/implib/arch/mips/table.S.tpl, source/3rdparty/implib/arch/mips64/table.S.tpl, source/3rdparty/implib/arch/x86_64/table.S.tpl
See https://github.com/yugr/Implib.so/issues/34
=> update vendored Implib.so to fix ld warnings

deepmd/descriptor/descriptor.py, deepmd/descriptor/hybrid.py, deepmd/descriptor/loc_frame.py, deepmd/descriptor/se.py, deepmd/descriptor/se_a_ef.py, deepmd/descriptor/se_atten.py, deepmd/entrypoints/train.py, deepmd/model/frozen.py, deepmd/model/linear.py, deepmd/model/model.py, deepmd/model/multi.py, deepmd/model/pairwise_dprc.py, source/tests/test_train.py
The current `update_sel` has too many complex conditionals. This PR rewrites them in the `Model` and `Descriptor` classes, which makes it easier to maintain the existing classes and implement new classes.
=> refactor update_sel

deepmd/descriptor/se_atten.py, deepmd/model/model.py, deepmd/model/multi.py
=> fix TypeError when type_map is not given

deepmd/model/pairwise_dprc.py
The "frozen" model has been previously supported in #2781, so this PR allows it to be used in the pairwise DPRc model.
Allow QM model type maps to be just the first $N$ type maps of the whole models, as the QM model doesn't need MM types.
One can load two separated models into one model or load the existing QM model and train the rest of the model.
=> support combining frozen models into a pairwise DPRc model

backend/dynamic_metadata.py, deepmd/entrypoints/__init__.py, deepmd/entrypoints/gui.py, deepmd/entrypoints/main.py, deepmd_cli/main.py, doc/cli.rst, doc/train/train-input.rst, pyproject.toml, source/tests/test_gui.py
See https://github.com/deepmodeling/dpgui/issues/270 for details.
=> Add `dpgui` entry point and `dp gui` CLI

source/api_cc/src/DataModifier.cc, source/api_cc/src/DeepTensor.cc, source/api_cc/src/common.cc, source/lib/include/ComputeDescriptor.h, source/lmp/fix_dplr.cpp
See https://en.cppreference.com/w/cpp/error/assert, which shows several ways to avoid unused warnings.
=> fix "expression result unused" warnings

doc/troubleshooting/howtoset_num_nodes.md
The output of `mpirun -h` does not contain the MPI version.
=> docs: `mpirun --version` to get MPI version

deepmd/env.py, deepmd/lmp.py
When using `pip install -e`, the library and the source code are not in the same directory, so `__file__` should not be used.
=> fix py lmp plugin path for editable installation

source/lib/src/gpu/tabulate.cu, source/lib/src/tabulate.cc
In this case, when `em_x` is equal to the last neighbor, `em` may not.
This patch checks whether em[1] ~ [3] is zero. In the current se_a implementation, they are zero only when they are padded zero.
=> fix se_a compression for just enough sel and symmetrical coordinates

deepmd/infer/deep_pot.py, deepmd/utils/batch_size.py, source/api_c/include/deepmd.hpp, source/api_c/tests/test_deeppot_a_hpp.cc, source/api_cc/src/DeepPot.cc, source/api_cc/src/common.cc, source/op/map_aparam.cc, source/op/pairwise.cc, source/op/prod_force.cc, source/op/prod_force_grad.cc, source/op/prod_force_grad_multi_device.cc, source/op/prod_force_multi_device.cc, source/op/prod_force_se_a_grad.cc, source/op/prod_force_se_a_mask.cc, source/op/prod_force_se_a_mask_grad.cc, source/op/prod_force_se_r_grad.cc, source/op/prod_virial.cc, source/op/prod_virial_grad.cc, source/op/prod_virial_grad_multi_device.cc, source/op/prod_virial_multi_device.cc, source/op/prod_virial_se_a_grad.cc, source/op/prod_virial_se_r_grad.cc, source/op/soft_min_force.cc, source/op/soft_min_force_grad.cc, source/op/soft_min_virial.cc, source/op/soft_min_virial_grad.cc, source/tests/test_deeppot_a.py, source/tests/test_deeppot_r.py
Fix #2668. Fix #2921. Fix #2873. Fix #2521.
=> fix floating point exception when nloc or nall is zero

.github/workflows/build_wheel.yml, doc/install/easy-install-dev.md
So one can install the developed version with
```sh
pip install -U --pre deepmd-kit[gpu,cu11,lmp] --extra-index-url https://deepmodeling.github.io/deepmd-kit/simple
```
=> deploy developed Python packages to GitHub Pages

deepmd/entrypoints/freeze.py
=> only freeze in rank 0

deepmd/descriptor/se_a.py, deepmd/descriptor/se_atten.py, deepmd/descriptor/se_r.py, deepmd/descriptor/se_t.py, deepmd/utils/tabulate.py, source/op/unaggregated_grad.cc, source/tests/model_compression/input.json
Fix #1370.
Support compressing any neuron structure; fix compression error when `neuron[0]` is 1 (although no one will set `neuron[0]` to 1).
=> support compressing any neuron structure

deepmd/entrypoints/convert.py, deepmd_cli/main.py, source/tests/test_deeppot_a.py
Add convert_pb_to_pbtxt in dp convert-from CLI
=> Support conversion to pbtxt in command line interface

.github/workflows/test_cc.yml, .github/workflows/test_cuda.yml, examples/infer_water/convert_model.c, source/install/docker_test_package_c.sh
=> fix ase tarball url and testing C library

backend/find_tensorflow.py
By default, SpecifierSet doesn't allow prereleases, which is not our expected behavior.
=> fix SpecifierSet behavior with prereleases

.pre-commit-config.yaml, deepmd/entrypoints/train.py, deepmd/fit/polar.py, deepmd/utils/argcheck.py, deepmd/utils/finetune.py, deepmd/utils/tabulate.py, doc/getting-started/quick_start.ipynb
See https://astral.sh/blog/the-ruff-formatter
=> move to ruff formatter

.github/release.yml
See https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes.
We shall add proper labels when submitting and merging PRs, so release notes can be more automatic.
=> docs: configuring automatically generated release notes

source/lib/src/gpu/CMakeLists.txt
Although we set it to `all` by default, one may manually set it via [CMAKE_CUDA_ARCHITECTURES](https://cmake.org/cmake/help/latest/variable/CMAKE_CUDA_ARCHITECTURES.html)  or [CUDAARCHS](https://cmake.org/cmake/help/latest/envvar/CUDAARCHS.html#envvar:CUDAARCHS).
=> respect user defined CUDAARCHS

source/lmp/pair_deepmd.cpp
The current implementation used a complex method to ensure `ixnode` (int) within `[0, nxnodes-1]`, but why not use mod ("%") to get the same behavior?
=> lmp: refactor ixnode

pyproject.toml
Bump scikit-build-core from `>=0.5,<0.6` to `>=0.5,<0.7,!=0.6.0`. (by default it will install 0.6.1)
=> bump scikit-build-core to 0.6

.github/workflows/build_cc.yml, .github/workflows/test_cuda.yml, backend/find_tensorflow.py, doc/install/easy-install-dev.md, doc/install/easy-install.md, doc/install/install-from-c-library.md, pyproject.toml, source/install/docker/Dockerfile, source/install/docker_package_c.sh
TensorFlow 2.15 bumps the CUDA version to 12.2. See https://github.com/tensorflow/tensorflow/commit/3de44168950a5972ba4cfa7e3c6cbf4cffa67fe6.
=> bump CUDA version to 12.2 for pre-built packages

deepmd/model/dos.py, deepmd/model/ener.py, deepmd/model/model.py, deepmd/model/multi.py, deepmd/model/pairwise_dprc.py, deepmd/model/tensor.py, deepmd/utils/type_embed.py, source/tests/test_compressed_training.py
=> fix restarting from compressed training with type embedding

doc/install/easy-install.md
Recently I contributed Horovod to conda-forge at https://github.com/conda-forge/staged-recipes/pull/24472. I have tested it with DeePMD-kit. Now the Conda-forge channel has all the features in our deepmodeling channel and even more available platforms.
I wonder if we should recommend Conda-forge in favor of our DeepModeling channel and use it for the offline installer. In 2019, Conda-forge lacked support for TensorFlow, so we hosted and built our own channel against the Anaconda channel. But now Conda-forge has become a mature channel and has better support for TensorFlow than the Anaconda channel.
=> docs: document horovod on Conda-Forge

deepmd/utils/data_system.py
When the probability of a system is smaller than 1e-3, it is shown as `0.000`, which is useless. This commit changes it to the scientific notation, displaying it like `1.547e-06`.
=> print system prob using scientific natation

doc/third-party/lammps-command.md, source/lmp/pair_deepmd.cpp
=> breaking(lmp): do not apply scale factor to model deviation

.github/workflows/build_wheel.yml
See https://github.com/deepmodeling/deepmd-kit/pull/3029
See also https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#responding-to-events
=> skip pushing when an action is triggered by dependeabot

source/api_cc/src/common.cc, source/lmp/pair_deepmd.cpp, source/lmp/pair_deepmd.h
This PR fixes #3015, which reported an invalid memory read and write when running `fix deposition` in Lammps to add atoms into the system. The issue could not be reproduced when `atomic` was removed from the `pair_style deepmd` line.
As suggested by @njzjz , the possible cause of the bug was the allocation of `stdfsend`, `stdfrecv`, etc., which only happened when `out_each == 1`, set by `atomic` in the `pair_style deepmd` command. Moreover, their size was only determined in the initialization step, based on the initial `natoms`. The valgrind log also supported this hypothesis, as it showed `MPI_Gather` and `MPI_Gatherv` errors in the traceback.
Therefore, we decided to destroy and recreate the memory when `atom->natoms` became larger than `stdfsend`. This should prevent the invalid memory …
=> fix: invalid read and write when natom grows

deepmd/calculator.py, deepmd/infer/__init__.py, deepmd/infer/deep_dipole.py, deepmd/infer/deep_eval.py, deepmd/infer/deep_polar.py, deepmd/infer/deep_pot.py, deepmd/infer/deep_tensor.py, source/tests/test_deepdipole.py, source/tests/test_deeppolar.py, source/tests/test_deeppot_a.py
=> build neighbor list with external Python program

deepmd/utils/batch_size.py
When fine-tuning with Horovod, the same error as https://github.com/deepmodeling/deepmd-kit/issues/2712 is thrown at the place I modified in this PR.
It seems `tf.test.is_gpu_available` will try to use all GPUs, but `tf.config.get_visible_devices` won't.
=> fix GPU mapping error for Horovod + finetune

deepmd/loss/dos.py, deepmd/loss/ener.py, deepmd/loss/loss.py, deepmd/loss/tensor.py, deepmd/train/trainer.py
Currently, when loss is defined and the labeled data is not found, `lcurve.out` shows wrong RMSE (assuming data is all zero). In this case, printing NaN is better.
=> print NaN loss when labeled data is not found

.github/labeler.yml
See https://github.com/actions/labeler/tree/main?tab=readme-ov-file#breaking-changes-in-v5; The action version was bumped by #3050
=> fix labeler.yml with actions/labeler v5

.github/workflows/test_cc.yml, source/api_cc/src/DataModifier.cc, source/api_cc/src/DeepPot.cc, source/api_cc/src/DeepTensor.cc, source/api_cc/tests/test_deepmd_exception.cc
When a constructor throws an exception, it will not call the destructor as the constructor is not finished. The memory leak happens here and is detected by LeakSanitizer (thanks, @Cloudac7, for reminding me to use it). We must catch the exception, delete the memory, and re-throw the exception.
=> Fix possible memory leak in constructors

.github/workflows/test_cc.yml, source/api_c/include/c_api.h, source/api_c/include/deepmd.hpp, source/api_c/src/c_api.cc, source/api_c/tests/test_deeppot_a.cc
Make sure no leaks reported from `string_to_char` by LeakSanitizer.
Most memory leaks happen only once, but `DP_CHECK_OK` causes 1 byte leaking every step, meaning 10 MB leaks for 10 million steps.
=> fix memory leaks related to `char*`

deepmd_utils/model_format.py, source/tests/test_model_format_utils.py
=> add utils for DP native model format

source/lmp/builtin.cmake
=> lmp: Register styles when using CMake

source/lib/include/region.h, source/lib/src/region.cc, source/lib/tests/test_coord.cc, source/lib/tests/test_simulation_region.cc, source/op/prod_env_mat_multi_device.cc, source/tests/test_auto_batch_size.py
When debuging #3103, I notice a segfault in `~Region`, preventing the actual error message thrown. `_norm_copy_coord_gpu` replaces `boxt` and `rec_boxt` of `Region` with GPU pointers, runs `deepmd::copy_coord_gpu`, and finnally recover the original pointer that can be deleted. However, `deepmd::copy_coord_gpu` might throw CUDA errors for any reason, and the pointers are not recovered. `~Region` tries to delete a pointer that it doesn't own, causing the segfault. The CUDA error message is not visible due to segfault. The segfault in #2895 may be also caused by it.
This PR adds a new constructor to `Region` to accept the external pointers. `~Region` will delete `boxt` and`rec_boxt` only when the pointer is not external.
We still need to figure out the reason for the error of …
=> fix segfault in ~Region

deepmd_utils/model_format.py, source/tests/test_model_format_utils.py
- fix bugs.
- add UT for the `NativeLayer`
=> NativeLayer: support None bias. 

deepmd_utils/model_format.py, source/tests/test_model_format_utils.py
add UT testing all input and output shapes
=> fix native layer concat bug. 

deepmd_utils/model_format/__init__.py, deepmd_utils/model_format/common.py, deepmd_utils/model_format/env_mat.py, deepmd_utils/model_format/network.py, source/tests/test_model_format_utils.py
- change of numerical precision is supported
- environment matrix is supported.
=> support numerical precision and env_mat

README.md, deepmd/descriptor/se_a.py, deepmd/entrypoints/gui.py, deepmd/env.py
1. Fix wrong custom operator installation filename
2. Fix missing file `deepmd/entrypoints/gui.py`
3. Annotated `@cast_precision` and keep brackets `[]` util problems fixed @SigureMo
@njzjz Besides, can you please help to rename `paddle` branch to `paddle_1` or other backup name, and then change `paddle2` to `paddle` branch? Because user may get confused aboout the difference between `paddle2 and `paddle`. Thanks a lot.
=> [Paddle Backend][Fix] Fix wrong custom operator installation filename

source/lmp/pair_deepmd.cpp
Fix #3126.
See https://docs.lammps.org/Developer_updating.html#use-ev-init-to-initialize-variables-derived-from-eflag-and-vflag
=> lmp: fix evflag initialization

source/api_cc/include/DeepPot.h, source/api_cc/src/DeepPot.cc
Refactor `DeepPotModelDevi` as a step of #3122. Now, it is just a wrapper of multiple `DeepPot` classes. Models can have different behaviors inside different `DeepPot`.
One may argue that the new class needs to prepare the input multiple times. However, it's not expensive only to copy the memory. Also, during the simulations, usually we run it every 100 steps.
=> cc: refactor DeepPotModelDevi, making it framework-independent

deepmd_utils/model_format/__init__.py, deepmd_utils/model_format/common.py, deepmd_utils/model_format/output_def.py, source/tests/test_output_def.py
- add `__call__` method for `NativeOP`. 
- adapt UTs accordingly.
=> fix: model check assumes __call__ as the forward method

deepmd_utils/model_format/__init__.py, deepmd_utils/model_format/network.py, source/tests/test_model_format_utils.py
- also add doc string for the embedding net
=> support fitting net

README.md
Update caution notes and re-formatting README.md in old paddle branch as @njzjz advised at #3127 .
=> [Paddle Backend] Deprecate old paddle branch

deepmd_utils/model_format/network.py, deepmd_utils/model_format/se_e2_a.py, source/tests/test_model_format_utils.py
- add parameter shape consistency check for layer 
- add input-output shape consistency check for net
=> refactorize NativeLayer, interface does not rely on the platform

deepmd/utils/batch_size.py, deepmd_utils/utils/batch_size.py
See https://github.com/deepmodeling/deepmd-kit/issues/3118 and https://github.com/dptech-corp/deepmd-pytorch/issues/137. Subclass needs to implement `is_gpu_available` and `is_oom_error`.
=> add cross-platform AutoBatchSize

deepmd/entrypoints/doc.py, deepmd/entrypoints/gui.py, deepmd_utils/entrypoints/__init__.py, deepmd_utils/entrypoints/doc.py, deepmd_utils/entrypoints/gui.py
=> move deepmd.entrypoints.{doc,gui} to deepmd_utils.entrypoints.{doc,gui}

source/api_cc/include/DeepPot.h, source/api_cc/include/DeepPotTF.h, source/api_cc/include/common.h, source/api_cc/src/DeepPot.cc, source/api_cc/src/DeepPotTF.cc
See #3119.
At this time, only TF is supported in such the multiple-backend framework.
=> cc: refactor DeepPot to support multiple backends

source/api_cc/include/DataModifier.h, source/api_cc/include/DataModifierTF.h, source/api_cc/src/DataModifier.cc, source/api_cc/src/DataModifierTF.cc
=> cc: refactor DataModifier for multiple-backend framework

doc/third-party/out-of-deepmd-kit.md
AmberTools24 should be released in April 2024.
=> docs: update Amber interface

deepmd/utils/errors.py, deepmd_utils/utils/batch_size.py, deepmd_utils/utils/errors.py
=> move `OutOfMemoryError` from `deepmd` to `deepmd_utils`

source/lib/src/gpu/CMakeLists.txt
Fix https://github.com/deepmodeling/deepmd-kit/discussions/2523#discussioncomment-8176469.
[`CMAKE_<LANG>_FLAGS`](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_FLAGS.html#variable:CMAKE_%3CLANG%3E_FLAGS) is a string, so when using `set`, we should use quotes.
=> cmake: fix setting `CMAKE_HIP_FLAGS`

deepmd/infer/deep_pot.py, deepmd_utils/infer/__init__.py, deepmd_utils/infer/backend.py, deepmd_utils/infer/deep_pot.py, source/tests/test_uni_infer.py
Need discussion for other classes.
=> add universal Python inference interface DeepPot

.github/workflows/build_wheel.yml, pyproject.toml
Fix #3168.
See: https://github.com/pypa/setuptools_scm/issues/1006#issuecomment-1905563223
=> detect version in advance before building deepmd-kit-cu11

README.md, backend/dynamic_metadata.py, deepmd_utils/driver.py, doc/third-party/dpdata.md, doc/third-party/index.md, doc/third-party/index.rst, doc/third-party/out-of-deepmd-kit.md, pyproject.toml, source/tests/test_deeppot_a.py
Add a dpdata driver via the plugin mechanism (override that in the dpdata package) so it can benefit from the multiple-backend DeepPot. Currently, the driver in the dpdata package has to support both v1 and v2 for backward compatibility. When shipped within the deepmd-kit package, it only needs to support the current deepmd-kit version.
=> add dpdata driver

deepmd_utils/infer/deep_pot.py
They are used by the downstream APIs, so must be implemented.
=> add more abstractmethods to universal `DeepPot`

source/api_cc/include/DataModifier.h, source/api_cc/include/DataModifierTF.h, source/api_cc/src/DataModifier.cc
Fix the following compiler warning:
```
/home/runner/work/deepmd-kit/deepmd-kit/source/api_c/src/c_api.cc:1336:17: warning: returning address of local temporary object [-Wreturn-stack-address]
return (int*)&(dcm->dcm.sel_types())[0];
^~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```
by returning the reference of `sel_type`.
`DataChargeModifier.sel_types` is not used anywhere, even in the test, so we don't have a chance to determine if there is a possible segfault, and this warning has no actual impact.
It seems `DeepTensor` has returned a reference since the beginning (https://github.com/deepmodeling/deepmd-kit/pull/137). (perhaps because `DeepTensor.sel_types` is used) `DeepTensor` and `DataChargeModifier` have different returned types.
=> cc: fix returning type of sel_types

backend/find_tensorflow.py, backend/read_env.py, deepmd/tf/utils/tabulate.py, doc/development/coding-conventions.rst, doc/install/easy-install.md, doc/install/install-from-source.md, pyproject.toml, source/install/build_tf.py
=> breaking: drop Python 3.7 support

deepmd/infer/deep_pot.py, deepmd/main.py, deepmd/pt/entrypoints/main.py, deepmd/tf/entrypoints/main.py, deepmd/utils/argcheck.py
Just merge in form. Several options or subcommands are only supported by TensorFlow or PyTorch.
Also, avoid import from `deepmd.tf` in `deepmd.utils.argcheck`.
```
Use --tf or --pt to choose the backend:
dp --tf train input.json
dp --pt train input.json
```
=> Merge TF and PT CLI

deepmd/infer/deep_pot.py, deepmd/pt/infer/deep_eval.py, deepmd/pt/utils/ase_calc.py, source/tests/pt/test_calculator.py, source/tests/pt/test_deeppot.py
- Set `deepmd.pt.utils.ase_calc.DPCalculator` as an alias of `deepmd.calculator.DP`;
- Replace `deepmd_pt` with  `deepmd.pt` in `deep_pot.py`; fix (atomic) virial output shape of `DeepPot`; add tests for them;
- Set `pbc` in `pt/test_calculator.py` as it requests stress.
=> Fix PT `DeepPot` and replace ASE calculator

deepmd/common.py, deepmd/main.py, deepmd/pt/entrypoints/main.py, deepmd/pt/train/training.py, deepmd/tf/train/trainer.py, source/tests/pt/water/se_atten.json
Set the default `save_ckpt` to `model.ckpt` as the prefix. When saving checkpoints, `model.ckpt-100.pt` will be saved, and `model.ckpt.pt` will be symlinked to `model.ckpt-100.pt`. A `checkpoint` file will be dedicated to record `model.ckpt-100.pt`.
This keeps the same behavior as the TF backend. One can do the below using the PT backend just like the TF backend:
```sh
dp --pt train input.json
dp --pt freeze
```
=> PT: keep the same checkpoint behavior as TF

deepmd/pt/utils/dataset.py, deepmd/utils/random.py
Fix https://github.com/deepmodeling/deepmd-kit/security/code-scanning/2096
=> add size and replace arguments to deepmd.utils.random.choice

CITATIONS.bib, backend/dynamic_metadata.py, doc/backend.md, doc/conf.py, doc/credits.rst, doc/index.rst, doc/inference/python.md, doc/install/easy-install-dev.md, doc/install/easy-install.md, doc/install/install-from-c-library.md, doc/install/install-from-source.md, doc/model/dpa2.md, doc/model/index.rst, doc/model/train-energy.md, doc/model/train-se-atten.md, doc/model/train-se-e2-a.md, doc/train/finetuning.md, doc/train/multi-task-training.md
Fix #3121.
There are TODOs:
(1) PyTorch-backend specific features and arguments;
(2) Python interface installation. Currently, the TensorFlow backend is always installed, and I am considering rewriting the logic;
(3) Unsupported features - write docs when implemented.
=> docs: document PyTorch backend

source/install/docker/Dockerfile
The default one from PyPI is for CU12.
=> fix: install CU11 PyTorch in the CU11 docker image

source/CMakeLists.txt
If so, throw the following error:
```
-- PyTorch CXX11 ABI: 0
CMake Error at CMakeLists.txt:162 (message):
PyTorch CXX11 ABI mismatch TensorFlow: 0 != 1
```
=> throw errors when PyTorch CXX11 ABI is different from TensorFlow

.github/workflows/build_wheel.yml, backend/find_tensorflow.py, pyproject.toml
Today [GitHub introduced the new M1 runners](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/), making it possible to build macos-arm64 wheels without cross-building.
Remove old hacked codes for cross-building.
=> build macos-arm64 wheel on M1 runners

source/CMakeLists.txt
Fix #3214.
In the gmx patch file, `${TENSORFLOW_ROOT}` is used other than `${TensorFlow_LIBRARY_PATH}$` or `${TENSORFLOW_INCLUDE_DIRS}`, so the fastest workaround is to set `${TENSORFLOW_ROOT}`.
https://github.com/deepmodeling/deepmd-kit/blob/eb9b2efedf4efc946894800a0d7abf5056f4bb7a/source/gmx/patches/2020.2/CMakeLists.txt.patch.in#L14-L18
=> fix compile gromacs with precompiled C library

source/gmx/CMakeLists.txt, source/gmx/include/gmx_plugin.h
=> gmx: fix include directive

.github/workflows/build_wheel.yml, .github/workflows/test_cc.yml, .pre-commit-config.yaml, backend/find_tensorflow.py, doc/inference/cxx.md, examples/infer_water/infer_water.c, pyproject.toml, source/CMakeLists.txt, source/api_c/include/c_api.h, source/api_c/include/deepmd.hpp, source/api_c/src/c_api.cc, source/api_c/tests/test_deeppot_a.cc, source/api_cc/include/DataModifier.h, source/api_cc/include/DataModifierTF.h, source/api_cc/src/DataModifier.cc, source/gmx/CMakeLists.txt, source/gmx/include/gmx_plugin.h
Cherry-pick: #3163, #3181, #3217, #3221, #3223, #3206
> [!Note]
> This PR should not be squashed.
=> [r2] Collected changes and fixes from devel

deepmd/dpmodel/model/make_model.py, deepmd/pt/model/model/make_model.py
=> fix model doc str: add shape hint to doc string.

.github/workflows/build_wheel.yml, pyproject.toml
Cherry-pick #3172. Original message:
----
Fix #3168.
See:
https://github.com/pypa/setuptools_scm/issues/1006#issuecomment-1905563223
=> [r2] detect version in advance before building deepmd-kit-cu11

deepmd/pt/infer/deep_eval.py, deepmd/pt/model/model/ener.py, source/tests/pt/test_model.py
To be consistent with TF, as discussed in https://github.com/deepmodeling/deepmd-kit/pull/3213#discussion_r1477183841. Old PT models are expected to be incompatible.
=> pt: rename atomic_virial to atom_virial in the model output

deepmd/env.py, deepmd/pt/entrypoints/main.py, deepmd/pt/infer/inference.py, deepmd/pt/model/model/model.py, deepmd/pt/model/task/dipole.py, deepmd/pt/model/task/ener.py, deepmd/pt/model/task/fitting.py, deepmd/pt/optimizer/LKF.py, deepmd/pt/train/training.py, deepmd/pt/train/wrapper.py, deepmd/pt/utils/dataloader.py, deepmd/pt/utils/dataset.py, deepmd/pt/utils/finetune.py, deepmd/pt/utils/preprocess.py, deepmd/pt/utils/stat.py, deepmd/utils/pair_tab.py
We can change the format of the global logger in the future if the additional information is helpful (e.g., time, path, etc).
=> pt: apply global logger to pt

backend/find_tensorflow.py
Avoid installing tensorflow as build requires when `DP_ENABLE_TENSORFLOW` is `0`.
=> fix DP_ENABLE_TENSORFLOW support

deepmd/dpmodel/fitting/invar_fitting.py, deepmd/dpmodel/model/make_base_atomic_model.py, deepmd/dpmodel/model/pair_tab_model.py, deepmd/dpmodel/model/transform_output.py, deepmd/dpmodel/output_def.py, deepmd/pt/model/model/pair_tab_model.py, deepmd/pt/model/model/transform_output.py, deepmd/pt/model/task/denoise.py, deepmd/pt/model/task/ener.py, source/tests/common/dpmodel/test_output_def.py
solve some virial shape issue: should be [9] rather than [3,3]
=> support separate r_differentiable and c_differentiable

deepmd/dpmodel/output_def.py, source/tests/common/dpmodel/test_output_def.py
hessian not implemented in neither tf nor pt.
=> add hessian support in output def.

deepmd/main.py, deepmd/tf/entrypoints/freeze.py
To have the same behavior between TF and PT.
=> tf: support checkpoint path (instead of directory) in dp freeze

doc/install/install-from-c-library.md, source/CMakeLists.txt, source/ipi/CMakeLists.txt, source/ipi/driver.cc, source/ipi/tests/test_driver.py
(1) Remove `normalize_coord` and add a test to confirm it still works;
(2) Remove the include of `SimulationRegion.h` and the direct link to `libdeepmd.so`;
(3) Allow using a pre-compiled C library to build `dp_ipi`.
=> ipi: remove normalize_coord

deepmd/dpmodel/__init__.py, deepmd/dpmodel/output_def.py, deepmd/dpmodel/utils/env_mat.py, deepmd/pt/model/descriptor/env_mat.py, deepmd/pt/model/model/__init__.py, deepmd/pt/model/model/ener.py, deepmd/pt/model/model/make_hessian_model.py, deepmd/pt/model/model/make_model.py, deepmd/pt/model/model/transform_output.py, source/tests/pt/model/test_make_hessian_model.py
restrictions:
- cannot jit
- only the `forward_common` interface has its hessian calculation. not for `forward_common_lower`.
- may give nan when nall == nloc. specifically when nloc==1
also fix bug in pt: transform_output. The output shape will be wrong when the dimension of output variable is larger than 1.
=> Implement hessian autodiff calculation

deepmd/pt/model/task/ener.py
the stats are actually not well tested, see https://github.com/deepmodeling/deepmd-kit/issues/3278
=> feat: pt: support user specified rcond for fitting stat

deepmd/dpmodel/descriptor/se_e2_a.py, deepmd/dpmodel/fitting/invar_fitting.py, deepmd/dpmodel/utils/__init__.py, deepmd/dpmodel/utils/exclude_mask.py, deepmd/pt/model/descriptor/descriptor.py, deepmd/pt/model/descriptor/hybrid.py, deepmd/pt/model/descriptor/repformers.py, deepmd/pt/model/descriptor/se_a.py, deepmd/pt/model/descriptor/se_atten.py, deepmd/pt/model/task/ener.py, deepmd/pt/model/task/fitting.py, deepmd/pt/utils/__init__.py, deepmd/pt/utils/exclude_mask.py, deepmd/pt/utils/exclude_types.py, source/tests/common/dpmodel/test_exclusion_mask.py, source/tests/common/dpmodel/test_fitting_invar_fitting.py, source/tests/pt/model/test_ener_fitting.py, source/tests/pt/model/test_exclusion_mask.py
- implement fitting exclude types
- pt: refactorize the pair exclusion masks as torch modules.
=> feat: dp and pt: implement fitting exclude types

deepmd/pt/utils/env_mat_stat.py
Resolves https://github.com/deepmodeling/deepmd-kit/pull/3285#discussion_r1493338812.
We don't even need to consider whether the data uses mixed type in this piece of code. The data can be reshaped to the atom level, and type masks can be used to get an environmental matrix with certain types. No frame-level things are involved here.
=> pt: process frames in parallel for env mat stat

source/tests/pt/model/test_descriptor_dpa1.py, source/tests/pt/model/test_descriptor_dpa2.py
Why it is bad:
The default dtype in the producution code is still float32. When setting it to float64 during tests, the actual producation behavior may not be properly tested. (for example, if the production code misses dtype for pt.zeros, we are not able to find it in these tests)
=> pt: avoid `set_default_dtype` in tests

deepmd/dpmodel/utils/neighbor_stat.py, deepmd/entrypoints/neighbor_stat.py, deepmd/main.py, deepmd/pt/utils/neighbor_stat.py, deepmd/tf/entrypoints/train.py, deepmd/tf/utils/neighbor_stat.py, deepmd/utils/neighbor_stat.py, source/tests/common/dpmodel/test_neighbor_stat.py, source/tests/pt/test_neighbor_stat.py, source/tests/tf/test_neighbor_stat.py, source/tests/tf/test_virtual_type.py
It was broken by #3289, which replaced distinguished types by mixed types but didn't change the input.
Add tests for two types.
=> fix neighbor stat mixed_types input

pyproject.toml
This seems to fix the GPG key error posted at https://github.com/deepmodeling/deepmd-kit/pull/3325#issuecomment-1960484188. See https://almalinux.org/blog/2023-12-20-almalinux-8-key-update/
=> fix AlmaLinux GPG key error

deepmd/pt/model/descriptor/se_a.py, deepmd/pt/model/descriptor/se_atten.py, source/tests/consistent/common.py, source/tests/consistent/descriptor/test_se_e2_a.py
The output should cast back to the global precision.
=> pt: fix se_e2_a precision cast

deepmd/dpmodel/model/make_model.py, deepmd/pt/infer/deep_eval.py, deepmd/pt/model/model/make_model.py, source/tests/pt/model/test_deeppot.py
=> pt: export `model_output_type` instead of `model_output_def`

deepmd/backend/backend.py, deepmd/backend/dpmodel.py, deepmd/backend/pytorch.py, deepmd/backend/tensorflow.py, deepmd/dpmodel/utils/network.py, deepmd/entrypoints/convert_backend.py, deepmd/entrypoints/main.py, deepmd/main.py, deepmd/pt/model/atomic_model/base_atomic_model.py, deepmd/pt/model/atomic_model/dp_atomic_model.py, deepmd/pt/model/atomic_model/linear_atomic_model.py, deepmd/pt/model/atomic_model/pairtab_atomic_model.py, deepmd/pt/model/descriptor/se_atten.py, deepmd/pt/model/model/__init__.py, deepmd/pt/utils/serialization.py, deepmd/tf/fit/ener.py, deepmd/tf/model/model.py, deepmd/tf/utils/serialization.py, source/tests/common/dpmodel/test_network.py, source/tests/consistent/io/__init__.py, source/tests/consistent/io/test_io.py
```sh
dp convert-backend model.pb model.pth
dp convert-backend model.pb model.dp
```
=> feat: convert model files between backends

deepmd/backend/dpmodel.py, deepmd/dpmodel/infer/__init__.py, deepmd/dpmodel/infer/deep_eval.py, deepmd/dpmodel/utils/batch_size.py, source/tests/consistent/io/test_io.py
While a DPModel cannot be directly trained, it can be converted from another model:
```sh
dp convert-backend frozen_model.pth frozen_model.dp
dp test -m frozen_model.dp -s ../data/
```
The energy result is consistent with TF and PT. Force and virial are NaN, as expected.
=> feat: add NumPy DeepPot

.github/workflows/test_python.yml, backend/find_tensorflow.py, deepmd/tf/descriptor/se_atten.py, deepmd/tf/env.py
Fix a bug caused by the breaking change in Keras 3 (shipped by TF 2.16).
=> bump python to 3.12 in the test environment

deepmd/pt/utils/env_mat_stat.py, source/tests/pt/model/test_descriptor_se_r.py
=> Fix: se_r prod_env_mat

deepmd/pt/model/descriptor/se_a.py
The code in this PR is ugly, but applying a mask is causing performance degradation for ~3 ms/step.
When applying a mask, `aten::nonzero` has a high host time, as it causes host-device synchronization:
After fixing:
See https://github.com/pytorch/pytorch/issues/12461 for more information.
=> pt: fix se_a type_one_side performance degradation

doc/model/train-se-e2-r.md, doc/train/multi-task-training.md, examples/dos/train/input.json, examples/fparam/train/input.json, examples/fparam/train/input_aparam.json, examples/nopbc/train/input.json, examples/spin/se_e2_a/input.json, examples/water/d3/input.json, examples/water/dplr/train/dw.json, examples/water/dplr/train/ener.json, examples/water/hybrid/input.json, examples/water/se_e2_a/input.json, examples/water/se_e2_a/input_torch.json, examples/water/se_e2_a_mixed_prec/input.json, examples/water/se_e2_r/input.json, examples/water/zbl/input.json, examples/water_multi_task/ener_dipole/input.json, examples/water_tensor/dipole/dipole_input.json, examples/water_tensor/polar/polar_input.json, examples/zinc_protein/zinc_se_a_mask.json
=> docs: apply type_one_side=True to `se_a` and `se_r`

deepmd/dpmodel/fitting/general_fitting.py, deepmd/dpmodel/fitting/invar_fitting.py, deepmd/pt/model/task/ener.py, deepmd/pt/model/task/fitting.py, deepmd/tf/fit/ener.py, source/tests/consistent/fitting/test_ener.py
Also, fix the TF serialization issue (it tried to store a tensor instead of a NumPy array).
=> feat: atom_ener in energy fitting

deepmd/main.py, deepmd/pt/entrypoints/main.py
1. Support `--output` in `dp train`;
2. move argcheck before neighbor-stat, which is consistent with TF.
=> pt: supprot `--output` in `dp train`

pyproject.toml, source/tests/pt/test_multitask.py, source/tests/pt/test_training.py
See https://github.com/pytorch/pytorch/issues/61844
=> pt: ban `torch.testing.assert_allclose`

source/tests/pt/model/test_null_input.py
test the cases: 
1. system only has one atom
2. system has two atoms that are far away from each other. 
In each cases, the force and virial predictions should be zero and energy should be a valid float.
=> ut: add null test

deepmd/common.py, deepmd/pt/utils/dataset.py, deepmd/utils/data.py, deepmd/utils/data_system.py, source/tests/tf/test_data_requirement.py, source/tests/tf/test_deepmd_data.py
A new parameter, `output_natoms_for_type_sel`, is added for the data requirement. (default=false)
If sel_types is given, output_natoms_for_type_sel is true, and the data dimension is nsel, it will be converted to natoms.
If sel_types is given, output_natoms_for_type_sel is false, and the data dimension is natoms, it will be converted to nsel.
In other situations, it keeps the original shape.
The user can give data in either nsel or natoms, if `sel_types` and `output_natoms_for_type_sel` are set.
=> allow loading either nsel or natoms atomic tensor data

deepmd/dpmodel/descriptor/hybrid.py, deepmd/pt/model/descriptor/hybrid.py
g2, h2, and sw are heavily dependent on the neighbor list. We cannot ensure the sub descriptors require the same neighbor list as the parent descriptor.
=> do not return g2, h2, sw in hybrid descriptors

.github/workflows/build_wheel.yml, .github/workflows/package_c.yml
It looks when setting `branches-ignore`, the push on tags will not trigger the GitHub Actions. Setting `tags` is necessary. (So I have to manually upload the package again...)
=> fix github actions for release

.github/workflows/build_wheel.yml, pyproject.toml
Fix #3168.
#3172 didn't fix #3168. The environmental variable `SETUPTOOLS_SCM_PRETEND_VERSION` works. I don't know what's wrong with the previous one.
In this PR, I deleted the `.git` directory for `deepmd-kit-cu11`, which will throw an error if it doesn't work.
=> fix deepmd-kit-cu11 again

source/CMakeLists.txt, source/api_cc/CMakeLists.txt
Backported from https://github.com/conda-forge/deepmd-kit-feedstock/pull/71.
1. The rpath of libdeepmd_cc should contain the libtorch directory if it differs from the path of libdeepmd_cc. Setting `INSTALL_RPATH_USE_LINK_PATH` to `true` resolves the problem.
2. `${TORCH_CXX_FLAGS}` is empty in macOS, so the variable with quotes, i.e. `"${TORCH_CXX_FLAGS}"`, should be used.
=> pt: Fix compilation with libtorch

.github/workflows/test_python.yml
Python 3.12 or TF 2.16 seems to be slowing down...
=> revert test Python to 3.11

deepmd/dpmodel/fitting/general_fitting.py, deepmd/pt/model/task/fitting.py, source/tests/common/dpmodel/test_fitting_invar_fitting.py, source/tests/pt/model/test_ener_fitting.py
This can give the correct result for `dp test`,
```sh
cd examples/water_tensor/dipole
dp --pt train input_torch.json
dp --pt freeze
dp test -m frozen_model.pth -s validation_data/global_system/
```
=> convert exclude_types to sel_type

deepmd/pt/model/descriptor/se_a.py
sec is used as a slice index, so it should not stored on the GPU, otherwise, D2H will happen to create the tensor with the shape.
Before:
After:
=> pt: avoid D2H in se_e2_a

deepmd/pt/train/training.py, deepmd/pt/utils/nlist.py, deepmd/pt/utils/region.py
1. use inv_ex instead of inv. `inv_ex` does not check errors. We can assume the input is correct.
2. pass CPU box for `torch.arange`;
3. avoid torch.tensor.
=> pt: improve nlist performance

deepmd/pt/train/training.py
`to(DEVICE)` is cpu-blocking but `to(DEVICE, non-blocking=True)` is not blocking. This improves performance by at least 0.1s/100 steps.
Before, `get_data` is blocking:
After, `get_data` is not blocking:
The subsequent blocking is `phys2inter` (via `torch.linalg.inv`).
=> pt: make get_data non-blocking

deepmd/pt/train/training.py
#3405 changed results from `None` to `{}` but `print_on_training` wasn't revised.
=> pt: fix print_on_training when there is no validation data

deepmd/dpmodel/atomic_model/make_base_atomic_model.py, deepmd/dpmodel/model/base_model.py, deepmd/dpmodel/model/make_model.py, deepmd/pt/model/atomic_model/base_atomic_model.py, deepmd/pt/model/atomic_model/dp_atomic_model.py, deepmd/pt/model/atomic_model/linear_atomic_model.py, deepmd/pt/model/atomic_model/pairtab_atomic_model.py, deepmd/pt/model/model/make_model.py, deepmd/pt/model/model/model.py
After #3438, `model_def_script` is no more saved in AtomicModel.
=> fix: remove model_def_script from AtomicModel

deepmd/dpmodel/fitting/invar_fitting.py, deepmd/dpmodel/fitting/make_base_fitting.py
=> chore: remove unused init_fitting_stat

deepmd/dpmodel/utils/network.py, source/tests/pt/model/test_ener_fitting.py
=> fix the bug of empty fitting net neuron.

.github/workflows/test_cc.yml
This week, a random segfault occurred in GHA when using `-fsanitize=leak`. It seems related to https://github.com/actions/runner-images/issues/9491. Workaround: https://github.com/actions/runner-images/issues/9491#issuecomment-1989718917
See also: https://stackoverflow.com/questions/77894856/possible-bug-in-gcc-sanitizers
=> ci: reduce ASLR entropy

deepmd/infer/deep_eval.py, deepmd/tf/infer/deep_eval.py
The energy fitting network computes `nloc` by summing over `natoms[2:]` instead of reading `natoms[0]`.
https://github.com/deepmodeling/deepmd-kit/blob/8dab33bbe8248d9f337933f778be3e119948357e/deepmd/tf/fit/ener.py#L717-L720
This causes an issue for the virtual types after refactoring `DeepEval`. Before, `natoms_vec` is `[nloc, nall, nloc, ...]` for mixed types. After refactoring, we use the same `natoms_vec` for mixed_types and the normal case, so the virtual type support is broken.
This was not detected by the test, as the test model for the virtual types was added 12 months ago, but the energy fitting was changed 10 months ago.
=> fix(tf): fix DeepEval degradation for virtual types

source/lmp/plugin/CMakeLists.txt
This pull request fixes the broken symlink for `dpplugin.so` on macOS. It should point to `libdeepmd_lmp.so` but point to `libdeepmd_lmp.dylib` instead.
The `libdeepmd_lmp` is a shared module.
https://github.com/deepmodeling/deepmd-kit/blob/b875ea8f6661b6e1567537ead7e2b4a8b14ea113/source/lmp/plugin/CMakeLists.txt#L72
The build target name on macOS is `libdeepmd_lmp.so`.
Because on macOS, the `CMAKE_SHARED_MODULE_SUFFIX` (`.so`) is different from `CMAKE_SHARED_LIBRARY_SUFFIX` (`.dynlib`). As a result, in previous versions, on macOS the symbolic link `dpplugin.so` was pointed to `libdeepmd_lmp.dylib`, which does not exist. One can check the conda-forge builds to confirm (e.g., [osx-arm64/deepmd-kit-2.2.9-cpu_py311hf5376d5_mpi_openmpi_0.conda](https://anaconda.org/conda-forge/deepmd-kit/2.2.9 …
=> Fix LAMMPS plugin symlink path on macOS platform

deepmd/pt/model/atomic_model/pairtab_atomic_model.py
Reduce memory usage of `_extract_spline_coefficient`.
=> fix(pt): Fix PairTabAtomicModel OOM error

deepmd/pt/loss/ener.py, deepmd/pt/loss/ener_spin.py, deepmd/pt/loss/loss.py, deepmd/pt/loss/tensor.py, deepmd/pt/train/training.py, deepmd/pt/train/wrapper.py, source/tests/pt/model/test_model.py, source/tests/pt/test_loss.py
This PR updates the loss interface to allow for a more flexible design. 
It enables processing input tensors before feeding them into the model, such as denoising operations (fyi @Chengqian-Zhang ). Previously, this was done in the data loader, which was less intuitive and more confusing. Now, users can easily handle these tasks within the loss function itself, as demonstrated in similar implementations in uni-mol: https://github.com/dptech-corp/Uni-Mol/blob/main/unimol/unimol/losses/unimol.py#L20.
=> pt: refactor loss

deepmd/pt/infer/deep_eval.py
=> pt: support multitask dp test

deepmd/tf/fit/dipole.py, deepmd/tf/fit/dos.py, deepmd/tf/fit/ener.py, deepmd/tf/fit/polar.py, deepmd/tf/model/model.py, source/tests/consistent/fitting/test_dipole.py, source/tests/consistent/fitting/test_dos.py, source/tests/consistent/fitting/test_ener.py, source/tests/consistent/fitting/test_polar.py
Fix #3533. Fix #3542. Fix #3545. Fix #3546. Fix #3547. Fix #3548. Fix #3549. Fix #3550.
=> tf: add explict mixed_types argument to fittings

deepmd/infer/model_devi.py
=> fix:  natom error in calc_model_devi

deepmd/common.py, deepmd/dpmodel/common.py, deepmd/pt/model/network/mlp.py, deepmd/pt/utils/env.py, deepmd/pt/utils/utils.py, deepmd/tf/common.py, deepmd/tf/utils/graph.py, deepmd/utils/argcheck.py, pyproject.toml, source/tests/consistent/fitting/test_ener.py, source/tests/consistent/test_activation.py
Fix #3553.
To support bfloat16,
- DP: As NumPy doesn't plan to support bfloat16, use `ml_dtypes.bfloat16`. The `ml_dtypes` package, developed by Google, is required.
- TF: use `tf.make_ndarray` instead of manually extracting information from a tensor node.
- PT: As ml_dtypes is not supported yet (https://github.com/pytorch/pytorch/issues/109873), use float32 as a bridge.
=> feat: Support bfloat16 and ensure valid precision and activation functions consistent everywhere

deepmd/pt/utils/finetune.py
fix #3604 , when doing single-task finetuning from multitask pretrained model and do not define the finetune model branch from command-line or input file.
=> pt: fix typo in multitask finetune

source/lib/src/gpu/prod_env_mat.cu
=> chore: remove incorrect memset TODOs

backend/dynamic_metadata.py
`nvidia-cudnn-cu12` 9.0.0.312 seems broken (and might not be compatible)
=> pin nvidia-cudnn-cu{11,12} to <9

deepmd/pt/utils/dataloader.py
https://github.com/deepmodeling/deepmd-kit/issues/3475
=> pt: support list format  batch size

deepmd/dpmodel/descriptor/se_e2_a.py, deepmd/dpmodel/descriptor/se_r.py, deepmd/tf/descriptor/loc_frame.py, deepmd/tf/descriptor/se_a.py, deepmd/tf/descriptor/se_a_ebd.py, deepmd/tf/descriptor/se_a_ebd_v2.py, deepmd/tf/descriptor/se_a_ef.py, deepmd/tf/descriptor/se_a_mask.py, deepmd/tf/descriptor/se_atten.py, deepmd/tf/descriptor/se_atten_v2.py, deepmd/tf/descriptor/se_r.py, deepmd/tf/descriptor/se_t.py
The wrong type hint appeared in f5c67af0d99e9e5af35695b3b3e89524facfe427, very old...
=> fix: fix type hint of sel

deepmd/pt/utils/auto_batch_size.py, source/tests/pt/test_auto_batch_size.py
- also add missing UT for execute_all
=> feat: auto batch size supports methods that return a dict

deepmd/pt/model/atomic_model/base_atomic_model.py, deepmd/pt/model/atomic_model/pairtab_atomic_model.py, deepmd/pt/model/task/invar_fitting.py, deepmd/pt/utils/stat.py, source/tests/pt/test_stat.py
- add UT for it.
- at the moment, only energy is supported in the `base_atomic_model`. handling of multiple output stat will be implemented in a future PR.
=> feat: compute output stat for a dict of labels.

deepmd/tf/descriptor/se_atten.py
Currently, `se_atten_v2` is always masked to zero when `exclude_types` is given. However, for the no neighbor case, the placeholder for a virtual neighbor is `davg`. This causes discontinuity when `set_davg_zero` is not set.
This PR uses `davg` for masking.
In production, we usually use `set_davg_zero` along with `exclude_types`, so it hasn't caused a real problem.
I notice PT hasn't implemented `se_atten_v2` or `exclude_types`, but we need attention in the future.
=> fix(tf): make `se_atten_v2` masking smooth when davg is not zero

deepmd/pt/entrypoints/main.py, deepmd/utils/argcheck.py, deepmd/utils/env_mat_stat.py, examples/water/dpa2/input_torch.json, examples/water/se_atten/input_torch.json, examples/water/se_e2_a/input_torch.json, source/tests/pt/model/test_saveload_dpa1.py, source/tests/pt/model/water/multitask.json
If the stat file ends with .h5 or .hdf5, an HDF5 file is used; otherwise, a directory containing NumPy binary files is used. This gives flexibility to users.
=> feat(pt): allow using directories to store stat

deepmd/dpmodel/atomic_model/make_base_atomic_model.py, deepmd/pt/model/atomic_model/base_atomic_model.py, deepmd/pt/model/model/make_model.py, deepmd/pt/model/task/invar_fitting.py, deepmd/pt/train/training.py, deepmd/pt/utils/stat.py, source/tests/common/dpmodel/test_dp_atomic_model.py, source/tests/pt/test_finetune.py
-    clean up the interface of `change_out_bias`
-    refact `compute_output_stats`, so the code is more readable.
=> refact: compute_output_stats and change_out_bias 

source/api_c/include/c_api.h, source/api_c/include/deepmd.hpp, source/api_c/src/c_api.cc, source/api_c/tests/test_deeppot_model_devi_fparam_aparam.cc, source/api_c/tests/test_deeppot_model_devi_hpp.cc, source/api_cc/include/DeepPot.h, source/api_cc/src/DeepPot.cc, source/api_cc/tests/test_deeppot_model_devi.cc, source/api_cc/tests/test_deeppot_model_devi_fparam_aparam.cc
To solve this issue:
https://github.com/deepmodeling/deepmd-kit/issues/3641
=> feat: model devi C/C++ API without nlist

deepmd/dpmodel/atomic_model/base_atomic_model.py, deepmd/dpmodel/atomic_model/dp_atomic_model.py, deepmd/dpmodel/atomic_model/linear_atomic_model.py, deepmd/dpmodel/atomic_model/make_base_atomic_model.py, deepmd/dpmodel/atomic_model/pairtab_atomic_model.py, deepmd/dpmodel/output_def.py, deepmd/pt/model/atomic_model/base_atomic_model.py, deepmd/pt/model/atomic_model/dp_atomic_model.py, deepmd/pt/model/atomic_model/linear_atomic_model.py, deepmd/pt/model/atomic_model/pairtab_atomic_model.py, deepmd/pt/model/task/invar_fitting.py, deepmd/pt/utils/stat.py, deepmd/utils/out_stat.py, source/tests/common/dpmodel/test_dp_atomic_model.py, source/tests/pt/model/test_atomic_model_stat.py, source/tests/pt/test_finetune.py, source/tests/pt/test_multitask.py, source/tests/pt/test_stat.py
This PR:
- breaking change: the base atomic model is now a module. 
- reason: the out stat is a data attribute of the base atomic model. 
- implement the `compute_or_load_output_stat` for the base atomic model. the method computes both bias and std. 
- the derived atomic models call the `compute_or_load_output_stat`  method for computing output stat. 
- atomic model provides the `apply_out_stat`, the derived class may override the method to define how the statistics is applied to an atomic model's output. @anyangml may need. 
- `out_stat` support statistics of output tensor of any shape. 
@iProzd  please check if i took it correctly in [ce7ec1f](https://github.com/deepmodeling/deepmd-kit/pull/3642/commits/ce7ec1f39be669fcc63a05e9474bc248d9a54d8a)
To be done:
- atomic statistics of the …
=> compute output stat for atomic model

deepmd/tf/descriptor/se_atten.py, source/tests/tf/test_model_se_atten.py
I construct a test case in which all old implementations fail.
=> fix(tf): apply exclude types to se_atten_v2 switch

.github/workflows/package_c.yml, source/install/docker_package_c.sh
Fix the following error in docker_package_c.sh
```
-- Found Git: /usr/bin/git (found version "2.25.1")
fatal: detected dubious ownership in repository at '/root/deepmd-kit'
To add an exception for this directory, call:
git config --global --add safe.directory /root/deepmd-kit
```
In addition, fetching git tags in actions/checkout.
=> fix: fix git version detection in docker_package_c.sh

deepmd/dpmodel/atomic_model/base_atomic_model.py, deepmd/dpmodel/atomic_model/dp_atomic_model.py, deepmd/dpmodel/atomic_model/linear_atomic_model.py, deepmd/dpmodel/atomic_model/pairtab_atomic_model.py, deepmd/pt/model/atomic_model/base_atomic_model.py, deepmd/pt/model/atomic_model/dp_atomic_model.py, deepmd/pt/model/atomic_model/linear_atomic_model.py, deepmd/pt/model/atomic_model/pairtab_atomic_model.py, deepmd/tf/model/model.py, source/tests/pt/model/test_atomic_model_stat.py
- implement serialize and deserialize for atomic model's compute output stat
- intensive change to the linear atomic models' serialization. @anyangml please help checking the changes.
=> feat: support serialize and deserialize for atomic model's compute output stat

.github/workflows/build_cc.yml, .github/workflows/test_cc.yml, .github/workflows/test_cuda.yml, .github/workflows/test_python.yml, source/install/docker/Dockerfile, source/install/docker_package_c.sh
Setup [`uv`](https://github.com/astral-sh/uv) in the GitHub Actions, saving several minutes compared to pip.
pip:
uv:
Using `uv` has some limitations, but it's good to use it in the CI.
=> CI: Accerate GitHub Actions using uv

deepmd/tf/descriptor/se_atten.py
Fix type issue in previous PR #3651.
=> fix(tf): fix foat32 for exclude_types in se_atten_v2

.readthedocs.yml
Per https://github.com/readthedocs/readthedocs-docker-images/issues/131#issuecomment-613624239, the solution is to install inkscape in the RTD environment.
See error in the log: https://readthedocs.org/projects/deepmd/builds/24116201/
```
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/deepmd/envs/latest/lib/python3.11/site-packages/sphinx/ext/imgconverter.py", line 59, in convert
subprocess.run(args, stdout=PIPE, stderr=PIPE, check=True)
File "/home/docs/.asdf/installs/python/3.11.6/lib/python3.11/subprocess.py", line 571, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['convert', '/home/docs/checkouts/readthedocs.org/user_builds/deepmd/checkouts/latest/doc/_static/pytorch.svg[0]', …
```
=> docs: fix convert svg error on RTD

.readthedocs.yml, doc/conf.py, doc/index.rst, doc/requirements.txt, pyproject.toml
Currently, the readthedocs build is terminated due to time out after 30 minutes on the devel branch, since it also builds other formats
1. Per https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html#document-python-modules-api-statically, autoapi might be faster.
2. Turn off epub and htmlzip. I don't think some one uses them.
=> docs: fix RTD timeout issue

deepmd/backend/dpmodel.py, deepmd/dpmodel/infer/deep_eval.py, deepmd/dpmodel/utils/__init__.py, deepmd/dpmodel/utils/network.py, deepmd/dpmodel/utils/serialization.py
=> chore(dpmodel): move save_dp_model and load_dp_model to a seperated module

source/tests/common/dpmodel/test_descriptor_se_r.py
=> test: add UTs for dp SeR

backend/find_tensorflow.py, deepmd/tf/env.py
After #3696, we don't need keras anymore.
=> build(tf): remove keras from dependencies

source/nodejs/yarn.lock
Closes #3665.
Bumps [tar](https://github.com/isaacs/node-tar) from 6.1.14 to 6.2.1.
- [Release notes](https://github.com/isaacs/node-tar/releases)
- [Changelog](https://github.com/isaacs/node-tar/blob/main/CHANGELOG.md)
- [Commits](https://github.com/isaacs/node-tar/compare/v6.1.14...v6.2.1)
---
updated-dependencies:
- dependency-name: tar
dependency-type: indirect
...
Signed-off-by: dependabot[bot] <support@github.com>
=> build(deps): bump tar from 6.1.14 to 6.2.1 in /source/nodejs

deepmd/dpmodel/descriptor/dpa1.py, source/tests/common/dpmodel/test_descriptor_hybrid.py
=> test(hybrid): add ut for descriptor hybrid

.github/workflows/test_python.yml, pyproject.toml, source/tests/tf/test_nvnmd_entrypoints.py
Split each pytest job into 6 separated jobs in GHA.
Currently, each separated job takes:
- ~2.5 min for installation, which may need to be optimized in the future;
- ~2 min for setup, which may be a defect and should be resolved in #3715;
-  4~5 min for tests (expected).
=> ci(test): split each pytest job into 6 separated jobs

deepmd/pt/entrypoints/main.py
`dp --pt freeze` does not output whether the operation finishes successfully. This PR adds a log message on it.
=> Feat: output logs on freezing models

.devcontainer/README.md, .devcontainer/gdb_pytest_lmp, .devcontainer/pytest_lmp
Introduce new scripts for running pytest with LAMMPS, enhancing the development environment for testing.
=> chore(dev): add pytest scripts for LAMMPS in devcontainer

deepmd/dpmodel/descriptor/dpa3.py, deepmd/pt/loss/ener.py, deepmd/pt/model/descriptor/__init__.py, deepmd/pt/model/descriptor/dpa3.py, deepmd/pt/model/descriptor/repflow_layer.py, deepmd/pt/model/descriptor/repflows.py, deepmd/pt/utils/utils.py, deepmd/utils/argcheck.py, source/tests/pt/model/test_dpa3.py, source/tests/universal/dpmodel/descriptor/test_descriptor.py, source/tests/universal/pt/descriptor/test_descriptor.py, source/tests/universal/pt/model/test_model.py
This PR is an early experimental preview version of DPA3. Significant changes may occur in subsequent updates. Please use with caution.
=> feat(pt): add dpa3 alpha descriptor
