deepmodeling/deepmd-kit

.travis.yml, source/cmake/Findtensorflow.cmake, source/op/soft_min.cc, source/tests/test_descrpt_nonsmth.py, source/tests/test_descrpt_se_r.py, source/tests/test_descrpt_smooth.py, source/tests/test_model_loc_frame.py, source/tests/test_model_se_a.py, source/tests/test_model_se_a_fparam.py, source/tests/test_model_se_a_srtab.py, source/tests/test_model_se_r.py, source/tests/test_tab_nonsmth.py, source/tests/test_tab_smooth.py
(Travis-CI doesn't seem to be opened)
=> add Travis-CI test && fix unittests

.travis.yml, README.md, pyproject.toml, setup.py
=> use "pip install ." to install deepmd-kit

source/train/CMakeLists.txt, source/train/__init__.py, source/train/env.py
have tested
**UPDATE:** only set for numpy built with mkl
=> set KMP_BLOCKTIME and KMP_AFFINITY variables

source/cmake/Findtensorflow.cmake
=> find libtensorflow_framework.so.1 for cpp

README.md, deepmd/__about__.py, doc/install-tf.1.14-gpu.md, setup.py, source/CMakeLists.txt, source/lib/CMakeLists.txt, source/lib/include/NNPInter.h, source/lib/src/NNPInter.cc, source/lmp/pair_nnp.cpp, source/lmp/pair_nnp.h.in, source/tests/test_deepmd_data_sys.py, source/train/DataSystem.py, source/train/__init__.py
additionally:
1, display version in python interface by deepmd.__version__
2, automatically determine the batch_size by using key "auto"
=> multi-gpu support in lammps mpi

doc/install-tf.1.14-gpu.md, doc/install-tf.1.14.md
=> simplify installation of TensorFlow

source/tests/test_deepmd_data.py, source/train/Data.py, source/train/DataSystem.py, source/train/train.py
according to type_map in model if it is not consistent with that defined in data
=> change data type

source/op/_prod_force_grad.py, source/op/_prod_force_se_a_grad.py, source/op/_prod_force_se_r_grad.py, source/op/_prod_virial_grad.py, source/op/_prod_virial_se_a_grad.py, source/op/_prod_virial_se_r_grad.py, source/op/_soft_min_force_grad.py, source/op/_soft_min_virial_grad.py, source/scripts/freeze.py, source/train/DeepEval.py, source/train/DescrptLocFrame.py, source/train/DescrptSeA.py, source/train/DescrptSeAR.py, source/train/DescrptSeR.py, source/train/Model.py, source/train/Trainer.py
Select the appropriate shared library suffix based on the operating system. I tested it on MacOS, no problem.
=> Select the appropriate shared library suffix based on the operating system

deepmd/__init__.py, examples/water/train/polar.json, examples/water/train/polar_se_a.json, examples/water/train/wannier.json, source/scripts/freeze.py, source/tests/test_wfc.py, source/tests/wfc.json, source/train/DeepDipole.py, source/train/Fitting.py, source/train/Loss.py, source/train/Model.py, source/train/Trainer.py, source/train/test.py
implement dipole model and test
refactorized Model and WFCLoss
=> Implement dipole

README.md
=> update installation methods

README.md, source/train/CMakeLists.txt, source/train/calculator.py
Example:
```python
from ase import Atoms
from deepmd.calculator import DP
water = Atoms('H2O',
positions=[(0.7601, 1.9270, 1),
(1.9575, 1, 1),
(1., 1., 1.)],
cell=[100, 100, 100],
calculator=DP(model="frozen_model.pb", type_map=['O', 'H']))
print(water.get_potential_energy())
print(water.get_forces())
```
Optimization is also available:
```python
from ase.optimize import BFGS
dyn = BFGS(water)
dyn.run(fmax=1e-6)
print(water.get_positions())
```
=> add an ASE calculator interface

source/lmp/pair_nnp.cpp
initialize host_name and host_names in function get_node_rank() at pair_nnp.cpp
=> initialize host_name before use

source/train/DescrptSeA.py, source/train/DescrptSeR.py
handle the case of std is almost 0
=> fix bug in descriptor nomalization

source/CMakeLists.txt
Co-authored-by: Linfeng Zhang <linfengz@princeton.edu>
=> set CMAKE_LINK_WHAT_YOU_USE flag (fix #163)

doc/install-tf.1.14.md
thanks Manyi Yang, who pointed out the issue
=> add the missing line for install-tf.1.14.md

source/train/DescrptSeA.py, source/train/DescrptSeR.py, source/train/Fitting.py, source/train/common.py
change activation function in input.json
=> user specified activation function for embedding and fitting nets

source/train/DescrptSeA.py, source/train/DescrptSeR.py, source/train/Fitting.py, source/train/Network.py, source/train/common.py
support only tf.float16, tf.float32 and tf.float64. 
tf.float16 may cause nan problem
=> user specified precision for embedding and fitting nets

source/train/DescrptSeA.py, source/train/DescrptSeR.py, source/train/Trainer.py
add type_one_side to se_r
change default rcut_smth
change energy loss type from `std` to `ener`
=> Updates on the descriptors

.travis.yml, README.md, setup.py
bump tf version to 2.3;
By the way:
* add tf to setup_require if it's not detected
* don't add cmake when it's installed
=> bump tensorflow version to 2.3

README.md
PS: we need to bump version for every release?
=> bump docker version in README

source/train/argcheck.py
numb_test can be input as str, int, or list not only list
=> fix error in definition of numb_test possible type

doc/train-input-auto.rst, source/tests/test_embedding_net.py, source/train/DescrptHybrid.py, source/train/DescrptSeA.py, source/train/DescrptSeAEbd.py, source/train/DescrptSeAT.py, source/train/DescrptSeR.py, source/train/Network.py, source/train/Trainer.py, source/train/argcheck.py
Refactorized embedding net
Implement three-body embedding and hybrid descriptors.
=> Three-body embedding

source/train/Loss.py, source/train/argcheck.py
compulsory key `loss`
compulsory label requirement
=> bug fixings

source/train/calculator.py
Dear Developers, 
I found an error in stress calculation using ASE interface. Thus, I made few changes in the `calculator.py`. 
First, the result types should be `float` for `energy`, `2d np.ndarray` for `forces`, and `3x3 np.ndarray` for `virial`. The old returned `energy` is an array, which is not inconsistent with other ase calculators. And the shape of `virial` is not restricted but I think the new one is better.   
Second, the old `stress` is incorrect and it does not simply equal DP calculated `virial`. Since ase defines tensile stress as the positive, the conversion follows `stress = -virial / volume`. Also, ase uses voigt notation to stores stress, which is transformed at last. 
Finally, I set the default calculated properties as `['energy', 'forces', 'virial']` and `stress` is …
=> fix an error in stress by ase interface

source/lib/include/CustomeOperation.h, source/op/cuda/descrpt_se_a.cu, source/op/cuda/descrpt_se_r.cu, source/op/descrpt_se_a_multi_device.cc, source/op/descrpt_se_r_multi_device.cc
When the number of sel is smaller than the lammps nbors, the program may have a gpu sorting error.
=> fix bug of nbor sorting

.github/workflows/test_python.yml
forgot to add environment variables
=> fix github actions

.github/workflows/lint_python.yml, .github/workflows/test_python.yml, requirements.txt, setup.py, source/train/Local.py
This PR aims to improve code quality by adding linting CI check. This [Action](https://github.com/marketplace/actions/python-lint-annotate-maintain-code-quality-with-annotated-prs-and-pushes) will run checks on PRs and all pushed code and annotate diffs to warn the author of the potential quality issues. Its function is only advisory I does not enforce the formatting merely warns the PR author and the reviewers about the potential code quality problems. If the produced suggestions are taken into account and the authors will implement the suggested changes it can in the long term help improve and maintain code quality. Currently enabled lintners are:
* black - strict code formatting check only suggests if the file should be reformatted
* mypy - static type checks can spot a lot of …
=> Lintner action

doc/developement.rst, doc/index.rst
I have drafted a proposition of coding style guidelines for contributors as discussed in #321. Essentially I took what they have in [ASE coding conventions](https://wiki.fysik.dtu.dk/ase/development/python_codingstandard.html) and reorganized it a bit + made a few changes and additions. I think this could help maintain code quality in the future. Any suggestions or criticism are welcome.
=> Propose coding guidelines - discussion

.github/workflows/test_python.yml, setup.py, source/tests/common.py, source/tests/test_class_arg.py, source/tests/test_compat_input.py, source/tests/test_data_modifier.py, source/tests/test_fitting_stat.py, source/tests/test_model_loc_frame.py, source/tests/test_model_se_a.py, source/tests/test_model_se_a_aparam.py, source/tests/test_model_se_a_fparam.py, source/tests/test_model_se_a_srtab.py, source/tests/test_model_se_r.py, source/tests/test_polar_se_a.py, source/tests/test_sel_idx.py, source/tests/test_wfc.py
=> use pytest and report coverage

source/op/cuda/descrpt_se_r.cu
- rm compute_t from descrpt_se_r.cu
=> fix a bug of single precision compilation

source/lib/include/common.h, source/lib/src/DataModifier.cc, source/lib/src/DeepTensor.cc, source/lib/src/NNPInter.cc
this will fix tf v2.3 build issues on r1.2
=> cherry-pick #276 to r1.2

deepmd/utils/neighbor_stat.py, examples/water/train/polar.json, examples/water/train/polar_se_a.json
- global type in lower case
- absolute path to data
=> bug fixings on api

source/api_cc/include/AtomMap.h, source/api_cc/include/DataModifier.h, source/api_cc/include/DeepPot.h, source/api_cc/include/DeepTensor.h, source/api_cc/include/common.h, source/api_cc/src/AtomMap.cc, source/api_cc/src/DataModifier.cc, source/api_cc/src/DeepPot.cc, source/api_cc/src/DeepTensor.cc, source/api_cc/src/common.cc, source/api_cc/tests/test_deeppot_a.cc, source/api_cc/tests/test_deeppot_model_devi.cc, source/api_cc/tests/test_deeppot_r.cc, source/api_cc/tests/test_dipolecharge.cc, source/cmake/cmake_lammps.cmake.in, source/ipi/driver.cc, source/lmp/CMakeLists.txt, source/lmp/fix_dplr.cpp, source/lmp/fix_dplr.h, source/lmp/pair_deepmd.cpp, source/lmp/pair_deepmd.h.in
`NNPInter` -> `DeepPot`
`NNPAtomMap` -> `AtomMap`
=> Update names of the c++ api

source/lib/src/prod_env_mat.cc
- first use cpu vector to store the nobr cpy, then copy it to the device through one cudaMemcpy API;
- performance is 93% compared to the master branch (nbor update every 10 steps), this pr is 98%;
=> reduce the usage of cudaMemcpy when update the gpu nbor list

source/api_cc/src/DeepPot.cc, source/api_cc/src/common.cc, source/api_cc/tests/test_deepdipole.cc, source/api_cc/tests/test_deeppolar.cc, source/api_cc/tests/test_deeppot_a.cc, source/api_cc/tests/test_deeppot_model_devi.cc, source/api_cc/tests/test_deeppot_r.cc, source/api_cc/tests/test_dipolecharge.cc, source/api_cc/tests/test_ewald.cc, source/api_cc/tests/test_utils.h, source/lib/include/Ewald.h, source/lib/include/ewald.h, source/lib/include/region.h, source/lib/src/ewald.cc, source/lib/src/region.cc, source/lib/tests/CMakeLists.txt, source/lib/tests/test_ewald.cc, source/lib/tests/test_simulation_region.cc, source/op/ewald_recp.cc, source/tests/test_ewald.py
- Fix bug of ewald recp
- add unittests for numerical force and virial
- add unittests for ewald
- remove dependency on `SimulationRegion`
=> Clean up ewald

source/api_cc/include/AtomMap.h, source/api_cc/include/DataModifier.h, source/api_cc/include/DeepPot.h, source/api_cc/include/DeepTensor.h, source/api_cc/include/common.h, source/api_cc/src/AtomMap.cc, source/api_cc/src/DataModifier.cc, source/api_cc/src/DeepPot.cc, source/api_cc/src/DeepTensor.cc, source/api_cc/src/common.cc, source/api_cc/tests/test_deepdipole.cc, source/api_cc/tests/test_deeppolar.cc, source/api_cc/tests/test_deeppot_a.cc, source/api_cc/tests/test_deeppot_model_devi.cc, source/api_cc/tests/test_deeppot_r.cc, source/api_cc/tests/test_dipolecharge.cc, source/ipi/driver.cc, source/lmp/env.sh.in, source/lmp/fix_dplr.cpp, source/lmp/fix_dplr.h, source/lmp/pair_deepmd.cpp, source/lmp/pair_deepmd.h.in
- Add `deepmd` namespace
- Explicit using of `tensorflow` namespace
- Fix some namespace related bugs
=> deepmd namespace for the C++ interface

deepmd/model/__init__.py, deepmd/model/ener.py, deepmd/model/model_stat.py, deepmd/model/tensor.py, deepmd/utils/argcheck.py, setup.py, source/tests/test_gen_stat_data.py, source/tests/test_model_loc_frame.py, source/tests/test_model_se_a.py, source/tests/test_model_se_a_aparam.py, source/tests/test_model_se_a_fparam.py, source/tests/test_model_se_a_srtab.py, source/tests/test_model_se_r.py, source/tests/test_polar_se_a.py, source/tests/test_tab_nonsmth.py, source/tests/test_tab_smooth.py, source/tests/test_wfc.py, source/train/CMakeLists.txt, source/train/trainer.py
- create `deepmd` module `model`
- create separate implementation for `EnerModel` and `TensorModel`.
=> refact model

.github/workflows/build_cc.yml, doc/install.md
Fix bugs in the instruction for installation.
=> update doc for installation

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/parameters.md
The tag of feature template and parameter template is changed automatically. Don't know why. Orz.
=> Change bug issue template according to what Yuzhi proposed.

deepmd/entrypoints/main.py, deepmd/entrypoints/test.py, deepmd/loss/tensor.py, source/tests/test_argument_parser.py
dp train / freeze / test check has finished, but tensorboard used in loss/tensor.py has not been tested yet.
Author: Haotian Ye (YWolfeee)
Date: 9, Apr, 2021.
=> API modification: support combined dipole training mode and global dipole test mode.

deepmd/utils/argcheck.py, examples/water/train/polar.json, examples/water/train/polar_se_a.json, examples/water/train/wannier.json, examples/water/train/water.json, examples/water/train/water_se_a.json, examples/water/train/water_se_ar.json, examples/water/train/water_se_r.json, examples/water/train/water_srtab_example.json, requirements.txt
- add argcheck for data modifier
- fix bugs in example input scripts
=> Add argcheck for data modifier. fix bugs

deepmd/utils/argcheck.py, doc/developement.rst
And also slightly changed the gen doc function to prevent an error when not setting make_anchor.
=> use new reference style in gen_doc

source/op/paddle_ops/srcs/pd_prod_env_mat_multi_devices_cpu.cc, source/op/paddle_ops/srcs/pd_prod_force_se_a_multi_devices_cpu.cc, source/op/paddle_ops/srcs/pd_prod_virial_se_a_multi_devices_cpu.cc, source/tests/test_pd_prod_force_and_virial.py
This PR support virial forward run on gpu with cpu kernel, this PR should be revert after virial forward CUDA kernel fixed by deepmd
=> Support virial forward run on gpu with cpu kernel

deepmd/train/trainer.py, deepmd/utils/argcheck.py
- `se_a` -> `se_e2_a`
- `se_r` -> `se_e2_r`
- `se_t` -> `se_e3`
check the items in the descriptor list of descriptor `hybrid`.
=> Changed name of descriptors. strict arg check of `hybrid`

examples/water/hybrid/input.json, examples/water/se_e2_a/input.json, examples/water/se_e2_r/input.json, examples/water/se_e3/input.json
Path to the dataset was wrong...
=> fix bugs in examples

README.md, doc/troubleshooting.md
move troubleshooting to a separate page
=> Add what's new in v2.0 to readme.

source/op/paddle_ops/srcs/pd_prod_env_mat_multi_devices_cpu.cc
This PR try to fix cpu error of prod mat env
=> fix error in cpu mode

deepmd/infer/deep_eval.py, deepmd/infer/deep_pot.py, deepmd/model/ener.py, deepmd/train/trainer.py
This PR support save load model with jit
=> support jist save load

source/api_cc/include/DeepPot.h, source/api_cc/src/DeepPot.cc, source/api_cc/tests/test_deeppot_model_devi.cc, source/lmp/pair_deepmd.cpp, source/lmp/pair_deepmd.h.in
- add model deviation and relative model deviation of virial
- refact the computation of std and relative std
- UT covering the case of relative std
=> Add model deviation of virial

.github/workflows/build_cc.yml, source/install/build_lammps.sh
=> test lammps builds

deepmd/train/trainer.py
=> fix TB logdir remove bug

doc/tensorboard.md
=> fix spell mistake

source/op/prod_virial_grad_multi_device.cc
=> fix bug in op definition prod_virial_grad_multi_device.cc. 

deepmd/descriptor/se_a.py, deepmd/fit/ener.py
=> fix bug in ener fitting: zero net should share the parameters with the working net

deepmd/op/__init__.py
=> `NOT_LOADABLE` should be `tuple`

deepmd/entrypoints/compress.py
=> also convert input v1 to v2 for dp compress

setup.py
fix #847.
See also sphinx-doc/sphinx#9433.
=> pin sphinx to a previous version

.github/workflows/build_wheel.yml
=> adapt changes to auditwheel directory in manylinux

deepmd/entrypoints/doc.py, deepmd/entrypoints/main.py, deepmd/utils/argcheck.py, requirements.txt, source/tests/test_argument_parser.py
waits deepmodeling/dargs#4 reviewed and merged, and new version of dargs published.
=> enhance the cli to generate doc json file

source/train/argcheck.py
=> fix a typo in #932

source/lib/src/gelu.cc, source/op/gelu_multi_device.cc
=> fix bug of gelu activation function

README.md
cherry pick #564
----
﻿- add more badges
- fix the document badge link
- remove conda badge as it doesn't work
=> cherry pick #564: add more badges

setup.py
This can fix some wired styles.
a wired style
=> bump sphinx_rtd_theme version

CITATION.cff
[GitHub just supported this feature](https://github.blog/2021-08-19-enhanced-support-citations-github/).
See [my branch](https://github.com/njzjz/deepmd-kit/tree/devel) to preview:
=> show citation in the GitHub

.readthedocs.yml, doc/environment.yml, setup.py
This fixes #847.
The idea comes fom https://github.com/readthedocs/readthedocs.org/issues/8151#issuecomment-890359661.
=> bump doxygen and sphinx version on RTD

doc/install/easy-install.md, doc/install/install-from-source.md, doc/train/parallel-training.md
as now easy installation also contains horovod, so we may want to discuss them separately
=> move horovod installation to installation part

source/cmake/googletest.cmake.in
See https://github.com/google/googletest/issues/3663
=> change googletest from master to main

requirements.txt
Same as https://github.com/deepmodeling/dpdata/pull/227.
=> add importlib_metadata as dependency

deepmd/descriptor/se_a.py, deepmd/descriptor/se_r.py, deepmd/descriptor/se_t.py
=> prevents rcut_smth larger than rcut

source/lib/include/ewald.h
=> make OpenMP an optional dependency

source/lmp/plugin/deepmdplugin.cpp
=> fix the name of deeptensor/atom and dplr plugin

deepmd/descriptor/se_a.py
#1573 has an issue: when the frozen graph is recovered again, `original_sel` is not the initial one (but the new one).
In this commit, `original_sel` will be saved into the graph.
=> restore original_sel in the graph

source/lib/src/cuda/CMakeLists.txt
the version should be >=11.5 instead of ==11.5
=> patch #1595: GREATER_EQUAL

doc/third-party/lammps-command.md, source/lmp/plugin/CMakeLists.txt
by setting the environmental variable `LAMMPS_PLUGIN_PATH`
=> add another way to load LAMMPS plugins

deepmd/entrypoints/compress.py
=> update compress cli input file

doc/install/easy-install.md
=> add tips for easy installation

deepmd/entrypoints/train.py
=> provide valid_data the same type_map as train_data

deepmd/train/trainer.py
Fix #1679.
The bug was introduced in #1610.
=> fix compress training

source/op/optimizer/parallel.cc, source/op/optimizer/parallel.h
=> fix grappler compilation error with TF 1.15 ~ 2.6

.github/workflows/build_cc.yml, .github/workflows/build_wheel.yml, .github/workflows/lint_python.yml, .github/workflows/test_cc.yml, .github/workflows/test_python.yml
related issue:
- https://github.com/actions/checkout/issues/760
- https://github.com/pypa/setuptools_scm/issues/707
=> fix git permission issue

source/api_cc/src/DeepPot.cc, source/lmp/pair_deepmd.cpp
=> correct type behavior when atomic energy is requested 

deepmd/entrypoints/compress.py
Windows platform has different slashes..
=> prevent explicit slash in the path

source/api_cc/include/common.h, source/api_cc/src/DeepPot.cc, source/api_cc/src/common.cc
=> throw warning in C++ if env is not set

source/CMakeLists.txt
=> avoid static CUDA linking

.github/labeler.yml, .github/workflows/labeler.yml
https://github.com/actions/labeler
=> Automatically label new pull requests based on the paths of files being changed

doc/install/install-from-source.md, source/install/build_tf.py
Here, CPU and CUDA versions are supported. ROCM is not supported. I need @denghuilu's help to support it
=> add a script to build TF C++ library from source

examples/fparam/train/input.json, examples/fparam/train/input_aparam.json, examples/water/se_e2_r/input.json, examples/water/se_e3/input.json, source/tests/test_examples.py
... and update some examples with depracated parameters.
=> add argument tests to check examples

doc/conf.py
exhale will run doxygen automatically, so there is no need to manually run it.
=> remove run_doxygen from sphinx conf.py

doc/api_op.rst, doc/conf.py, doc/index.rst, source/op/prod_env_mat_multi_device.cc
Also add op docs to ProdEnvMatA Op to show an example of how to write Op docs.
=> add op docs

source/api_cc/include/DataModifier.h, source/api_cc/include/DeepTensor.h, source/api_cc/src/DataModifier.cc, source/api_cc/src/DeepPot.cc, source/api_cc/src/DeepTensor.cc
Follow up #1789. It can be detected by valgrind.
=> fix memory leaking of GraphDef

source/lmp/pair_deepmd.cpp
=> add the missing sstream header

source/op/optimizer/parallel.h
See https://github.com/deepmodeling/deepmd-kit/issues/1746#issuecomment-1181271069
=> fix grappler compilation error with TF 1.15

doc/data/system.md
=> docs: fix shape of virial

deepmd/env.py, deepmd/train/trainer.py, pyproject.toml, source/CMakeLists.txt, source/cmake/Findtensorflow.cmake, source/op/optimizer/parallel.cc
=> fix build and running issues on Windows

deepmd/utils/tabulate.py
=> comment unused session in DPTabulate

doc/conf.py, doc/development/type-embedding.md, doc/install/easy-install.md, doc/model/train-se-e2-a-tebd.md, doc/train/training.md
Make warnings shown on the web page more prominent.
=> docs: make warnings more prominent

deepmd/entrypoints/main.py
=> add examples to cli help

setup.py
=> remove `get_platform` in setup.py

deepmd/nvnmd/entrypoints/wrap.py, doc/model/dplr.md, doc/third-party/lammps-command.md, doc/third-party/lammps.md, setup.py
See also https://github.com/lammps/pygments-lammps
=> highlight LAMMPS codes in doc

deepmd/utils/data.py
enforce type_map change when mixed_type.
add out_of_bound check for 'real_atom_types.npy'.
=> enforce type_map change when mixed_type

source/lib/include/SimulationRegion_Impl.h, source/lib/src/region.cc
Fixes  #972. See also https://math.stackexchange.com/q/829835
=> supports left hands volume

deepmd/common.py, deepmd/train/trainer.py, deepmd/utils/argcheck.py
=> support bfloat16

deepmd/entrypoints/main.py, doc/test/test.md
=> add dp test help doc

doc/development/cmake.md, examples/infer_water/.gitignore, examples/infer_water/CMakeLists.txt, examples/infer_water/README.md, examples/infer_water/infer_water.cpp, source/CMakeLists.txt, source/api_cc/CMakeLists.txt, source/cmake/Config.cmake.in, source/lib/CMakeLists.txt, source/lib/src/cuda/CMakeLists.txt, source/lib/src/rocm/CMakeLists.txt
Fix #2034. See `doc/development/cmake.md` for details.
=> export c++ library to cmake config

doc/development/cmake.md, examples/infer_water/.gitignore, examples/infer_water/CMakeLists.txt, examples/infer_water/README.md, examples/infer_water/infer_water.c, source/api_c/CMakeLists.txt
=> export C library to cmake config

doc/data/data-conv.md
=> docs: fix HDF5 path

.github/workflows/test_python.yml
See https://github.com/actions/runner-images/issues/6002
=> upgrade ubuntu-18.04

README.md, doc/train/parallel-training.md, doc/train/training-advanced.md, doc/troubleshooting/howtoset_num_nodes.md, doc/troubleshooting/index.md
This is a popular topic. I am not satisfied with the current documentation, so I rewrite it.
=> docs: rewrite docs for parallelism

source/api_c/tests/test_utils.h
=> fix the missing header in api_c tests

deepmd/nvnmd/utils/fio.py
=> optimize FioBin.save

deepmd/entrypoints/compress.py
=> open the graph file only once in compress

source/op/CMakeLists.txt
These files have been compiled in libdeepmd.so, so they don't need to compile again.
=> remove OP_LIB from op_abi

doc/install/install-lammps.md
=> docs: add a note about lammps runpath

doc/third-party/out-of-deepmd-kit.md
Signed-off-by: Chun Cai <amoycaic@gmail.com>
=> Add ABACUS to the interface part.

deepmd/entrypoints/test.py
=> fix per atom energy test results for multiple systems

deepmd/infer/deep_eval.py, source/tests/infer/se_e2_a_tebd.pbtxt, source/tests/test_deeppot_a.py
See the docstring for detials.
=> add `DeepEval.eval_typeebd` to get type embedding

deepmd/common.py, deepmd/descriptor/se_a_ebd.py, deepmd/fit/ener.py, deepmd/utils/data.py, deepmd/utils/data_system.py, source/tests/common.py
A loop using `np.append` is $O(N^2)$. See numpy/numpy#17090.
=> do not loop using `np.append`

deepmd/utils/argcheck.py
=> docs: fix the docs of numb_btch

pyproject.toml
Ref: https://github.com/h5py/h5py/issues/2215
=> pass `--prefer-binary` to cibuildwheel

.github/workflows/test_python.yml
per https://github.com/pypa/pip/issues/11770
=> temporarily pin pip to <23 

deepmd/descriptor/hybrid.py
Signed-off-by: Han Wang <wang_han@iapcm.ac.cn>
=> fix: provide get_nlist method for hybrid descriptor

.git-blame-ignore-revs
to ignore 97c38bb4235c9a440bd61a2459e330dba78269fa
=> add .git-blame-ignore-revs for git blame

deepmd/train/trainer.py
Fix bugs #2284 when using hybrid descriptor with se_atten
=> Fix bugs #2284 when using hybrid descriptor with se_atten

deepmd/train/trainer.py
=> print average training time

deepmd/descriptor/se_atten.py
Fix bug #2311 when using FP32 in se_atten
=> Fix bug #2311 when using FP32 in se_atten

backend/find_tensorflow.py
support detecting `TF_VERSION_SUFFIX`
=> fix TF version detection of release candidate version

.github/workflows/test_python.yml
=> unpin pip as the bug has been fixed

codecov.yml
I prefer manually check the coverage.
=> always pass the codecov status

source/lib/src/rocm/tabulate.hip.cu
=> fix ROCm tabulate_fusion_se_a_grad_fifth_order_polynomial

pyproject.toml
It looks like the `yum install` is broken. Switch to the local run file.
=> fix cuda installation for building wheels

codecov.yml
=> set Codecov patch threshold to 100%

source/lib/src/gelu.cc
=> enable openmp for gelu

source/api_cc/include/DeepPot.h, source/api_cc/src/DeepPot.cc
Remove `DeepPot::get_sel_a`, `DeepPotModelDevi::get_sel_a`, `cum_sum`, `graph_info`
=> clean unused methods in C++ API

deepmd/utils/data.py
Resovle #215, #745, #829, #990, #1335, #1625
=> raise a clear message when no set is found in a system

.github/workflows/build_wheel.yml
=> pin cibuildwheel to minor version

README.md
I just found it wrong after I clicked it...
=> docs: fix the link of DOI badge

doc/third-party/lammps-command.md, source/lmp/pair_deepmd.cpp, source/lmp/tests/test_dplr.py, source/lmp/tests/test_lammps.py, source/lmp/tests/test_lammps_3types.py
Fix #1935.
As this is a breaking change, it should be mentioned in the release note.
=>  breaking(lmp): fix definition of cvatom 

deepmd/entrypoints/test.py
Added atomic dipole to test.py
The current code did not cover this case.
=> Added atomic dipole to test.py

doc/install/install-from-source.md
=> docs: add docs for addtional CMake arguments via pip

CITATIONS.bib, doc/credits.rst
=> add citation for fparam

deepmd/utils/data.py
=> fix the issue of applying modifier multiple times when batch set is load only once

deepmd/fit/dos.py, deepmd/fit/ener.py, deepmd/model/dos.py, deepmd/model/ener.py, source/lmp/pair_deepmd.cpp
- fix bug in `Fitting.get_numb_aparam`
- fix bug in `Model.get_numb_param`
- fix bug in `make_fparam_from_compute` (interface to lammps)
=> fix typo about fparam/aparam

deepmd/utils/tabulate.py
`gelu_tf` is equivalent to `gelu`.
=> support compressing gelu_tf

deepmd/utils/data_system.py, source/tests/test_deepmd_data_sys.py
to be consistent with Pytorch version
=> merge prob_sys_size with prob_sys_size;0:nsys:1.0

pyproject.toml
=> bump scikit-build-core to 0.7

deepmd/descriptor/se_a.py
=> fix se_a_ebd_v2 when nloc != nall

.github/workflows/codeql.yml
It can scan the codes and report as follows:
=> add CodeQL checks

source/api_cc/src/DeepPot.cc
Fix:
- https://github.com/deepmodeling/deepmd-kit/security/code-scanning/1229
- https://github.com/deepmodeling/deepmd-kit/security/code-scanning/1230
- https://github.com/deepmodeling/deepmd-kit/security/code-scanning/1231
- https://github.com/deepmodeling/deepmd-kit/security/code-scanning/1232
=> Fix catching by value

doc/install/easy-install-dev.md, doc/install/install-from-c-library.md
The link was changed by #3070.
=> docs: update documentation for pre-compiled C library

deepmd_utils/model_format/__init__.py, deepmd_utils/model_format/network.py, deepmd_utils/model_format/se_e2_a.py, source/tests/test_model_format_utils.py
- add precision test for embedding net
Limitations 
- only support `type_one_side`
- does not support type embedding and `stripped_type_embedding`
- does not support `exclude_types`
- does not support spin
=> Add dp model format sea

source/api_cc/include/DeepTensor.h, source/api_cc/include/DeepTensorTF.h, source/api_cc/src/DeepTensor.cc, source/api_cc/src/DeepTensorTF.cc
=> cc: refactor DeepTensor for multiple-backend framework

pyproject.toml
This saves the time to load TensorFlow.
=> set dpgui entry point to `deepmd_utils`

deepmd/pt/train/training.py, deepmd/utils/argcheck.py, doc/train/tensorboard.md
Use the same arguments as TF.
[PyTorch on Tensorboard](https://pytorch.org/docs/stable/tensorboard.html):
[PyTorch Profiler on Tensorboard](https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html):
=> pt: add tensorboard and profiler support

doc/environment.yml
=> docs: install pytorch in RTD

deepmd/dpmodel/descriptor/make_base_descriptor.py, deepmd/pt/model/atomic_model/dp_atomic_model.py, deepmd/pt/model/descriptor/__init__.py, deepmd/pt/model/descriptor/descriptor.py, deepmd/pt/model/descriptor/dpa1.py, deepmd/pt/model/descriptor/dpa2.py, deepmd/pt/model/descriptor/gaussian_lcc.py, deepmd/pt/model/descriptor/se_a.py, deepmd/pt/model/model/__init__.py, source/tests/pt/model/test_polarizability_fitting.py
=> refact: pt: mv all plugin support to base descriptor. 

deepmd/fit/dipole.py, deepmd/infer/deep_eval.py, deepmd/infer/deep_tensor.py, deepmd/loss/tensor.py, deepmd/model/tensor.py, deepmd/train/trainer.py
Code reformat version of #3072 
Add water tensor dipole example
tensorflow: 
paddle(slightly better than tf):
=> [Paddle Backend] Add water tensor dipole(revert code format)

deepmd/dpmodel/descriptor/se_e2_a.py, deepmd/pt/model/descriptor/se_a.py, deepmd/tf/descriptor/se_atten.py
Add `se_a` to pt and dpmodel and add `dpa1` to tf.
=> sync descriptor alias

deepmd/fit/polar.py, deepmd/infer/deep_eval.py, deepmd/infer/deep_tensor.py, deepmd/model/tensor.py, deepmd/train/trainer.py
=> [Paddle Backend] Add tensor polar

deepmd/pt/model/task/invar_fitting.py
=> Fix: Invar_fitting warning msg

doc/conf.py
Refs:
* https://stackoverflow.com/questions/49898798/using-sphinx-extension-to-convert-svg-to-pdf
* https://www.sphinx-doc.org/en/master/usage/extensions/imgconverter.html
=> docs: fix pdf build due to svg
